@file:Suppress("warnings")
/*
 * This file is generated by jOOQ.
 */
package io.heapy.tgpt.database.indexes


import io.heapy.tgpt.database.tables.ApiCall
import io.heapy.tgpt.database.tables.Thread
import io.heapy.tgpt.database.tables.ThreadMessage

import org.jooq.Index
import org.jooq.impl.DSL
import org.jooq.impl.Internal



// -------------------------------------------------------------------------
// INDEX definitions
// -------------------------------------------------------------------------

val IDX_API_CALL_USER: Index = Internal.createIndex(DSL.name("idx_api_call_user"), ApiCall.API_CALL, arrayOf(ApiCall.API_CALL.TELEGRAM_USER_ID, ApiCall.API_CALL.CREATED), false)
val IDX_THREAD_CHAT: Index = Internal.createIndex(DSL.name("idx_thread_chat"), Thread.THREAD, arrayOf(Thread.THREAD.CHAT_ID), false)
val IDX_THREAD_MSG_TG: Index = Internal.createIndex(DSL.name("idx_thread_msg_tg"), ThreadMessage.THREAD_MESSAGE, arrayOf(ThreadMessage.THREAD_MESSAGE.THREAD_ID, ThreadMessage.THREAD_MESSAGE.TELEGRAM_MESSAGE_ID), false)
val IDX_THREAD_MSG_THREAD: Index = Internal.createIndex(DSL.name("idx_thread_msg_thread"), ThreadMessage.THREAD_MESSAGE, arrayOf(ThreadMessage.THREAD_MESSAGE.THREAD_ID, ThreadMessage.THREAD_MESSAGE.CREATED), false)
