/*
 * This file is generated by jOOQ.
 */
package io.heapy.kotbot.database


import io.heapy.kotbot.database.tables.CallbackData
import io.heapy.kotbot.database.tables.GarbageMessages
import io.heapy.kotbot.database.tables.GptSession
import io.heapy.kotbot.database.tables.GptSessionMessage
import io.heapy.kotbot.database.tables.JobExecution
import io.heapy.kotbot.database.tables.TelegramUser
import io.heapy.kotbot.database.tables.UpdateRaw

import kotlin.collections.List

import org.jooq.Catalog
import org.jooq.Table
import org.jooq.impl.DSL
import org.jooq.impl.SchemaImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class Public : SchemaImpl(DSL.name("public"), DefaultCatalog.DEFAULT_CATALOG, DSL.comment("")) {
    companion object {

        /**
         * The reference instance of <code>public</code>
         */
        val PUBLIC: Public = Public()
    }

    /**
     * The table <code>public.callback_data</code>.
     */
    val CALLBACK_DATA: CallbackData get() = CallbackData.CALLBACK_DATA

    /**
     * The table <code>public.garbage_messages</code>.
     */
    val GARBAGE_MESSAGES: GarbageMessages get() = GarbageMessages.GARBAGE_MESSAGES

    /**
     * The table <code>public.gpt_session</code>.
     */
    val GPT_SESSION: GptSession get() = GptSession.GPT_SESSION

    /**
     * The table <code>public.gpt_session_message</code>.
     */
    val GPT_SESSION_MESSAGE: GptSessionMessage get() = GptSessionMessage.GPT_SESSION_MESSAGE

    /**
     * The table <code>public.job_execution</code>.
     */
    val JOB_EXECUTION: JobExecution get() = JobExecution.JOB_EXECUTION

    /**
     * The table <code>public.telegram_user</code>.
     */
    val TELEGRAM_USER: TelegramUser get() = TelegramUser.TELEGRAM_USER

    /**
     * The table <code>public.update_raw</code>.
     */
    val UPDATE_RAW: UpdateRaw get() = UpdateRaw.UPDATE_RAW

    override fun getCatalog(): Catalog = DefaultCatalog.DEFAULT_CATALOG

    override fun getTables(): List<Table<*>> = listOf(
        CallbackData.CALLBACK_DATA,
        GarbageMessages.GARBAGE_MESSAGES,
        GptSession.GPT_SESSION,
        GptSessionMessage.GPT_SESSION_MESSAGE,
        JobExecution.JOB_EXECUTION,
        TelegramUser.TELEGRAM_USER,
        UpdateRaw.UPDATE_RAW
    )
}
