/*
 * This file is generated by jOOQ.
 */
package io.heapy.kotbot.database


import io.heapy.kotbot.database.tables.CallbackData
import io.heapy.kotbot.database.tables.GarbageMessages
import io.heapy.kotbot.database.tables.TelegramUser
import io.heapy.kotbot.database.tables.UpdateRaw

import kotlin.collections.List

import org.jooq.Catalog
import org.jooq.Table
import org.jooq.impl.SchemaImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class Public : SchemaImpl("public", DefaultCatalog.DEFAULT_CATALOG) {
    companion object {

        /**
         * The reference instance of <code>public</code>
         */
        val PUBLIC: Public = Public()
    }

    /**
     * The table <code>public.callback_data</code>.
     */
    val CALLBACK_DATA: CallbackData get() = CallbackData.CALLBACK_DATA

    /**
     * The table <code>public.garbage_messages</code>.
     */
    val GARBAGE_MESSAGES: GarbageMessages get() = GarbageMessages.GARBAGE_MESSAGES

    /**
     * The table <code>public.telegram_user</code>.
     */
    val TELEGRAM_USER: TelegramUser get() = TelegramUser.TELEGRAM_USER

    /**
     * The table <code>public.update_raw</code>.
     */
    val UPDATE_RAW: UpdateRaw get() = UpdateRaw.UPDATE_RAW

    override fun getCatalog(): Catalog = DefaultCatalog.DEFAULT_CATALOG

    override fun getTables(): List<Table<*>> = listOf(
        CallbackData.CALLBACK_DATA,
        GarbageMessages.GARBAGE_MESSAGES,
        TelegramUser.TELEGRAM_USER,
        UpdateRaw.UPDATE_RAW
    )
}
