/*
 * This file is generated by jOOQ.
 */
package io.heapy.tgpt.database.tables


import io.heapy.tgpt.database.Public
import io.heapy.tgpt.database.keys.ALLOWED_USER_PKEY
import io.heapy.tgpt.database.keys.ALLOWED_USER_TELEGRAM_ID_KEY
import io.heapy.tgpt.database.tables.records.AllowedUserRecord

import java.time.LocalDateTime

import kotlin.collections.Collection
import kotlin.collections.List

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Identity
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class AllowedUser(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, AllowedUserRecord>?,
    parentPath: InverseForeignKey<out Record, AllowedUserRecord>?,
    aliased: Table<AllowedUserRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<AllowedUserRecord>(
    alias,
    Public.PUBLIC,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>public.allowed_user</code>
         */
        val ALLOWED_USER: AllowedUser = AllowedUser()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<AllowedUserRecord> = AllowedUserRecord::class.java

    /**
     * The column <code>public.allowed_user.id</code>.
     */
    val ID: TableField<AllowedUserRecord, Long?> = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "")

    /**
     * The column <code>public.allowed_user.telegram_id</code>.
     */
    val TELEGRAM_ID: TableField<AllowedUserRecord, Long?> = createField(DSL.name("telegram_id"), SQLDataType.BIGINT.nullable(false), this, "")

    /**
     * The column <code>public.allowed_user.username</code>.
     */
    val USERNAME: TableField<AllowedUserRecord, String?> = createField(DSL.name("username"), SQLDataType.VARCHAR(255), this, "")

    /**
     * The column <code>public.allowed_user.display_name</code>.
     */
    val DISPLAY_NAME: TableField<AllowedUserRecord, String?> = createField(DSL.name("display_name"), SQLDataType.VARCHAR(255), this, "")

    /**
     * The column <code>public.allowed_user.is_active</code>.
     */
    val IS_ACTIVE: TableField<AllowedUserRecord, Boolean?> = createField(DSL.name("is_active"), SQLDataType.BOOLEAN.nullable(false).defaultValue(DSL.field(DSL.raw("true"), SQLDataType.BOOLEAN)), this, "")

    /**
     * The column <code>public.allowed_user.created</code>.
     */
    val CREATED: TableField<AllowedUserRecord, LocalDateTime?> = createField(DSL.name("created"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "")

    private constructor(alias: Name, aliased: Table<AllowedUserRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<AllowedUserRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<AllowedUserRecord>?, where: Condition?): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>public.allowed_user</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>public.allowed_user</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>public.allowed_user</code> table reference
     */
    constructor(): this(DSL.name("allowed_user"), null)
    override fun getSchema(): Schema? = if (aliased()) null else Public.PUBLIC
    override fun getIdentity(): Identity<AllowedUserRecord, Long?> = super.getIdentity() as Identity<AllowedUserRecord, Long?>
    override fun getPrimaryKey(): UniqueKey<AllowedUserRecord> = ALLOWED_USER_PKEY
    override fun getUniqueKeys(): List<UniqueKey<AllowedUserRecord>> = listOf(ALLOWED_USER_TELEGRAM_ID_KEY)
    override fun `as`(alias: String): AllowedUser = AllowedUser(DSL.name(alias), this)
    override fun `as`(alias: Name): AllowedUser = AllowedUser(alias, this)
    override fun `as`(alias: Table<*>): AllowedUser = AllowedUser(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): AllowedUser = AllowedUser(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): AllowedUser = AllowedUser(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): AllowedUser = AllowedUser(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): AllowedUser = AllowedUser(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): AllowedUser = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): AllowedUser = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): AllowedUser = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): AllowedUser = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): AllowedUser = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): AllowedUser = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): AllowedUser = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): AllowedUser = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): AllowedUser = where(DSL.notExists(select))
}
