/*
 * This file is generated by jOOQ.
 */
package io.heapy.tgpt.database.tables


import io.heapy.tgpt.database.Public
import io.heapy.tgpt.database.indexes.IDX_API_CALL_USER
import io.heapy.tgpt.database.keys.API_CALL_PKEY
import io.heapy.tgpt.database.keys.API_CALL__API_CALL_THREAD_ID_FKEY
import io.heapy.tgpt.database.tables.Thread.ThreadPath
import io.heapy.tgpt.database.tables.records.ApiCallRecord

import java.math.BigDecimal
import java.time.LocalDateTime

import kotlin.collections.Collection
import kotlin.collections.List

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Identity
import org.jooq.Index
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.Path
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class ApiCall(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, ApiCallRecord>?,
    parentPath: InverseForeignKey<out Record, ApiCallRecord>?,
    aliased: Table<ApiCallRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<ApiCallRecord>(
    alias,
    Public.PUBLIC,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>public.api_call</code>
         */
        val API_CALL: ApiCall = ApiCall()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<ApiCallRecord> = ApiCallRecord::class.java

    /**
     * The column <code>public.api_call.id</code>.
     */
    val ID: TableField<ApiCallRecord, Long?> = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "")

    /**
     * The column <code>public.api_call.thread_id</code>.
     */
    val THREAD_ID: TableField<ApiCallRecord, Long?> = createField(DSL.name("thread_id"), SQLDataType.BIGINT.nullable(false), this, "")

    /**
     * The column <code>public.api_call.telegram_user_id</code>.
     */
    val TELEGRAM_USER_ID: TableField<ApiCallRecord, Long?> = createField(DSL.name("telegram_user_id"), SQLDataType.BIGINT.nullable(false), this, "")

    /**
     * The column <code>public.api_call.model</code>.
     */
    val MODEL: TableField<ApiCallRecord, String?> = createField(DSL.name("model"), SQLDataType.VARCHAR(100).nullable(false), this, "")

    /**
     * The column <code>public.api_call.prompt_tokens</code>.
     */
    val PROMPT_TOKENS: TableField<ApiCallRecord, Int?> = createField(DSL.name("prompt_tokens"), SQLDataType.INTEGER.nullable(false), this, "")

    /**
     * The column <code>public.api_call.completion_tokens</code>.
     */
    val COMPLETION_TOKENS: TableField<ApiCallRecord, Int?> = createField(DSL.name("completion_tokens"), SQLDataType.INTEGER.nullable(false), this, "")

    /**
     * The column <code>public.api_call.total_tokens</code>.
     */
    val TOTAL_TOKENS: TableField<ApiCallRecord, Int?> = createField(DSL.name("total_tokens"), SQLDataType.INTEGER.nullable(false), this, "")

    /**
     * The column <code>public.api_call.estimated_cost_usd</code>.
     */
    val ESTIMATED_COST_USD: TableField<ApiCallRecord, BigDecimal?> = createField(DSL.name("estimated_cost_usd"), SQLDataType.NUMERIC(10, 6).nullable(false), this, "")

    /**
     * The column <code>public.api_call.created</code>.
     */
    val CREATED: TableField<ApiCallRecord, LocalDateTime?> = createField(DSL.name("created"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "")

    private constructor(alias: Name, aliased: Table<ApiCallRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<ApiCallRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<ApiCallRecord>?, where: Condition?): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>public.api_call</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>public.api_call</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>public.api_call</code> table reference
     */
    constructor(): this(DSL.name("api_call"), null)

    constructor(path: Table<out Record>, childPath: ForeignKey<out Record, ApiCallRecord>?, parentPath: InverseForeignKey<out Record, ApiCallRecord>?): this(Internal.createPathAlias(path, childPath, parentPath), path, childPath, parentPath, API_CALL, null, null)

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    open class ApiCallPath : ApiCall, Path<ApiCallRecord> {
        constructor(path: Table<out Record>, childPath: ForeignKey<out Record, ApiCallRecord>?, parentPath: InverseForeignKey<out Record, ApiCallRecord>?): super(path, childPath, parentPath)
        private constructor(alias: Name, aliased: Table<ApiCallRecord>): super(alias, aliased)
        override fun `as`(alias: String): ApiCallPath = ApiCallPath(DSL.name(alias), this)
        override fun `as`(alias: Name): ApiCallPath = ApiCallPath(alias, this)
        override fun `as`(alias: Table<*>): ApiCallPath = ApiCallPath(alias.qualifiedName, this)
    }
    override fun getSchema(): Schema? = if (aliased()) null else Public.PUBLIC
    override fun getIndexes(): List<Index> = listOf(IDX_API_CALL_USER)
    override fun getIdentity(): Identity<ApiCallRecord, Long?> = super.getIdentity() as Identity<ApiCallRecord, Long?>
    override fun getPrimaryKey(): UniqueKey<ApiCallRecord> = API_CALL_PKEY
    override fun getReferences(): List<ForeignKey<ApiCallRecord, *>> = listOf(API_CALL__API_CALL_THREAD_ID_FKEY)

    /**
     * Get the implicit join path to the <code>public.thread</code> table.
     */
    fun thread(): ThreadPath = thread
    val thread: ThreadPath by lazy { ThreadPath(this, API_CALL__API_CALL_THREAD_ID_FKEY, null) }
    override fun `as`(alias: String): ApiCall = ApiCall(DSL.name(alias), this)
    override fun `as`(alias: Name): ApiCall = ApiCall(alias, this)
    override fun `as`(alias: Table<*>): ApiCall = ApiCall(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): ApiCall = ApiCall(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): ApiCall = ApiCall(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): ApiCall = ApiCall(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): ApiCall = ApiCall(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): ApiCall = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): ApiCall = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): ApiCall = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): ApiCall = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): ApiCall = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): ApiCall = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): ApiCall = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): ApiCall = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): ApiCall = where(DSL.notExists(select))
}
