/*
 * This file is generated by jOOQ.
 */
package io.heapy.tgpt.database.tables


import io.heapy.tgpt.database.Public
import io.heapy.tgpt.database.indexes.IDX_THREAD_CHAT
import io.heapy.tgpt.database.keys.API_CALL__API_CALL_THREAD_ID_FKEY
import io.heapy.tgpt.database.keys.THREAD_MESSAGE__THREAD_MESSAGE_THREAD_ID_FKEY
import io.heapy.tgpt.database.keys.THREAD_PKEY
import io.heapy.tgpt.database.keys.THREAD__THREAD_FORKED_FROM_THREAD_ID_FKEY
import io.heapy.tgpt.database.tables.ApiCall.ApiCallPath
import io.heapy.tgpt.database.tables.Thread.ThreadPath
import io.heapy.tgpt.database.tables.ThreadMessage.ThreadMessagePath
import io.heapy.tgpt.database.tables.records.ThreadRecord

import java.time.LocalDateTime

import kotlin.collections.Collection
import kotlin.collections.List

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Identity
import org.jooq.Index
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.Path
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class Thread(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, ThreadRecord>?,
    parentPath: InverseForeignKey<out Record, ThreadRecord>?,
    aliased: Table<ThreadRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<ThreadRecord>(
    alias,
    Public.PUBLIC,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>public.thread</code>
         */
        val THREAD: Thread = Thread()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<ThreadRecord> = ThreadRecord::class.java

    /**
     * The column <code>public.thread.id</code>.
     */
    val ID: TableField<ThreadRecord, Long?> = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "")

    /**
     * The column <code>public.thread.chat_id</code>.
     */
    val CHAT_ID: TableField<ThreadRecord, Long?> = createField(DSL.name("chat_id"), SQLDataType.BIGINT.nullable(false), this, "")

    /**
     * The column <code>public.thread.created_by</code>.
     */
    val CREATED_BY: TableField<ThreadRecord, Long?> = createField(DSL.name("created_by"), SQLDataType.BIGINT.nullable(false), this, "")

    /**
     * The column <code>public.thread.forked_from_thread_id</code>.
     */
    val FORKED_FROM_THREAD_ID: TableField<ThreadRecord, Long?> = createField(DSL.name("forked_from_thread_id"), SQLDataType.BIGINT, this, "")

    /**
     * The column <code>public.thread.forked_at_message_id</code>.
     */
    val FORKED_AT_MESSAGE_ID: TableField<ThreadRecord, Long?> = createField(DSL.name("forked_at_message_id"), SQLDataType.BIGINT, this, "")

    /**
     * The column <code>public.thread.created</code>.
     */
    val CREATED: TableField<ThreadRecord, LocalDateTime?> = createField(DSL.name("created"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "")

    private constructor(alias: Name, aliased: Table<ThreadRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<ThreadRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<ThreadRecord>?, where: Condition?): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>public.thread</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>public.thread</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>public.thread</code> table reference
     */
    constructor(): this(DSL.name("thread"), null)

    constructor(path: Table<out Record>, childPath: ForeignKey<out Record, ThreadRecord>?, parentPath: InverseForeignKey<out Record, ThreadRecord>?): this(Internal.createPathAlias(path, childPath, parentPath), path, childPath, parentPath, THREAD, null, null)

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    open class ThreadPath : Thread, Path<ThreadRecord> {
        constructor(path: Table<out Record>, childPath: ForeignKey<out Record, ThreadRecord>?, parentPath: InverseForeignKey<out Record, ThreadRecord>?): super(path, childPath, parentPath)
        private constructor(alias: Name, aliased: Table<ThreadRecord>): super(alias, aliased)
        override fun `as`(alias: String): ThreadPath = ThreadPath(DSL.name(alias), this)
        override fun `as`(alias: Name): ThreadPath = ThreadPath(alias, this)
        override fun `as`(alias: Table<*>): ThreadPath = ThreadPath(alias.qualifiedName, this)
    }
    override fun getSchema(): Schema? = if (aliased()) null else Public.PUBLIC
    override fun getIndexes(): List<Index> = listOf(IDX_THREAD_CHAT)
    override fun getIdentity(): Identity<ThreadRecord, Long?> = super.getIdentity() as Identity<ThreadRecord, Long?>
    override fun getPrimaryKey(): UniqueKey<ThreadRecord> = THREAD_PKEY
    override fun getReferences(): List<ForeignKey<ThreadRecord, *>> = listOf(THREAD__THREAD_FORKED_FROM_THREAD_ID_FKEY)

    /**
     * Get the implicit join path to the <code>public.thread</code> table.
     */
    fun thread(): ThreadPath = thread
    val thread: ThreadPath by lazy { ThreadPath(this, THREAD__THREAD_FORKED_FROM_THREAD_ID_FKEY, null) }

    private lateinit var _apiCall: ApiCallPath

    /**
     * Get the implicit to-many join path to the <code>public.api_call</code>
     * table
     */
    fun apiCall(): ApiCallPath {
        if (!this::_apiCall.isInitialized)
            _apiCall = ApiCallPath(this, null, API_CALL__API_CALL_THREAD_ID_FKEY.inverseKey)

        return _apiCall;
    }

    val apiCall: ApiCallPath
        get(): ApiCallPath = apiCall()

    private lateinit var _threadMessage: ThreadMessagePath

    /**
     * Get the implicit to-many join path to the
     * <code>public.thread_message</code> table
     */
    fun threadMessage(): ThreadMessagePath {
        if (!this::_threadMessage.isInitialized)
            _threadMessage = ThreadMessagePath(this, null, THREAD_MESSAGE__THREAD_MESSAGE_THREAD_ID_FKEY.inverseKey)

        return _threadMessage;
    }

    val threadMessage: ThreadMessagePath
        get(): ThreadMessagePath = threadMessage()
    override fun `as`(alias: String): Thread = Thread(DSL.name(alias), this)
    override fun `as`(alias: Name): Thread = Thread(alias, this)
    override fun `as`(alias: Table<*>): Thread = Thread(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): Thread = Thread(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): Thread = Thread(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): Thread = Thread(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): Thread = Thread(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): Thread = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): Thread = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): Thread = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): Thread = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): Thread = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): Thread = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): Thread = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): Thread = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): Thread = where(DSL.notExists(select))
}
