/*
 * This file is generated by jOOQ.
 */
package io.heapy.tgpt.database.tables


import io.heapy.tgpt.database.Public
import io.heapy.tgpt.database.enums.ContentType
import io.heapy.tgpt.database.enums.MessageRole
import io.heapy.tgpt.database.indexes.IDX_THREAD_MSG_TG
import io.heapy.tgpt.database.indexes.IDX_THREAD_MSG_THREAD
import io.heapy.tgpt.database.keys.THREAD_MESSAGE_PKEY
import io.heapy.tgpt.database.keys.THREAD_MESSAGE__THREAD_MESSAGE_THREAD_ID_FKEY
import io.heapy.tgpt.database.tables.Thread.ThreadPath
import io.heapy.tgpt.database.tables.records.ThreadMessageRecord

import java.time.LocalDateTime

import kotlin.collections.Collection
import kotlin.collections.List

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Identity
import org.jooq.Index
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.Path
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class ThreadMessage(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, ThreadMessageRecord>?,
    parentPath: InverseForeignKey<out Record, ThreadMessageRecord>?,
    aliased: Table<ThreadMessageRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<ThreadMessageRecord>(
    alias,
    Public.PUBLIC,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>public.thread_message</code>
         */
        val THREAD_MESSAGE: ThreadMessage = ThreadMessage()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<ThreadMessageRecord> = ThreadMessageRecord::class.java

    /**
     * The column <code>public.thread_message.id</code>.
     */
    val ID: TableField<ThreadMessageRecord, Long?> = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "")

    /**
     * The column <code>public.thread_message.thread_id</code>.
     */
    val THREAD_ID: TableField<ThreadMessageRecord, Long?> = createField(DSL.name("thread_id"), SQLDataType.BIGINT.nullable(false), this, "")

    /**
     * The column <code>public.thread_message.role</code>.
     */
    val ROLE: TableField<ThreadMessageRecord, MessageRole?> = createField(DSL.name("role"), SQLDataType.VARCHAR.nullable(false).asEnumDataType(MessageRole::class.java), this, "")

    /**
     * The column <code>public.thread_message.content_type</code>.
     */
    val CONTENT_TYPE: TableField<ThreadMessageRecord, ContentType?> = createField(DSL.name("content_type"), SQLDataType.VARCHAR.nullable(false).defaultValue(DSL.field(DSL.raw("'text'::content_type"), SQLDataType.VARCHAR)).asEnumDataType(ContentType::class.java), this, "")

    /**
     * The column <code>public.thread_message.content</code>.
     */
    val CONTENT: TableField<ThreadMessageRecord, String?> = createField(DSL.name("content"), SQLDataType.CLOB.nullable(false), this, "")

    /**
     * The column <code>public.thread_message.telegram_message_id</code>.
     */
    val TELEGRAM_MESSAGE_ID: TableField<ThreadMessageRecord, Int?> = createField(DSL.name("telegram_message_id"), SQLDataType.INTEGER, this, "")

    /**
     * The column <code>public.thread_message.telegram_user_id</code>.
     */
    val TELEGRAM_USER_ID: TableField<ThreadMessageRecord, Long?> = createField(DSL.name("telegram_user_id"), SQLDataType.BIGINT, this, "")

    /**
     * The column <code>public.thread_message.created</code>.
     */
    val CREATED: TableField<ThreadMessageRecord, LocalDateTime?> = createField(DSL.name("created"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "")

    private constructor(alias: Name, aliased: Table<ThreadMessageRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<ThreadMessageRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<ThreadMessageRecord>?, where: Condition?): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>public.thread_message</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>public.thread_message</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>public.thread_message</code> table reference
     */
    constructor(): this(DSL.name("thread_message"), null)

    constructor(path: Table<out Record>, childPath: ForeignKey<out Record, ThreadMessageRecord>?, parentPath: InverseForeignKey<out Record, ThreadMessageRecord>?): this(Internal.createPathAlias(path, childPath, parentPath), path, childPath, parentPath, THREAD_MESSAGE, null, null)

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    open class ThreadMessagePath : ThreadMessage, Path<ThreadMessageRecord> {
        constructor(path: Table<out Record>, childPath: ForeignKey<out Record, ThreadMessageRecord>?, parentPath: InverseForeignKey<out Record, ThreadMessageRecord>?): super(path, childPath, parentPath)
        private constructor(alias: Name, aliased: Table<ThreadMessageRecord>): super(alias, aliased)
        override fun `as`(alias: String): ThreadMessagePath = ThreadMessagePath(DSL.name(alias), this)
        override fun `as`(alias: Name): ThreadMessagePath = ThreadMessagePath(alias, this)
        override fun `as`(alias: Table<*>): ThreadMessagePath = ThreadMessagePath(alias.qualifiedName, this)
    }
    override fun getSchema(): Schema? = if (aliased()) null else Public.PUBLIC
    override fun getIndexes(): List<Index> = listOf(IDX_THREAD_MSG_TG, IDX_THREAD_MSG_THREAD)
    override fun getIdentity(): Identity<ThreadMessageRecord, Long?> = super.getIdentity() as Identity<ThreadMessageRecord, Long?>
    override fun getPrimaryKey(): UniqueKey<ThreadMessageRecord> = THREAD_MESSAGE_PKEY
    override fun getReferences(): List<ForeignKey<ThreadMessageRecord, *>> = listOf(THREAD_MESSAGE__THREAD_MESSAGE_THREAD_ID_FKEY)

    /**
     * Get the implicit join path to the <code>public.thread</code> table.
     */
    fun thread(): ThreadPath = thread
    val thread: ThreadPath by lazy { ThreadPath(this, THREAD_MESSAGE__THREAD_MESSAGE_THREAD_ID_FKEY, null) }
    override fun `as`(alias: String): ThreadMessage = ThreadMessage(DSL.name(alias), this)
    override fun `as`(alias: Name): ThreadMessage = ThreadMessage(alias, this)
    override fun `as`(alias: Table<*>): ThreadMessage = ThreadMessage(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): ThreadMessage = ThreadMessage(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): ThreadMessage = ThreadMessage(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): ThreadMessage = ThreadMessage(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): ThreadMessage = ThreadMessage(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): ThreadMessage = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): ThreadMessage = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): ThreadMessage = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): ThreadMessage = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): ThreadMessage = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): ThreadMessage = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): ThreadMessage = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): ThreadMessage = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): ThreadMessage = where(DSL.notExists(select))
}
