/*
 * This file is generated by jOOQ.
 */
package io.heapy.tgpt.database.enums


import io.heapy.tgpt.database.Public

import org.jooq.Catalog
import org.jooq.EnumType
import org.jooq.Schema


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
enum class MessageRole(@get:JvmName("literal") public val literal: String) : EnumType {
    system("system"),
    user("user"),
    assistant("assistant");
    override fun getCatalog(): Catalog? = schema.catalog
    override fun getSchema(): Schema = Public.PUBLIC
    override fun getName(): String = "message_role"
    override fun getLiteral(): String = literal
}
