/*
 * This file is generated by jOOQ.
 */
package io.heapy.kotbot.database.tables.daos


import io.heapy.kotbot.database.tables.CallbackData
import io.heapy.kotbot.database.tables.records.CallbackDataRecord

import java.time.LocalDateTime
import java.util.UUID

import kotlin.collections.List

import org.jooq.Configuration
import org.jooq.JSONB
import org.jooq.impl.DAOImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class CallbackDataDao(configuration: Configuration?) : DAOImpl<CallbackDataRecord, io.heapy.kotbot.database.tables.pojos.CallbackData, UUID>(CallbackData.CALLBACK_DATA, io.heapy.kotbot.database.tables.pojos.CallbackData::class.java, configuration) {

    /**
     * Create a new CallbackDataDao without any configuration
     */
    constructor(): this(null)

    override fun getId(o: io.heapy.kotbot.database.tables.pojos.CallbackData): UUID? = o.id

    /**
     * Fetch records that have <code>id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    fun fetchRangeOfId(lowerInclusive: UUID?, upperInclusive: UUID?): List<io.heapy.kotbot.database.tables.pojos.CallbackData> = fetchRange(CallbackData.CALLBACK_DATA.ID, lowerInclusive, upperInclusive)

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    fun fetchById(vararg values: UUID): List<io.heapy.kotbot.database.tables.pojos.CallbackData> = fetch(CallbackData.CALLBACK_DATA.ID, *values)

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    fun fetchOneById(value: UUID): io.heapy.kotbot.database.tables.pojos.CallbackData? = fetchOne(CallbackData.CALLBACK_DATA.ID, value)

    /**
     * Fetch records that have <code>data BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    fun fetchRangeOfData(lowerInclusive: JSONB, upperInclusive: JSONB): List<io.heapy.kotbot.database.tables.pojos.CallbackData> = fetchRange(CallbackData.CALLBACK_DATA.DATA, lowerInclusive, upperInclusive)

    /**
     * Fetch records that have <code>data IN (values)</code>
     */
    fun fetchByData(vararg values: JSONB): List<io.heapy.kotbot.database.tables.pojos.CallbackData> = fetch(CallbackData.CALLBACK_DATA.DATA, *values)

    /**
     * Fetch records that have <code>type BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    fun fetchRangeOfType(lowerInclusive: String, upperInclusive: String): List<io.heapy.kotbot.database.tables.pojos.CallbackData> = fetchRange(CallbackData.CALLBACK_DATA.TYPE, lowerInclusive, upperInclusive)

    /**
     * Fetch records that have <code>type IN (values)</code>
     */
    fun fetchByType(vararg values: String): List<io.heapy.kotbot.database.tables.pojos.CallbackData> = fetch(CallbackData.CALLBACK_DATA.TYPE, *values)

    /**
     * Fetch records that have <code>created BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    fun fetchRangeOfCreated(lowerInclusive: LocalDateTime, upperInclusive: LocalDateTime): List<io.heapy.kotbot.database.tables.pojos.CallbackData> = fetchRange(CallbackData.CALLBACK_DATA.CREATED, lowerInclusive, upperInclusive)

    /**
     * Fetch records that have <code>created IN (values)</code>
     */
    fun fetchByCreated(vararg values: LocalDateTime): List<io.heapy.kotbot.database.tables.pojos.CallbackData> = fetch(CallbackData.CALLBACK_DATA.CREATED, *values)
}
