/*
 * This file is generated by jOOQ.
 */
package io.heapy.kotbot.database.tables.daos


import io.heapy.kotbot.database.tables.ChallengeAttempt
import io.heapy.kotbot.database.tables.records.ChallengeAttemptRecord

import java.time.LocalDateTime
import java.util.UUID

import kotlin.collections.List

import org.jooq.Configuration
import org.jooq.impl.DAOImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class ChallengeAttemptDao(configuration: Configuration?) : DAOImpl<ChallengeAttemptRecord, io.heapy.kotbot.database.tables.pojos.ChallengeAttempt, Long>(ChallengeAttempt.CHALLENGE_ATTEMPT, io.heapy.kotbot.database.tables.pojos.ChallengeAttempt::class.java, configuration) {

    /**
     * Create a new ChallengeAttemptDao without any configuration
     */
    constructor(): this(null)

    override fun getId(o: io.heapy.kotbot.database.tables.pojos.ChallengeAttempt): Long? = o.id

    /**
     * Fetch records that have <code>id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    fun fetchRangeOfId(lowerInclusive: Long?, upperInclusive: Long?): List<io.heapy.kotbot.database.tables.pojos.ChallengeAttempt> = fetchRange(ChallengeAttempt.CHALLENGE_ATTEMPT.ID, lowerInclusive, upperInclusive)

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    fun fetchById(vararg values: Long): List<io.heapy.kotbot.database.tables.pojos.ChallengeAttempt> = fetch(ChallengeAttempt.CHALLENGE_ATTEMPT.ID, *values.toTypedArray())

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    fun fetchOneById(value: Long): io.heapy.kotbot.database.tables.pojos.ChallengeAttempt? = fetchOne(ChallengeAttempt.CHALLENGE_ATTEMPT.ID, value)

    /**
     * Fetch records that have <code>session_id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    fun fetchRangeOfSessionId(lowerInclusive: Long, upperInclusive: Long): List<io.heapy.kotbot.database.tables.pojos.ChallengeAttempt> = fetchRange(ChallengeAttempt.CHALLENGE_ATTEMPT.SESSION_ID, lowerInclusive, upperInclusive)

    /**
     * Fetch records that have <code>session_id IN (values)</code>
     */
    fun fetchBySessionId(vararg values: Long): List<io.heapy.kotbot.database.tables.pojos.ChallengeAttempt> = fetch(ChallengeAttempt.CHALLENGE_ATTEMPT.SESSION_ID, *values.toTypedArray())

    /**
     * Fetch records that have <code>telegram_id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    fun fetchRangeOfTelegramId(lowerInclusive: Long, upperInclusive: Long): List<io.heapy.kotbot.database.tables.pojos.ChallengeAttempt> = fetchRange(ChallengeAttempt.CHALLENGE_ATTEMPT.TELEGRAM_ID, lowerInclusive, upperInclusive)

    /**
     * Fetch records that have <code>telegram_id IN (values)</code>
     */
    fun fetchByTelegramId(vararg values: Long): List<io.heapy.kotbot.database.tables.pojos.ChallengeAttempt> = fetch(ChallengeAttempt.CHALLENGE_ATTEMPT.TELEGRAM_ID, *values.toTypedArray())

    /**
     * Fetch records that have <code>challenge_id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    fun fetchRangeOfChallengeId(lowerInclusive: UUID, upperInclusive: UUID): List<io.heapy.kotbot.database.tables.pojos.ChallengeAttempt> = fetchRange(ChallengeAttempt.CHALLENGE_ATTEMPT.CHALLENGE_ID, lowerInclusive, upperInclusive)

    /**
     * Fetch records that have <code>challenge_id IN (values)</code>
     */
    fun fetchByChallengeId(vararg values: UUID): List<io.heapy.kotbot.database.tables.pojos.ChallengeAttempt> = fetch(ChallengeAttempt.CHALLENGE_ATTEMPT.CHALLENGE_ID, *values)

    /**
     * Fetch records that have <code>template_key BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    fun fetchRangeOfTemplateKey(lowerInclusive: String, upperInclusive: String): List<io.heapy.kotbot.database.tables.pojos.ChallengeAttempt> = fetchRange(ChallengeAttempt.CHALLENGE_ATTEMPT.TEMPLATE_KEY, lowerInclusive, upperInclusive)

    /**
     * Fetch records that have <code>template_key IN (values)</code>
     */
    fun fetchByTemplateKey(vararg values: String): List<io.heapy.kotbot.database.tables.pojos.ChallengeAttempt> = fetch(ChallengeAttempt.CHALLENGE_ATTEMPT.TEMPLATE_KEY, *values)

    /**
     * Fetch records that have <code>selected_answer BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    fun fetchRangeOfSelectedAnswer(lowerInclusive: String, upperInclusive: String): List<io.heapy.kotbot.database.tables.pojos.ChallengeAttempt> = fetchRange(ChallengeAttempt.CHALLENGE_ATTEMPT.SELECTED_ANSWER, lowerInclusive, upperInclusive)

    /**
     * Fetch records that have <code>selected_answer IN (values)</code>
     */
    fun fetchBySelectedAnswer(vararg values: String): List<io.heapy.kotbot.database.tables.pojos.ChallengeAttempt> = fetch(ChallengeAttempt.CHALLENGE_ATTEMPT.SELECTED_ANSWER, *values)

    /**
     * Fetch records that have <code>correct_answer BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    fun fetchRangeOfCorrectAnswer(lowerInclusive: String, upperInclusive: String): List<io.heapy.kotbot.database.tables.pojos.ChallengeAttempt> = fetchRange(ChallengeAttempt.CHALLENGE_ATTEMPT.CORRECT_ANSWER, lowerInclusive, upperInclusive)

    /**
     * Fetch records that have <code>correct_answer IN (values)</code>
     */
    fun fetchByCorrectAnswer(vararg values: String): List<io.heapy.kotbot.database.tables.pojos.ChallengeAttempt> = fetch(ChallengeAttempt.CHALLENGE_ATTEMPT.CORRECT_ANSWER, *values)

    /**
     * Fetch records that have <code>is_correct BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    fun fetchRangeOfIsCorrect(lowerInclusive: Boolean, upperInclusive: Boolean): List<io.heapy.kotbot.database.tables.pojos.ChallengeAttempt> = fetchRange(ChallengeAttempt.CHALLENGE_ATTEMPT.IS_CORRECT, lowerInclusive, upperInclusive)

    /**
     * Fetch records that have <code>is_correct IN (values)</code>
     */
    fun fetchByIsCorrect(vararg values: Boolean): List<io.heapy.kotbot.database.tables.pojos.ChallengeAttempt> = fetch(ChallengeAttempt.CHALLENGE_ATTEMPT.IS_CORRECT, *values.toTypedArray())

    /**
     * Fetch records that have <code>challenge_sent_at BETWEEN lowerInclusive
     * AND upperInclusive</code>
     */
    fun fetchRangeOfChallengeSentAt(lowerInclusive: LocalDateTime, upperInclusive: LocalDateTime): List<io.heapy.kotbot.database.tables.pojos.ChallengeAttempt> = fetchRange(ChallengeAttempt.CHALLENGE_ATTEMPT.CHALLENGE_SENT_AT, lowerInclusive, upperInclusive)

    /**
     * Fetch records that have <code>challenge_sent_at IN (values)</code>
     */
    fun fetchByChallengeSentAt(vararg values: LocalDateTime): List<io.heapy.kotbot.database.tables.pojos.ChallengeAttempt> = fetch(ChallengeAttempt.CHALLENGE_ATTEMPT.CHALLENGE_SENT_AT, *values)

    /**
     * Fetch records that have <code>answered_at BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    fun fetchRangeOfAnsweredAt(lowerInclusive: LocalDateTime?, upperInclusive: LocalDateTime?): List<io.heapy.kotbot.database.tables.pojos.ChallengeAttempt> = fetchRange(ChallengeAttempt.CHALLENGE_ATTEMPT.ANSWERED_AT, lowerInclusive, upperInclusive)

    /**
     * Fetch records that have <code>answered_at IN (values)</code>
     */
    fun fetchByAnsweredAt(vararg values: LocalDateTime): List<io.heapy.kotbot.database.tables.pojos.ChallengeAttempt> = fetch(ChallengeAttempt.CHALLENGE_ATTEMPT.ANSWERED_AT, *values)

    /**
     * Fetch records that have <code>latency_ms BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    fun fetchRangeOfLatencyMs(lowerInclusive: Long, upperInclusive: Long): List<io.heapy.kotbot.database.tables.pojos.ChallengeAttempt> = fetchRange(ChallengeAttempt.CHALLENGE_ATTEMPT.LATENCY_MS, lowerInclusive, upperInclusive)

    /**
     * Fetch records that have <code>latency_ms IN (values)</code>
     */
    fun fetchByLatencyMs(vararg values: Long): List<io.heapy.kotbot.database.tables.pojos.ChallengeAttempt> = fetch(ChallengeAttempt.CHALLENGE_ATTEMPT.LATENCY_MS, *values.toTypedArray())
}
