/*
 * This file is generated by jOOQ.
 */
package io.heapy.kotbot.database.tables.daos


import io.heapy.kotbot.database.tables.GptSession
import io.heapy.kotbot.database.tables.records.GptSessionRecord

import java.time.LocalDateTime

import kotlin.collections.List

import org.jooq.Configuration
import org.jooq.impl.DAOImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class GptSessionDao(configuration: Configuration?) : DAOImpl<GptSessionRecord, io.heapy.kotbot.database.tables.pojos.GptSession, Long>(GptSession.GPT_SESSION, io.heapy.kotbot.database.tables.pojos.GptSession::class.java, configuration) {

    /**
     * Create a new GptSessionDao without any configuration
     */
    constructor(): this(null)

    override fun getId(o: io.heapy.kotbot.database.tables.pojos.GptSession): Long? = o.id

    /**
     * Fetch records that have <code>id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    fun fetchRangeOfId(lowerInclusive: Long?, upperInclusive: Long?): List<io.heapy.kotbot.database.tables.pojos.GptSession> = fetchRange(GptSession.GPT_SESSION.ID, lowerInclusive, upperInclusive)

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    fun fetchById(vararg values: Long): List<io.heapy.kotbot.database.tables.pojos.GptSession> = fetch(GptSession.GPT_SESSION.ID, *values.toTypedArray())

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    fun fetchOneById(value: Long): io.heapy.kotbot.database.tables.pojos.GptSession? = fetchOne(GptSession.GPT_SESSION.ID, value)

    /**
     * Fetch records that have <code>user_id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    fun fetchRangeOfUserId(lowerInclusive: Long, upperInclusive: Long): List<io.heapy.kotbot.database.tables.pojos.GptSession> = fetchRange(GptSession.GPT_SESSION.USER_ID, lowerInclusive, upperInclusive)

    /**
     * Fetch records that have <code>user_id IN (values)</code>
     */
    fun fetchByUserId(vararg values: Long): List<io.heapy.kotbot.database.tables.pojos.GptSession> = fetch(GptSession.GPT_SESSION.USER_ID, *values.toTypedArray())

    /**
     * Fetch records that have <code>group_chat_id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    fun fetchRangeOfGroupChatId(lowerInclusive: Long, upperInclusive: Long): List<io.heapy.kotbot.database.tables.pojos.GptSession> = fetchRange(GptSession.GPT_SESSION.GROUP_CHAT_ID, lowerInclusive, upperInclusive)

    /**
     * Fetch records that have <code>group_chat_id IN (values)</code>
     */
    fun fetchByGroupChatId(vararg values: Long): List<io.heapy.kotbot.database.tables.pojos.GptSession> = fetch(GptSession.GPT_SESSION.GROUP_CHAT_ID, *values.toTypedArray())

    /**
     * Fetch records that have <code>wait_message_id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    fun fetchRangeOfWaitMessageId(lowerInclusive: Int, upperInclusive: Int): List<io.heapy.kotbot.database.tables.pojos.GptSession> = fetchRange(GptSession.GPT_SESSION.WAIT_MESSAGE_ID, lowerInclusive, upperInclusive)

    /**
     * Fetch records that have <code>wait_message_id IN (values)</code>
     */
    fun fetchByWaitMessageId(vararg values: Int): List<io.heapy.kotbot.database.tables.pojos.GptSession> = fetch(GptSession.GPT_SESSION.WAIT_MESSAGE_ID, *values.toTypedArray())

    /**
     * Fetch records that have <code>preview_chat_id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    fun fetchRangeOfPreviewChatId(lowerInclusive: Long?, upperInclusive: Long?): List<io.heapy.kotbot.database.tables.pojos.GptSession> = fetchRange(GptSession.GPT_SESSION.PREVIEW_CHAT_ID, lowerInclusive, upperInclusive)

    /**
     * Fetch records that have <code>preview_chat_id IN (values)</code>
     */
    fun fetchByPreviewChatId(vararg values: Long): List<io.heapy.kotbot.database.tables.pojos.GptSession> = fetch(GptSession.GPT_SESSION.PREVIEW_CHAT_ID, *values.toTypedArray())

    /**
     * Fetch records that have <code>preview_message_id BETWEEN lowerInclusive
     * AND upperInclusive</code>
     */
    fun fetchRangeOfPreviewMessageId(lowerInclusive: Int?, upperInclusive: Int?): List<io.heapy.kotbot.database.tables.pojos.GptSession> = fetchRange(GptSession.GPT_SESSION.PREVIEW_MESSAGE_ID, lowerInclusive, upperInclusive)

    /**
     * Fetch records that have <code>preview_message_id IN (values)</code>
     */
    fun fetchByPreviewMessageId(vararg values: Int): List<io.heapy.kotbot.database.tables.pojos.GptSession> = fetch(GptSession.GPT_SESSION.PREVIEW_MESSAGE_ID, *values.toTypedArray())

    /**
     * Fetch records that have <code>status BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    fun fetchRangeOfStatus(lowerInclusive: String?, upperInclusive: String?): List<io.heapy.kotbot.database.tables.pojos.GptSession> = fetchRange(GptSession.GPT_SESSION.STATUS, lowerInclusive, upperInclusive)

    /**
     * Fetch records that have <code>status IN (values)</code>
     */
    fun fetchByStatus(vararg values: String): List<io.heapy.kotbot.database.tables.pojos.GptSession> = fetch(GptSession.GPT_SESSION.STATUS, *values)

    /**
     * Fetch records that have <code>created BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    fun fetchRangeOfCreated(lowerInclusive: LocalDateTime?, upperInclusive: LocalDateTime?): List<io.heapy.kotbot.database.tables.pojos.GptSession> = fetchRange(GptSession.GPT_SESSION.CREATED, lowerInclusive, upperInclusive)

    /**
     * Fetch records that have <code>created IN (values)</code>
     */
    fun fetchByCreated(vararg values: LocalDateTime): List<io.heapy.kotbot.database.tables.pojos.GptSession> = fetch(GptSession.GPT_SESSION.CREATED, *values)
}
