/*
 * This file is generated by jOOQ.
 */
package io.heapy.kotbot.database.tables.daos


import io.heapy.kotbot.database.tables.GptSessionMessage
import io.heapy.kotbot.database.tables.records.GptSessionMessageRecord

import java.time.LocalDateTime

import kotlin.collections.List

import org.jooq.Configuration
import org.jooq.impl.DAOImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class GptSessionMessageDao(configuration: Configuration?) : DAOImpl<GptSessionMessageRecord, io.heapy.kotbot.database.tables.pojos.GptSessionMessage, Long>(GptSessionMessage.GPT_SESSION_MESSAGE, io.heapy.kotbot.database.tables.pojos.GptSessionMessage::class.java, configuration) {

    /**
     * Create a new GptSessionMessageDao without any configuration
     */
    constructor(): this(null)

    override fun getId(o: io.heapy.kotbot.database.tables.pojos.GptSessionMessage): Long? = o.id

    /**
     * Fetch records that have <code>id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    fun fetchRangeOfId(lowerInclusive: Long?, upperInclusive: Long?): List<io.heapy.kotbot.database.tables.pojos.GptSessionMessage> = fetchRange(GptSessionMessage.GPT_SESSION_MESSAGE.ID, lowerInclusive, upperInclusive)

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    fun fetchById(vararg values: Long): List<io.heapy.kotbot.database.tables.pojos.GptSessionMessage> = fetch(GptSessionMessage.GPT_SESSION_MESSAGE.ID, *values.toTypedArray())

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    fun fetchOneById(value: Long): io.heapy.kotbot.database.tables.pojos.GptSessionMessage? = fetchOne(GptSessionMessage.GPT_SESSION_MESSAGE.ID, value)

    /**
     * Fetch records that have <code>session_id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    fun fetchRangeOfSessionId(lowerInclusive: Long, upperInclusive: Long): List<io.heapy.kotbot.database.tables.pojos.GptSessionMessage> = fetchRange(GptSessionMessage.GPT_SESSION_MESSAGE.SESSION_ID, lowerInclusive, upperInclusive)

    /**
     * Fetch records that have <code>session_id IN (values)</code>
     */
    fun fetchBySessionId(vararg values: Long): List<io.heapy.kotbot.database.tables.pojos.GptSessionMessage> = fetch(GptSessionMessage.GPT_SESSION_MESSAGE.SESSION_ID, *values.toTypedArray())

    /**
     * Fetch records that have <code>role BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    fun fetchRangeOfRole(lowerInclusive: String, upperInclusive: String): List<io.heapy.kotbot.database.tables.pojos.GptSessionMessage> = fetchRange(GptSessionMessage.GPT_SESSION_MESSAGE.ROLE, lowerInclusive, upperInclusive)

    /**
     * Fetch records that have <code>role IN (values)</code>
     */
    fun fetchByRole(vararg values: String): List<io.heapy.kotbot.database.tables.pojos.GptSessionMessage> = fetch(GptSessionMessage.GPT_SESSION_MESSAGE.ROLE, *values)

    /**
     * Fetch records that have <code>content BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    fun fetchRangeOfContent(lowerInclusive: String, upperInclusive: String): List<io.heapy.kotbot.database.tables.pojos.GptSessionMessage> = fetchRange(GptSessionMessage.GPT_SESSION_MESSAGE.CONTENT, lowerInclusive, upperInclusive)

    /**
     * Fetch records that have <code>content IN (values)</code>
     */
    fun fetchByContent(vararg values: String): List<io.heapy.kotbot.database.tables.pojos.GptSessionMessage> = fetch(GptSessionMessage.GPT_SESSION_MESSAGE.CONTENT, *values)

    /**
     * Fetch records that have <code>created BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    fun fetchRangeOfCreated(lowerInclusive: LocalDateTime?, upperInclusive: LocalDateTime?): List<io.heapy.kotbot.database.tables.pojos.GptSessionMessage> = fetchRange(GptSessionMessage.GPT_SESSION_MESSAGE.CREATED, lowerInclusive, upperInclusive)

    /**
     * Fetch records that have <code>created IN (values)</code>
     */
    fun fetchByCreated(vararg values: LocalDateTime): List<io.heapy.kotbot.database.tables.pojos.GptSessionMessage> = fetch(GptSessionMessage.GPT_SESSION_MESSAGE.CREATED, *values)
}
