/*
 * This file is generated by jOOQ.
 */
package io.heapy.kotbot.database.tables.daos


import io.heapy.kotbot.database.enums.JobExecutionStatus
import io.heapy.kotbot.database.tables.JobExecution
import io.heapy.kotbot.database.tables.records.JobExecutionRecord

import java.time.LocalDateTime

import kotlin.collections.List

import org.jooq.Configuration
import org.jooq.impl.DAOImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class JobExecutionDao(configuration: Configuration?) : DAOImpl<JobExecutionRecord, io.heapy.kotbot.database.tables.pojos.JobExecution, Long>(JobExecution.JOB_EXECUTION, io.heapy.kotbot.database.tables.pojos.JobExecution::class.java, configuration) {

    /**
     * Create a new JobExecutionDao without any configuration
     */
    constructor(): this(null)

    override fun getId(o: io.heapy.kotbot.database.tables.pojos.JobExecution): Long? = o.id

    /**
     * Fetch records that have <code>id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    fun fetchRangeOfId(lowerInclusive: Long?, upperInclusive: Long?): List<io.heapy.kotbot.database.tables.pojos.JobExecution> = fetchRange(JobExecution.JOB_EXECUTION.ID, lowerInclusive, upperInclusive)

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    fun fetchById(vararg values: Long): List<io.heapy.kotbot.database.tables.pojos.JobExecution> = fetch(JobExecution.JOB_EXECUTION.ID, *values.toTypedArray())

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    fun fetchOneById(value: Long): io.heapy.kotbot.database.tables.pojos.JobExecution? = fetchOne(JobExecution.JOB_EXECUTION.ID, value)

    /**
     * Fetch records that have <code>job_name BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    fun fetchRangeOfJobName(lowerInclusive: String, upperInclusive: String): List<io.heapy.kotbot.database.tables.pojos.JobExecution> = fetchRange(JobExecution.JOB_EXECUTION.JOB_NAME, lowerInclusive, upperInclusive)

    /**
     * Fetch records that have <code>job_name IN (values)</code>
     */
    fun fetchByJobName(vararg values: String): List<io.heapy.kotbot.database.tables.pojos.JobExecution> = fetch(JobExecution.JOB_EXECUTION.JOB_NAME, *values)

    /**
     * Fetch records that have <code>started BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    fun fetchRangeOfStarted(lowerInclusive: LocalDateTime?, upperInclusive: LocalDateTime?): List<io.heapy.kotbot.database.tables.pojos.JobExecution> = fetchRange(JobExecution.JOB_EXECUTION.STARTED, lowerInclusive, upperInclusive)

    /**
     * Fetch records that have <code>started IN (values)</code>
     */
    fun fetchByStarted(vararg values: LocalDateTime): List<io.heapy.kotbot.database.tables.pojos.JobExecution> = fetch(JobExecution.JOB_EXECUTION.STARTED, *values)

    /**
     * Fetch records that have <code>finished BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    fun fetchRangeOfFinished(lowerInclusive: LocalDateTime?, upperInclusive: LocalDateTime?): List<io.heapy.kotbot.database.tables.pojos.JobExecution> = fetchRange(JobExecution.JOB_EXECUTION.FINISHED, lowerInclusive, upperInclusive)

    /**
     * Fetch records that have <code>finished IN (values)</code>
     */
    fun fetchByFinished(vararg values: LocalDateTime): List<io.heapy.kotbot.database.tables.pojos.JobExecution> = fetch(JobExecution.JOB_EXECUTION.FINISHED, *values)

    /**
     * Fetch records that have <code>status BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    fun fetchRangeOfStatus(lowerInclusive: JobExecutionStatus?, upperInclusive: JobExecutionStatus?): List<io.heapy.kotbot.database.tables.pojos.JobExecution> = fetchRange(JobExecution.JOB_EXECUTION.STATUS, lowerInclusive, upperInclusive)

    /**
     * Fetch records that have <code>status IN (values)</code>
     */
    fun fetchByStatus(vararg values: JobExecutionStatus): List<io.heapy.kotbot.database.tables.pojos.JobExecution> = fetch(JobExecution.JOB_EXECUTION.STATUS, *values)
}
