/*
 * This file is generated by jOOQ.
 */
package io.heapy.kotbot.database.tables.daos


import io.heapy.kotbot.database.enums.JoinSessionStatus
import io.heapy.kotbot.database.tables.JoinSession
import io.heapy.kotbot.database.tables.records.JoinSessionRecord

import java.time.LocalDateTime
import java.util.UUID

import kotlin.collections.List

import org.jooq.Configuration
import org.jooq.JSONB
import org.jooq.impl.DAOImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class JoinSessionDao(configuration: Configuration?) : DAOImpl<JoinSessionRecord, io.heapy.kotbot.database.tables.pojos.JoinSession, Long>(JoinSession.JOIN_SESSION, io.heapy.kotbot.database.tables.pojos.JoinSession::class.java, configuration) {

    /**
     * Create a new JoinSessionDao without any configuration
     */
    constructor(): this(null)

    override fun getId(o: io.heapy.kotbot.database.tables.pojos.JoinSession): Long? = o.id

    /**
     * Fetch records that have <code>id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    fun fetchRangeOfId(lowerInclusive: Long?, upperInclusive: Long?): List<io.heapy.kotbot.database.tables.pojos.JoinSession> = fetchRange(JoinSession.JOIN_SESSION.ID, lowerInclusive, upperInclusive)

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    fun fetchById(vararg values: Long): List<io.heapy.kotbot.database.tables.pojos.JoinSession> = fetch(JoinSession.JOIN_SESSION.ID, *values.toTypedArray())

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    fun fetchOneById(value: Long): io.heapy.kotbot.database.tables.pojos.JoinSession? = fetchOne(JoinSession.JOIN_SESSION.ID, value)

    /**
     * Fetch records that have <code>telegram_id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    fun fetchRangeOfTelegramId(lowerInclusive: Long, upperInclusive: Long): List<io.heapy.kotbot.database.tables.pojos.JoinSession> = fetchRange(JoinSession.JOIN_SESSION.TELEGRAM_ID, lowerInclusive, upperInclusive)

    /**
     * Fetch records that have <code>telegram_id IN (values)</code>
     */
    fun fetchByTelegramId(vararg values: Long): List<io.heapy.kotbot.database.tables.pojos.JoinSession> = fetch(JoinSession.JOIN_SESSION.TELEGRAM_ID, *values.toTypedArray())

    /**
     * Fetch records that have <code>chat_id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    fun fetchRangeOfChatId(lowerInclusive: Long, upperInclusive: Long): List<io.heapy.kotbot.database.tables.pojos.JoinSession> = fetchRange(JoinSession.JOIN_SESSION.CHAT_ID, lowerInclusive, upperInclusive)

    /**
     * Fetch records that have <code>chat_id IN (values)</code>
     */
    fun fetchByChatId(vararg values: Long): List<io.heapy.kotbot.database.tables.pojos.JoinSession> = fetch(JoinSession.JOIN_SESSION.CHAT_ID, *values.toTypedArray())

    /**
     * Fetch records that have <code>user_chat_id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    fun fetchRangeOfUserChatId(lowerInclusive: Long, upperInclusive: Long): List<io.heapy.kotbot.database.tables.pojos.JoinSession> = fetchRange(JoinSession.JOIN_SESSION.USER_CHAT_ID, lowerInclusive, upperInclusive)

    /**
     * Fetch records that have <code>user_chat_id IN (values)</code>
     */
    fun fetchByUserChatId(vararg values: Long): List<io.heapy.kotbot.database.tables.pojos.JoinSession> = fetch(JoinSession.JOIN_SESSION.USER_CHAT_ID, *values.toTypedArray())

    /**
     * Fetch records that have <code>status BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    fun fetchRangeOfStatus(lowerInclusive: JoinSessionStatus?, upperInclusive: JoinSessionStatus?): List<io.heapy.kotbot.database.tables.pojos.JoinSession> = fetchRange(JoinSession.JOIN_SESSION.STATUS, lowerInclusive, upperInclusive)

    /**
     * Fetch records that have <code>status IN (values)</code>
     */
    fun fetchByStatus(vararg values: JoinSessionStatus): List<io.heapy.kotbot.database.tables.pojos.JoinSession> = fetch(JoinSession.JOIN_SESSION.STATUS, *values)

    /**
     * Fetch records that have <code>max_attempts BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    fun fetchRangeOfMaxAttempts(lowerInclusive: Int, upperInclusive: Int): List<io.heapy.kotbot.database.tables.pojos.JoinSession> = fetchRange(JoinSession.JOIN_SESSION.MAX_ATTEMPTS, lowerInclusive, upperInclusive)

    /**
     * Fetch records that have <code>max_attempts IN (values)</code>
     */
    fun fetchByMaxAttempts(vararg values: Int): List<io.heapy.kotbot.database.tables.pojos.JoinSession> = fetch(JoinSession.JOIN_SESSION.MAX_ATTEMPTS, *values.toTypedArray())

    /**
     * Fetch records that have <code>attempts_used BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    fun fetchRangeOfAttemptsUsed(lowerInclusive: Int?, upperInclusive: Int?): List<io.heapy.kotbot.database.tables.pojos.JoinSession> = fetchRange(JoinSession.JOIN_SESSION.ATTEMPTS_USED, lowerInclusive, upperInclusive)

    /**
     * Fetch records that have <code>attempts_used IN (values)</code>
     */
    fun fetchByAttemptsUsed(vararg values: Int): List<io.heapy.kotbot.database.tables.pojos.JoinSession> = fetch(JoinSession.JOIN_SESSION.ATTEMPTS_USED, *values.toTypedArray())

    /**
     * Fetch records that have <code>expires_at BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    fun fetchRangeOfExpiresAt(lowerInclusive: LocalDateTime, upperInclusive: LocalDateTime): List<io.heapy.kotbot.database.tables.pojos.JoinSession> = fetchRange(JoinSession.JOIN_SESSION.EXPIRES_AT, lowerInclusive, upperInclusive)

    /**
     * Fetch records that have <code>expires_at IN (values)</code>
     */
    fun fetchByExpiresAt(vararg values: LocalDateTime): List<io.heapy.kotbot.database.tables.pojos.JoinSession> = fetch(JoinSession.JOIN_SESSION.EXPIRES_AT, *values)

    /**
     * Fetch records that have <code>created_at BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    fun fetchRangeOfCreatedAt(lowerInclusive: LocalDateTime?, upperInclusive: LocalDateTime?): List<io.heapy.kotbot.database.tables.pojos.JoinSession> = fetchRange(JoinSession.JOIN_SESSION.CREATED_AT, lowerInclusive, upperInclusive)

    /**
     * Fetch records that have <code>created_at IN (values)</code>
     */
    fun fetchByCreatedAt(vararg values: LocalDateTime): List<io.heapy.kotbot.database.tables.pojos.JoinSession> = fetch(JoinSession.JOIN_SESSION.CREATED_AT, *values)

    /**
     * Fetch records that have <code>finished_at BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    fun fetchRangeOfFinishedAt(lowerInclusive: LocalDateTime?, upperInclusive: LocalDateTime?): List<io.heapy.kotbot.database.tables.pojos.JoinSession> = fetchRange(JoinSession.JOIN_SESSION.FINISHED_AT, lowerInclusive, upperInclusive)

    /**
     * Fetch records that have <code>finished_at IN (values)</code>
     */
    fun fetchByFinishedAt(vararg values: LocalDateTime): List<io.heapy.kotbot.database.tables.pojos.JoinSession> = fetch(JoinSession.JOIN_SESSION.FINISHED_AT, *values)

    /**
     * Fetch records that have <code>challenge_id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    fun fetchRangeOfChallengeId(lowerInclusive: UUID?, upperInclusive: UUID?): List<io.heapy.kotbot.database.tables.pojos.JoinSession> = fetchRange(JoinSession.JOIN_SESSION.CHALLENGE_ID, lowerInclusive, upperInclusive)

    /**
     * Fetch records that have <code>challenge_id IN (values)</code>
     */
    fun fetchByChallengeId(vararg values: UUID): List<io.heapy.kotbot.database.tables.pojos.JoinSession> = fetch(JoinSession.JOIN_SESSION.CHALLENGE_ID, *values)

    /**
     * Fetch records that have <code>template_key BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    fun fetchRangeOfTemplateKey(lowerInclusive: String?, upperInclusive: String?): List<io.heapy.kotbot.database.tables.pojos.JoinSession> = fetchRange(JoinSession.JOIN_SESSION.TEMPLATE_KEY, lowerInclusive, upperInclusive)

    /**
     * Fetch records that have <code>template_key IN (values)</code>
     */
    fun fetchByTemplateKey(vararg values: String): List<io.heapy.kotbot.database.tables.pojos.JoinSession> = fetch(JoinSession.JOIN_SESSION.TEMPLATE_KEY, *values)

    /**
     * Fetch records that have <code>seed BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    fun fetchRangeOfSeed(lowerInclusive: Long?, upperInclusive: Long?): List<io.heapy.kotbot.database.tables.pojos.JoinSession> = fetchRange(JoinSession.JOIN_SESSION.SEED, lowerInclusive, upperInclusive)

    /**
     * Fetch records that have <code>seed IN (values)</code>
     */
    fun fetchBySeed(vararg values: Long): List<io.heapy.kotbot.database.tables.pojos.JoinSession> = fetch(JoinSession.JOIN_SESSION.SEED, *values.toTypedArray())

    /**
     * Fetch records that have <code>snippet BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    fun fetchRangeOfSnippet(lowerInclusive: String?, upperInclusive: String?): List<io.heapy.kotbot.database.tables.pojos.JoinSession> = fetchRange(JoinSession.JOIN_SESSION.SNIPPET, lowerInclusive, upperInclusive)

    /**
     * Fetch records that have <code>snippet IN (values)</code>
     */
    fun fetchBySnippet(vararg values: String): List<io.heapy.kotbot.database.tables.pojos.JoinSession> = fetch(JoinSession.JOIN_SESSION.SNIPPET, *values)

    /**
     * Fetch records that have <code>correct_answer BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    fun fetchRangeOfCorrectAnswer(lowerInclusive: String?, upperInclusive: String?): List<io.heapy.kotbot.database.tables.pojos.JoinSession> = fetchRange(JoinSession.JOIN_SESSION.CORRECT_ANSWER, lowerInclusive, upperInclusive)

    /**
     * Fetch records that have <code>correct_answer IN (values)</code>
     */
    fun fetchByCorrectAnswer(vararg values: String): List<io.heapy.kotbot.database.tables.pojos.JoinSession> = fetch(JoinSession.JOIN_SESSION.CORRECT_ANSWER, *values)

    /**
     * Fetch records that have <code>options BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    fun fetchRangeOfOptions(lowerInclusive: JSONB?, upperInclusive: JSONB?): List<io.heapy.kotbot.database.tables.pojos.JoinSession> = fetchRange(JoinSession.JOIN_SESSION.OPTIONS, lowerInclusive, upperInclusive)

    /**
     * Fetch records that have <code>options IN (values)</code>
     */
    fun fetchByOptions(vararg values: JSONB): List<io.heapy.kotbot.database.tables.pojos.JoinSession> = fetch(JoinSession.JOIN_SESSION.OPTIONS, *values)

    /**
     * Fetch records that have <code>challenge_sent_at BETWEEN lowerInclusive
     * AND upperInclusive</code>
     */
    fun fetchRangeOfChallengeSentAt(lowerInclusive: LocalDateTime?, upperInclusive: LocalDateTime?): List<io.heapy.kotbot.database.tables.pojos.JoinSession> = fetchRange(JoinSession.JOIN_SESSION.CHALLENGE_SENT_AT, lowerInclusive, upperInclusive)

    /**
     * Fetch records that have <code>challenge_sent_at IN (values)</code>
     */
    fun fetchByChallengeSentAt(vararg values: LocalDateTime): List<io.heapy.kotbot.database.tables.pojos.JoinSession> = fetch(JoinSession.JOIN_SESSION.CHALLENGE_SENT_AT, *values)

    /**
     * Fetch records that have <code>message_id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    fun fetchRangeOfMessageId(lowerInclusive: Int?, upperInclusive: Int?): List<io.heapy.kotbot.database.tables.pojos.JoinSession> = fetchRange(JoinSession.JOIN_SESSION.MESSAGE_ID, lowerInclusive, upperInclusive)

    /**
     * Fetch records that have <code>message_id IN (values)</code>
     */
    fun fetchByMessageId(vararg values: Int): List<io.heapy.kotbot.database.tables.pojos.JoinSession> = fetch(JoinSession.JOIN_SESSION.MESSAGE_ID, *values.toTypedArray())
}
