/*
 * This file is generated by jOOQ.
 */
package io.heapy.kotbot.database.tables.daos


import io.heapy.kotbot.database.enums.TelegramUserRole
import io.heapy.kotbot.database.enums.TelegramUserStatus
import io.heapy.kotbot.database.tables.TelegramUser
import io.heapy.kotbot.database.tables.records.TelegramUserRecord

import java.time.LocalDateTime

import kotlin.collections.List

import org.jooq.Configuration
import org.jooq.impl.DAOImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class TelegramUserDao(configuration: Configuration?) : DAOImpl<TelegramUserRecord, io.heapy.kotbot.database.tables.pojos.TelegramUser, Long>(TelegramUser.TELEGRAM_USER, io.heapy.kotbot.database.tables.pojos.TelegramUser::class.java, configuration) {

    /**
     * Create a new TelegramUserDao without any configuration
     */
    constructor(): this(null)

    override fun getId(o: io.heapy.kotbot.database.tables.pojos.TelegramUser): Long? = o.internalId

    /**
     * Fetch records that have <code>internal_id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    fun fetchRangeOfInternalId(lowerInclusive: Long?, upperInclusive: Long?): List<io.heapy.kotbot.database.tables.pojos.TelegramUser> = fetchRange(TelegramUser.TELEGRAM_USER.INTERNAL_ID, lowerInclusive, upperInclusive)

    /**
     * Fetch records that have <code>internal_id IN (values)</code>
     */
    fun fetchByInternalId(vararg values: Long): List<io.heapy.kotbot.database.tables.pojos.TelegramUser> = fetch(TelegramUser.TELEGRAM_USER.INTERNAL_ID, *values.toTypedArray())

    /**
     * Fetch a unique record that has <code>internal_id = value</code>
     */
    fun fetchOneByInternalId(value: Long): io.heapy.kotbot.database.tables.pojos.TelegramUser? = fetchOne(TelegramUser.TELEGRAM_USER.INTERNAL_ID, value)

    /**
     * Fetch records that have <code>telegram_id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    fun fetchRangeOfTelegramId(lowerInclusive: Long, upperInclusive: Long): List<io.heapy.kotbot.database.tables.pojos.TelegramUser> = fetchRange(TelegramUser.TELEGRAM_USER.TELEGRAM_ID, lowerInclusive, upperInclusive)

    /**
     * Fetch records that have <code>telegram_id IN (values)</code>
     */
    fun fetchByTelegramId(vararg values: Long): List<io.heapy.kotbot.database.tables.pojos.TelegramUser> = fetch(TelegramUser.TELEGRAM_USER.TELEGRAM_ID, *values.toTypedArray())

    /**
     * Fetch records that have <code>created BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    fun fetchRangeOfCreated(lowerInclusive: LocalDateTime?, upperInclusive: LocalDateTime?): List<io.heapy.kotbot.database.tables.pojos.TelegramUser> = fetchRange(TelegramUser.TELEGRAM_USER.CREATED, lowerInclusive, upperInclusive)

    /**
     * Fetch records that have <code>created IN (values)</code>
     */
    fun fetchByCreated(vararg values: LocalDateTime): List<io.heapy.kotbot.database.tables.pojos.TelegramUser> = fetch(TelegramUser.TELEGRAM_USER.CREATED, *values)

    /**
     * Fetch records that have <code>last_message BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    fun fetchRangeOfLastMessage(lowerInclusive: LocalDateTime?, upperInclusive: LocalDateTime?): List<io.heapy.kotbot.database.tables.pojos.TelegramUser> = fetchRange(TelegramUser.TELEGRAM_USER.LAST_MESSAGE, lowerInclusive, upperInclusive)

    /**
     * Fetch records that have <code>last_message IN (values)</code>
     */
    fun fetchByLastMessage(vararg values: LocalDateTime): List<io.heapy.kotbot.database.tables.pojos.TelegramUser> = fetch(TelegramUser.TELEGRAM_USER.LAST_MESSAGE, *values)

    /**
     * Fetch records that have <code>message_count BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    fun fetchRangeOfMessageCount(lowerInclusive: Int?, upperInclusive: Int?): List<io.heapy.kotbot.database.tables.pojos.TelegramUser> = fetchRange(TelegramUser.TELEGRAM_USER.MESSAGE_COUNT, lowerInclusive, upperInclusive)

    /**
     * Fetch records that have <code>message_count IN (values)</code>
     */
    fun fetchByMessageCount(vararg values: Int): List<io.heapy.kotbot.database.tables.pojos.TelegramUser> = fetch(TelegramUser.TELEGRAM_USER.MESSAGE_COUNT, *values.toTypedArray())

    /**
     * Fetch records that have <code>status BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    fun fetchRangeOfStatus(lowerInclusive: TelegramUserStatus?, upperInclusive: TelegramUserStatus?): List<io.heapy.kotbot.database.tables.pojos.TelegramUser> = fetchRange(TelegramUser.TELEGRAM_USER.STATUS, lowerInclusive, upperInclusive)

    /**
     * Fetch records that have <code>status IN (values)</code>
     */
    fun fetchByStatus(vararg values: TelegramUserStatus): List<io.heapy.kotbot.database.tables.pojos.TelegramUser> = fetch(TelegramUser.TELEGRAM_USER.STATUS, *values)

    /**
     * Fetch records that have <code>role BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    fun fetchRangeOfRole(lowerInclusive: TelegramUserRole?, upperInclusive: TelegramUserRole?): List<io.heapy.kotbot.database.tables.pojos.TelegramUser> = fetchRange(TelegramUser.TELEGRAM_USER.ROLE, lowerInclusive, upperInclusive)

    /**
     * Fetch records that have <code>role IN (values)</code>
     */
    fun fetchByRole(vararg values: TelegramUserRole): List<io.heapy.kotbot.database.tables.pojos.TelegramUser> = fetch(TelegramUser.TELEGRAM_USER.ROLE, *values)

    /**
     * Fetch records that have <code>badge BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    fun fetchRangeOfBadge(lowerInclusive: String?, upperInclusive: String?): List<io.heapy.kotbot.database.tables.pojos.TelegramUser> = fetchRange(TelegramUser.TELEGRAM_USER.BADGE, lowerInclusive, upperInclusive)

    /**
     * Fetch records that have <code>badge IN (values)</code>
     */
    fun fetchByBadge(vararg values: String): List<io.heapy.kotbot.database.tables.pojos.TelegramUser> = fetch(TelegramUser.TELEGRAM_USER.BADGE, *values)

    /**
     * Fetch records that have <code>version BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    fun fetchRangeOfVersion(lowerInclusive: Int?, upperInclusive: Int?): List<io.heapy.kotbot.database.tables.pojos.TelegramUser> = fetchRange(TelegramUser.TELEGRAM_USER.VERSION, lowerInclusive, upperInclusive)

    /**
     * Fetch records that have <code>version IN (values)</code>
     */
    fun fetchByVersion(vararg values: Int): List<io.heapy.kotbot.database.tables.pojos.TelegramUser> = fetch(TelegramUser.TELEGRAM_USER.VERSION, *values.toTypedArray())

    /**
     * Fetch records that have <code>display_name BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    fun fetchRangeOfDisplayName(lowerInclusive: String?, upperInclusive: String?): List<io.heapy.kotbot.database.tables.pojos.TelegramUser> = fetchRange(TelegramUser.TELEGRAM_USER.DISPLAY_NAME, lowerInclusive, upperInclusive)

    /**
     * Fetch records that have <code>display_name IN (values)</code>
     */
    fun fetchByDisplayName(vararg values: String): List<io.heapy.kotbot.database.tables.pojos.TelegramUser> = fetch(TelegramUser.TELEGRAM_USER.DISPLAY_NAME, *values)
}
