/*
 * This file is generated by jOOQ.
 */
package io.heapy.kotbot.database.tables.daos


import io.heapy.kotbot.database.tables.UpdateRaw
import io.heapy.kotbot.database.tables.records.UpdateRawRecord

import java.time.LocalDateTime

import kotlin.collections.List

import org.jooq.Configuration
import org.jooq.JSONB
import org.jooq.impl.DAOImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class UpdateRawDao(configuration: Configuration?) : DAOImpl<UpdateRawRecord, io.heapy.kotbot.database.tables.pojos.UpdateRaw, Long>(UpdateRaw.UPDATE_RAW, io.heapy.kotbot.database.tables.pojos.UpdateRaw::class.java, configuration) {

    /**
     * Create a new UpdateRawDao without any configuration
     */
    constructor(): this(null)

    override fun getId(o: io.heapy.kotbot.database.tables.pojos.UpdateRaw): Long = o.id

    /**
     * Fetch records that have <code>id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    fun fetchRangeOfId(lowerInclusive: Long, upperInclusive: Long): List<io.heapy.kotbot.database.tables.pojos.UpdateRaw> = fetchRange(UpdateRaw.UPDATE_RAW.ID, lowerInclusive, upperInclusive)

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    fun fetchById(vararg values: Long): List<io.heapy.kotbot.database.tables.pojos.UpdateRaw> = fetch(UpdateRaw.UPDATE_RAW.ID, *values.toTypedArray())

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    fun fetchOneById(value: Long): io.heapy.kotbot.database.tables.pojos.UpdateRaw? = fetchOne(UpdateRaw.UPDATE_RAW.ID, value)

    /**
     * Fetch records that have <code>created BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    fun fetchRangeOfCreated(lowerInclusive: LocalDateTime, upperInclusive: LocalDateTime): List<io.heapy.kotbot.database.tables.pojos.UpdateRaw> = fetchRange(UpdateRaw.UPDATE_RAW.CREATED, lowerInclusive, upperInclusive)

    /**
     * Fetch records that have <code>created IN (values)</code>
     */
    fun fetchByCreated(vararg values: LocalDateTime): List<io.heapy.kotbot.database.tables.pojos.UpdateRaw> = fetch(UpdateRaw.UPDATE_RAW.CREATED, *values)

    /**
     * Fetch records that have <code>update BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    fun fetchRangeOfUpdate(lowerInclusive: JSONB, upperInclusive: JSONB): List<io.heapy.kotbot.database.tables.pojos.UpdateRaw> = fetchRange(UpdateRaw.UPDATE_RAW.UPDATE, lowerInclusive, upperInclusive)

    /**
     * Fetch records that have <code>update IN (values)</code>
     */
    fun fetchByUpdate(vararg values: JSONB): List<io.heapy.kotbot.database.tables.pojos.UpdateRaw> = fetch(UpdateRaw.UPDATE_RAW.UPDATE, *values)
}
