/*
 * This file is generated by jOOQ.
 */
package io.heapy.kotbot.database.tables.daos


import io.heapy.kotbot.database.enums.VerificationSource
import io.heapy.kotbot.database.tables.VerifiedUser
import io.heapy.kotbot.database.tables.records.VerifiedUserRecord

import java.time.LocalDateTime

import kotlin.collections.List

import org.jooq.Configuration
import org.jooq.impl.DAOImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class VerifiedUserDao(configuration: Configuration?) : DAOImpl<VerifiedUserRecord, io.heapy.kotbot.database.tables.pojos.VerifiedUser, Long>(VerifiedUser.VERIFIED_USER, io.heapy.kotbot.database.tables.pojos.VerifiedUser::class.java, configuration) {

    /**
     * Create a new VerifiedUserDao without any configuration
     */
    constructor(): this(null)

    override fun getId(o: io.heapy.kotbot.database.tables.pojos.VerifiedUser): Long? = o.id

    /**
     * Fetch records that have <code>id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    fun fetchRangeOfId(lowerInclusive: Long?, upperInclusive: Long?): List<io.heapy.kotbot.database.tables.pojos.VerifiedUser> = fetchRange(VerifiedUser.VERIFIED_USER.ID, lowerInclusive, upperInclusive)

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    fun fetchById(vararg values: Long): List<io.heapy.kotbot.database.tables.pojos.VerifiedUser> = fetch(VerifiedUser.VERIFIED_USER.ID, *values.toTypedArray())

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    fun fetchOneById(value: Long): io.heapy.kotbot.database.tables.pojos.VerifiedUser? = fetchOne(VerifiedUser.VERIFIED_USER.ID, value)

    /**
     * Fetch records that have <code>telegram_id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    fun fetchRangeOfTelegramId(lowerInclusive: Long, upperInclusive: Long): List<io.heapy.kotbot.database.tables.pojos.VerifiedUser> = fetchRange(VerifiedUser.VERIFIED_USER.TELEGRAM_ID, lowerInclusive, upperInclusive)

    /**
     * Fetch records that have <code>telegram_id IN (values)</code>
     */
    fun fetchByTelegramId(vararg values: Long): List<io.heapy.kotbot.database.tables.pojos.VerifiedUser> = fetch(VerifiedUser.VERIFIED_USER.TELEGRAM_ID, *values.toTypedArray())

    /**
     * Fetch records that have <code>source BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    fun fetchRangeOfSource(lowerInclusive: VerificationSource, upperInclusive: VerificationSource): List<io.heapy.kotbot.database.tables.pojos.VerifiedUser> = fetchRange(VerifiedUser.VERIFIED_USER.SOURCE, lowerInclusive, upperInclusive)

    /**
     * Fetch records that have <code>source IN (values)</code>
     */
    fun fetchBySource(vararg values: VerificationSource): List<io.heapy.kotbot.database.tables.pojos.VerifiedUser> = fetch(VerifiedUser.VERIFIED_USER.SOURCE, *values)

    /**
     * Fetch records that have <code>verified_at BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    fun fetchRangeOfVerifiedAt(lowerInclusive: LocalDateTime?, upperInclusive: LocalDateTime?): List<io.heapy.kotbot.database.tables.pojos.VerifiedUser> = fetchRange(VerifiedUser.VERIFIED_USER.VERIFIED_AT, lowerInclusive, upperInclusive)

    /**
     * Fetch records that have <code>verified_at IN (values)</code>
     */
    fun fetchByVerifiedAt(vararg values: LocalDateTime): List<io.heapy.kotbot.database.tables.pojos.VerifiedUser> = fetch(VerifiedUser.VERIFIED_USER.VERIFIED_AT, *values)

    /**
     * Fetch records that have <code>session_id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    fun fetchRangeOfSessionId(lowerInclusive: Long?, upperInclusive: Long?): List<io.heapy.kotbot.database.tables.pojos.VerifiedUser> = fetchRange(VerifiedUser.VERIFIED_USER.SESSION_ID, lowerInclusive, upperInclusive)

    /**
     * Fetch records that have <code>session_id IN (values)</code>
     */
    fun fetchBySessionId(vararg values: Long): List<io.heapy.kotbot.database.tables.pojos.VerifiedUser> = fetch(VerifiedUser.VERIFIED_USER.SESSION_ID, *values.toTypedArray())
}
