/*
 * This file is generated by jOOQ.
 */
package io.heapy.kotbot.database.routines


import io.heapy.kotbot.database.Public

import java.util.UUID

import org.jooq.Parameter
import org.jooq.impl.AbstractRoutine
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class UuidNil : AbstractRoutine<UUID>("uuid_nil", Public.PUBLIC, DSL.comment(""), SQLDataType.UUID) {
    companion object {

        /**
         * The parameter <code>public.uuid_nil.RETURN_VALUE</code>.
         */
        val RETURN_VALUE: Parameter<UUID?> = Internal.createParameter("RETURN_VALUE", SQLDataType.UUID, false, false)
    }

    init {
        returnParameter = UuidNil.RETURN_VALUE
    }
}
