/*
 * This file is generated by jOOQ.
 */
package io.heapy.kotbot.database.tables.interfaces


import java.io.Serializable
import java.time.LocalDateTime
import java.util.UUID

import org.jooq.JSONB


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
interface ICallbackData : Serializable {
    val id: UUID?
    val `data`: JSONB
    val created: LocalDateTime
    val consumed: Boolean?
}
