/*
 * This file is generated by jOOQ.
 */
package io.heapy.kotbot.database.tables.interfaces


import java.io.Serializable
import java.time.LocalDateTime
import java.util.UUID


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
interface IChallengeAttempt : Serializable {
    val id: Long?
    val sessionId: Long
    val telegramId: Long
    val challengeId: UUID
    val templateKey: String
    val selectedAnswer: String
    val correctAnswer: String
    val isCorrect: Boolean
    val challengeSentAt: LocalDateTime
    val answeredAt: LocalDateTime?
    val latencyMs: Long
}
