/*
 * This file is generated by jOOQ.
 */
package io.heapy.kotbot.database.tables.interfaces


import io.heapy.kotbot.database.enums.FeedSource

import java.io.Serializable
import java.time.LocalDateTime


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
interface IFeedItem : Serializable {
    val id: Long?
    val source: FeedSource
    val itemKey: String
    val title: String
    val url: String
    val chatId: Long
    val messageId: Int
    val postedAt: LocalDateTime?
}
