/*
 * This file is generated by jOOQ.
 */
package io.heapy.kotbot.database.tables.interfaces


import io.heapy.kotbot.database.enums.ActionType
import io.heapy.kotbot.database.enums.MatchType

import java.io.Serializable


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
interface IGarbageMessages : Serializable {
    val id: Int?
    val text: String
    val type: String
    val match: MatchType
    val action: ActionType
}
