/*
 * This file is generated by jOOQ.
 */
package io.heapy.kotbot.database.tables.interfaces


import java.io.Serializable
import java.time.LocalDateTime


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
interface IGptSessionMessage : Serializable {
    val id: Long?
    val sessionId: Long
    val role: String
    val content: String
    val created: LocalDateTime?
}
