/*
 * This file is generated by jOOQ.
 */
package io.heapy.kotbot.database.tables.interfaces


import java.io.Serializable
import java.time.LocalDateTime


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
interface IGptSession : Serializable {
    val id: Long?
    val userId: Long
    val groupChatId: Long
    val waitMessageId: Int
    val previewChatId: Long?
    val previewMessageId: Int?
    val status: String?
    val created: LocalDateTime?
}
