/*
 * This file is generated by jOOQ.
 */
package io.heapy.kotbot.database.tables.interfaces


import io.heapy.kotbot.database.enums.JobExecutionStatus

import java.io.Serializable
import java.time.LocalDateTime


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
interface IJobExecution : Serializable {
    val id: Long?
    val jobName: String
    val started: LocalDateTime?
    val finished: LocalDateTime?
    val status: JobExecutionStatus?
}
