/*
 * This file is generated by jOOQ.
 */
package io.heapy.kotbot.database.tables.interfaces


import io.heapy.kotbot.database.enums.JoinSessionStatus

import java.io.Serializable
import java.time.LocalDateTime
import java.util.UUID

import org.jooq.JSONB


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
interface IJoinSession : Serializable {
    val id: Long?
    val telegramId: Long
    val chatId: Long
    val userChatId: Long
    val status: JoinSessionStatus?
    val maxAttempts: Int
    val attemptsUsed: Int?
    val expiresAt: LocalDateTime
    val createdAt: LocalDateTime?
    val finishedAt: LocalDateTime?
    val challengeId: UUID?
    val templateKey: String?
    val seed: Long?
    val snippet: String?
    val correctAnswer: String?
    val options: JSONB?
    val challengeSentAt: LocalDateTime?
    val messageId: Int?
}
