/*
 * This file is generated by jOOQ.
 */
package io.heapy.kotbot.database.tables.interfaces


import io.heapy.kotbot.database.enums.TelegramUserRole
import io.heapy.kotbot.database.enums.TelegramUserStatus

import java.io.Serializable
import java.time.LocalDateTime


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
interface ITelegramUser : Serializable {
    val internalId: Long?
    val telegramId: Long
    val created: LocalDateTime?
    val lastMessage: LocalDateTime?
    val messageCount: Int?
    val status: TelegramUserStatus?
    val role: TelegramUserRole?
    val badge: String?
    val version: Int?
}
