/*
 * This file is generated by jOOQ.
 */
package io.heapy.kotbot.database.tables.interfaces


import io.heapy.kotbot.database.enums.VerificationSource

import java.io.Serializable
import java.time.LocalDateTime


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
interface IVerifiedUser : Serializable {
    val id: Long?
    val telegramId: Long
    val source: VerificationSource
    val verifiedAt: LocalDateTime?
    val sessionId: Long?
}
