/*
 * This file is generated by jOOQ.
 */
package io.heapy.kotbot.database.tables.references


import io.heapy.kotbot.database.tables.GarbageMessages
import io.heapy.kotbot.database.tables.TelegramUser
import io.heapy.kotbot.database.tables.UpdateRaw



/**
 * The table <code>public.garbage_messages</code>.
 */
val GARBAGE_MESSAGES: GarbageMessages = GarbageMessages.GARBAGE_MESSAGES

/**
 * The table <code>public.telegram_user</code>.
 */
val TELEGRAM_USER: TelegramUser = TelegramUser.TELEGRAM_USER

/**
 * The table <code>public.update_raw</code>.
 */
val UPDATE_RAW: UpdateRaw = UpdateRaw.UPDATE_RAW
