/*
 * This file is generated by jOOQ.
 */
package io.heapy.kotbot.database.tables.references


import io.heapy.kotbot.database.tables.UpdateRaw



/**
 * The table <code>public.update_raw</code>.
 */
val UPDATE_RAW: UpdateRaw = UpdateRaw.UPDATE_RAW
