/*
 * This file is generated by jOOQ.
 */
package io.heapy.kotbot.database.tables


import io.heapy.kotbot.database.Public
import io.heapy.kotbot.database.keys.CALLBACK_DATA_PKEY
import io.heapy.kotbot.database.tables.records.CallbackDataRecord

import java.time.LocalDateTime
import java.util.UUID

import kotlin.collections.Collection

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.InverseForeignKey
import org.jooq.JSONB
import org.jooq.Name
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class CallbackData(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, CallbackDataRecord>?,
    parentPath: InverseForeignKey<out Record, CallbackDataRecord>?,
    aliased: Table<CallbackDataRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<CallbackDataRecord>(
    alias,
    Public.PUBLIC,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>public.callback_data</code>
         */
        val CALLBACK_DATA: CallbackData = CallbackData()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<CallbackDataRecord> = CallbackDataRecord::class.java

    /**
     * The column <code>public.callback_data.id</code>.
     */
    val ID: TableField<CallbackDataRecord, UUID?> = createField(DSL.name("id"), SQLDataType.UUID.nullable(false).defaultValue(DSL.field(DSL.raw("uuid_generate_v4()"), SQLDataType.UUID)), this, "")

    /**
     * The column <code>public.callback_data.data</code>.
     */
    val DATA: TableField<CallbackDataRecord, JSONB?> = createField(DSL.name("data"), SQLDataType.JSONB.nullable(false), this, "")

    /**
     * The column <code>public.callback_data.created</code>.
     */
    val CREATED: TableField<CallbackDataRecord, LocalDateTime?> = createField(DSL.name("created"), SQLDataType.LOCALDATETIME(6).nullable(false), this, "")

    /**
     * The column <code>public.callback_data.consumed</code>.
     */
    val CONSUMED: TableField<CallbackDataRecord, Boolean?> = createField(DSL.name("consumed"), SQLDataType.BOOLEAN.nullable(false).defaultValue(DSL.field(DSL.raw("false"), SQLDataType.BOOLEAN)), this, "")

    private constructor(alias: Name, aliased: Table<CallbackDataRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<CallbackDataRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<CallbackDataRecord>?, where: Condition?): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>public.callback_data</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>public.callback_data</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>public.callback_data</code> table reference
     */
    constructor(): this(DSL.name("callback_data"), null)
    override fun getSchema(): Schema? = if (aliased()) null else Public.PUBLIC
    override fun getPrimaryKey(): UniqueKey<CallbackDataRecord> = CALLBACK_DATA_PKEY
    override fun `as`(alias: String): CallbackData = CallbackData(DSL.name(alias), this)
    override fun `as`(alias: Name): CallbackData = CallbackData(alias, this)
    override fun `as`(alias: Table<*>): CallbackData = CallbackData(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): CallbackData = CallbackData(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): CallbackData = CallbackData(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): CallbackData = CallbackData(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): CallbackData = CallbackData(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): CallbackData = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): CallbackData = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): CallbackData = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): CallbackData = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): CallbackData = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): CallbackData = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): CallbackData = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): CallbackData = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): CallbackData = where(DSL.notExists(select))
}
