/*
 * This file is generated by jOOQ.
 */
package io.heapy.kotbot.database.tables


import io.heapy.kotbot.database.Public
import io.heapy.kotbot.database.indexes.CHALLENGE_ATTEMPT_SESSION_IDX
import io.heapy.kotbot.database.indexes.CHALLENGE_ATTEMPT_TELEGRAM_IDX
import io.heapy.kotbot.database.keys.CHALLENGE_ATTEMPT_PKEY
import io.heapy.kotbot.database.keys.CHALLENGE_ATTEMPT__CHALLENGE_ATTEMPT_SESSION_ID_FKEY
import io.heapy.kotbot.database.tables.JoinSession.JoinSessionPath
import io.heapy.kotbot.database.tables.records.ChallengeAttemptRecord

import java.time.LocalDateTime
import java.util.UUID

import kotlin.collections.Collection
import kotlin.collections.List

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Identity
import org.jooq.Index
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.Path
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class ChallengeAttempt(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, ChallengeAttemptRecord>?,
    parentPath: InverseForeignKey<out Record, ChallengeAttemptRecord>?,
    aliased: Table<ChallengeAttemptRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<ChallengeAttemptRecord>(
    alias,
    Public.PUBLIC,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>public.challenge_attempt</code>
         */
        val CHALLENGE_ATTEMPT: ChallengeAttempt = ChallengeAttempt()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<ChallengeAttemptRecord> = ChallengeAttemptRecord::class.java

    /**
     * The column <code>public.challenge_attempt.id</code>.
     */
    val ID: TableField<ChallengeAttemptRecord, Long?> = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "")

    /**
     * The column <code>public.challenge_attempt.session_id</code>.
     */
    val SESSION_ID: TableField<ChallengeAttemptRecord, Long?> = createField(DSL.name("session_id"), SQLDataType.BIGINT.nullable(false), this, "")

    /**
     * The column <code>public.challenge_attempt.telegram_id</code>.
     */
    val TELEGRAM_ID: TableField<ChallengeAttemptRecord, Long?> = createField(DSL.name("telegram_id"), SQLDataType.BIGINT.nullable(false), this, "")

    /**
     * The column <code>public.challenge_attempt.challenge_id</code>.
     */
    val CHALLENGE_ID: TableField<ChallengeAttemptRecord, UUID?> = createField(DSL.name("challenge_id"), SQLDataType.UUID.nullable(false), this, "")

    /**
     * The column <code>public.challenge_attempt.template_key</code>.
     */
    val TEMPLATE_KEY: TableField<ChallengeAttemptRecord, String?> = createField(DSL.name("template_key"), SQLDataType.VARCHAR(50).nullable(false), this, "")

    /**
     * The column <code>public.challenge_attempt.selected_answer</code>.
     */
    val SELECTED_ANSWER: TableField<ChallengeAttemptRecord, String?> = createField(DSL.name("selected_answer"), SQLDataType.CLOB.nullable(false), this, "")

    /**
     * The column <code>public.challenge_attempt.correct_answer</code>.
     */
    val CORRECT_ANSWER: TableField<ChallengeAttemptRecord, String?> = createField(DSL.name("correct_answer"), SQLDataType.CLOB.nullable(false), this, "")

    /**
     * The column <code>public.challenge_attempt.is_correct</code>.
     */
    val IS_CORRECT: TableField<ChallengeAttemptRecord, Boolean?> = createField(DSL.name("is_correct"), SQLDataType.BOOLEAN.nullable(false), this, "")

    /**
     * The column <code>public.challenge_attempt.challenge_sent_at</code>.
     */
    val CHALLENGE_SENT_AT: TableField<ChallengeAttemptRecord, LocalDateTime?> = createField(DSL.name("challenge_sent_at"), SQLDataType.LOCALDATETIME(6).nullable(false), this, "")

    /**
     * The column <code>public.challenge_attempt.answered_at</code>.
     */
    val ANSWERED_AT: TableField<ChallengeAttemptRecord, LocalDateTime?> = createField(DSL.name("answered_at"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "")

    /**
     * The column <code>public.challenge_attempt.latency_ms</code>.
     */
    val LATENCY_MS: TableField<ChallengeAttemptRecord, Long?> = createField(DSL.name("latency_ms"), SQLDataType.BIGINT.nullable(false), this, "")

    private constructor(alias: Name, aliased: Table<ChallengeAttemptRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<ChallengeAttemptRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<ChallengeAttemptRecord>?, where: Condition?): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>public.challenge_attempt</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>public.challenge_attempt</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>public.challenge_attempt</code> table reference
     */
    constructor(): this(DSL.name("challenge_attempt"), null)

    constructor(path: Table<out Record>, childPath: ForeignKey<out Record, ChallengeAttemptRecord>?, parentPath: InverseForeignKey<out Record, ChallengeAttemptRecord>?): this(Internal.createPathAlias(path, childPath, parentPath), path, childPath, parentPath, CHALLENGE_ATTEMPT, null, null)

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    open class ChallengeAttemptPath : ChallengeAttempt, Path<ChallengeAttemptRecord> {
        constructor(path: Table<out Record>, childPath: ForeignKey<out Record, ChallengeAttemptRecord>?, parentPath: InverseForeignKey<out Record, ChallengeAttemptRecord>?): super(path, childPath, parentPath)
        private constructor(alias: Name, aliased: Table<ChallengeAttemptRecord>): super(alias, aliased)
        override fun `as`(alias: String): ChallengeAttemptPath = ChallengeAttemptPath(DSL.name(alias), this)
        override fun `as`(alias: Name): ChallengeAttemptPath = ChallengeAttemptPath(alias, this)
        override fun `as`(alias: Table<*>): ChallengeAttemptPath = ChallengeAttemptPath(alias.qualifiedName, this)
    }
    override fun getSchema(): Schema? = if (aliased()) null else Public.PUBLIC
    override fun getIndexes(): List<Index> = listOf(CHALLENGE_ATTEMPT_SESSION_IDX, CHALLENGE_ATTEMPT_TELEGRAM_IDX)
    override fun getIdentity(): Identity<ChallengeAttemptRecord, Long?> = super.getIdentity() as Identity<ChallengeAttemptRecord, Long?>
    override fun getPrimaryKey(): UniqueKey<ChallengeAttemptRecord> = CHALLENGE_ATTEMPT_PKEY
    override fun getReferences(): List<ForeignKey<ChallengeAttemptRecord, *>> = listOf(CHALLENGE_ATTEMPT__CHALLENGE_ATTEMPT_SESSION_ID_FKEY)

    /**
     * Get the implicit join path to the <code>public.join_session</code> table.
     */
    fun joinSession(): JoinSessionPath = joinSession
    val joinSession: JoinSessionPath by lazy { JoinSessionPath(this, CHALLENGE_ATTEMPT__CHALLENGE_ATTEMPT_SESSION_ID_FKEY, null) }
    override fun `as`(alias: String): ChallengeAttempt = ChallengeAttempt(DSL.name(alias), this)
    override fun `as`(alias: Name): ChallengeAttempt = ChallengeAttempt(alias, this)
    override fun `as`(alias: Table<*>): ChallengeAttempt = ChallengeAttempt(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): ChallengeAttempt = ChallengeAttempt(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): ChallengeAttempt = ChallengeAttempt(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): ChallengeAttempt = ChallengeAttempt(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): ChallengeAttempt = ChallengeAttempt(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): ChallengeAttempt = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): ChallengeAttempt = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): ChallengeAttempt = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): ChallengeAttempt = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): ChallengeAttempt = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): ChallengeAttempt = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): ChallengeAttempt = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): ChallengeAttempt = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): ChallengeAttempt = where(DSL.notExists(select))
}
