/*
 * This file is generated by jOOQ.
 */
package io.heapy.kotbot.database.tables


import io.heapy.kotbot.database.Public
import io.heapy.kotbot.database.enums.FeedSource
import io.heapy.kotbot.database.indexes.FEED_ITEM_SOURCE_KEY_UINDEX
import io.heapy.kotbot.database.keys.FEED_ITEM_PKEY
import io.heapy.kotbot.database.tables.records.FeedItemRecord

import java.time.LocalDateTime

import kotlin.collections.Collection
import kotlin.collections.List

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Identity
import org.jooq.Index
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableLike
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class FeedItem(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, FeedItemRecord>?,
    parentPath: InverseForeignKey<out Record, FeedItemRecord>?,
    aliased: Table<FeedItemRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<FeedItemRecord>(
    alias,
    Public.PUBLIC,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>public.feed_item</code>
         */
        val FEED_ITEM: FeedItem = FeedItem()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<FeedItemRecord> = FeedItemRecord::class.java

    /**
     * The column <code>public.feed_item.id</code>.
     */
    val ID: TableField<FeedItemRecord, Long?> = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).generatedByDefaultAsIdentity(), this, "")

    /**
     * The column <code>public.feed_item.source</code>.
     */
    val SOURCE: TableField<FeedItemRecord, FeedSource?> = createField(DSL.name("source"), SQLDataType.VARCHAR.nullable(false).asEnumDataType(FeedSource::class.java), this, "")

    /**
     * The column <code>public.feed_item.item_key</code>.
     */
    val ITEM_KEY: TableField<FeedItemRecord, String?> = createField(DSL.name("item_key"), SQLDataType.CLOB.nullable(false), this, "")

    /**
     * The column <code>public.feed_item.title</code>.
     */
    val TITLE: TableField<FeedItemRecord, String?> = createField(DSL.name("title"), SQLDataType.CLOB.nullable(false), this, "")

    /**
     * The column <code>public.feed_item.url</code>.
     */
    val URL: TableField<FeedItemRecord, String?> = createField(DSL.name("url"), SQLDataType.CLOB.nullable(false), this, "")

    /**
     * The column <code>public.feed_item.chat_id</code>.
     */
    val CHAT_ID: TableField<FeedItemRecord, Long?> = createField(DSL.name("chat_id"), SQLDataType.BIGINT.nullable(false), this, "")

    /**
     * The column <code>public.feed_item.message_id</code>.
     */
    val MESSAGE_ID: TableField<FeedItemRecord, Int?> = createField(DSL.name("message_id"), SQLDataType.INTEGER.nullable(false), this, "")

    /**
     * The column <code>public.feed_item.posted_at</code>.
     */
    val POSTED_AT: TableField<FeedItemRecord, LocalDateTime?> = createField(DSL.name("posted_at"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "")

    private constructor(alias: Name, aliased: Table<FeedItemRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<FeedItemRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<FeedItemRecord>?, where: Condition?): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>public.feed_item</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>public.feed_item</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>public.feed_item</code> table reference
     */
    constructor(): this(DSL.name("feed_item"), null)
    override fun getSchema(): Schema? = if (aliased()) null else Public.PUBLIC
    override fun getIndexes(): List<Index> = listOf(FEED_ITEM_SOURCE_KEY_UINDEX)
    override fun getIdentity(): Identity<FeedItemRecord, Long?> = super.getIdentity() as Identity<FeedItemRecord, Long?>
    override fun getPrimaryKey(): UniqueKey<FeedItemRecord> = FEED_ITEM_PKEY
    override fun `as`(alias: String): FeedItem = FeedItem(DSL.name(alias), this)
    override fun `as`(alias: Name): FeedItem = FeedItem(alias, this)
    override fun `as`(alias: Table<*>): FeedItem = FeedItem(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): FeedItem = FeedItem(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): FeedItem = FeedItem(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): FeedItem = FeedItem(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): FeedItem = FeedItem(qualifiedName, if (aliased()) this else null, Internal.condition(this, condition))

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): FeedItem = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): FeedItem = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): FeedItem = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): FeedItem = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): FeedItem = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): FeedItem = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): FeedItem = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: TableLike<*>): FeedItem = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: TableLike<*>): FeedItem = where(DSL.notExists(select))
}
