/*
 * This file is generated by jOOQ.
 */
package io.heapy.kotbot.database.tables


import io.heapy.kotbot.database.Public
import io.heapy.kotbot.database.enums.ActionType
import io.heapy.kotbot.database.enums.MatchType
import io.heapy.kotbot.database.keys.GARBAGE_MESSAGES_PKEY
import io.heapy.kotbot.database.tables.records.GarbageMessagesRecord

import kotlin.collections.Collection

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Identity
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class GarbageMessages(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, GarbageMessagesRecord>?,
    parentPath: InverseForeignKey<out Record, GarbageMessagesRecord>?,
    aliased: Table<GarbageMessagesRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<GarbageMessagesRecord>(
    alias,
    Public.PUBLIC,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>public.garbage_messages</code>
         */
        val GARBAGE_MESSAGES: GarbageMessages = GarbageMessages()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<GarbageMessagesRecord> = GarbageMessagesRecord::class.java

    /**
     * The column <code>public.garbage_messages.id</code>.
     */
    val ID: TableField<GarbageMessagesRecord, Int?> = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "")

    /**
     * The column <code>public.garbage_messages.text</code>.
     */
    val TEXT: TableField<GarbageMessagesRecord, String?> = createField(DSL.name("text"), SQLDataType.VARCHAR(255).nullable(false), this, "")

    /**
     * The column <code>public.garbage_messages.type</code>.
     */
    val TYPE: TableField<GarbageMessagesRecord, String?> = createField(DSL.name("type"), SQLDataType.VARCHAR(255).nullable(false), this, "")

    /**
     * The column <code>public.garbage_messages.match</code>.
     */
    val MATCH: TableField<GarbageMessagesRecord, MatchType?> = createField(DSL.name("match"), SQLDataType.VARCHAR.nullable(false).asEnumDataType(MatchType::class.java), this, "")

    /**
     * The column <code>public.garbage_messages.action</code>.
     */
    val ACTION: TableField<GarbageMessagesRecord, ActionType?> = createField(DSL.name("action"), SQLDataType.VARCHAR.nullable(false).asEnumDataType(ActionType::class.java), this, "")

    private constructor(alias: Name, aliased: Table<GarbageMessagesRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<GarbageMessagesRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<GarbageMessagesRecord>?, where: Condition?): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>public.garbage_messages</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>public.garbage_messages</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>public.garbage_messages</code> table reference
     */
    constructor(): this(DSL.name("garbage_messages"), null)
    override fun getSchema(): Schema? = if (aliased()) null else Public.PUBLIC
    override fun getIdentity(): Identity<GarbageMessagesRecord, Int?> = super.getIdentity() as Identity<GarbageMessagesRecord, Int?>
    override fun getPrimaryKey(): UniqueKey<GarbageMessagesRecord> = GARBAGE_MESSAGES_PKEY
    override fun `as`(alias: String): GarbageMessages = GarbageMessages(DSL.name(alias), this)
    override fun `as`(alias: Name): GarbageMessages = GarbageMessages(alias, this)
    override fun `as`(alias: Table<*>): GarbageMessages = GarbageMessages(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): GarbageMessages = GarbageMessages(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): GarbageMessages = GarbageMessages(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): GarbageMessages = GarbageMessages(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): GarbageMessages = GarbageMessages(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): GarbageMessages = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): GarbageMessages = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): GarbageMessages = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): GarbageMessages = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): GarbageMessages = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): GarbageMessages = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): GarbageMessages = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): GarbageMessages = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): GarbageMessages = where(DSL.notExists(select))
}
