/*
 * This file is generated by jOOQ.
 */
package io.heapy.kotbot.database.tables


import io.heapy.kotbot.database.Public
import io.heapy.kotbot.database.keys.GPT_SESSION_MESSAGE_PKEY
import io.heapy.kotbot.database.keys.GPT_SESSION_MESSAGE__GPT_SESSION_MESSAGE_SESSION_ID_FKEY
import io.heapy.kotbot.database.tables.GptSession.GptSessionPath
import io.heapy.kotbot.database.tables.records.GptSessionMessageRecord

import java.time.LocalDateTime

import kotlin.collections.Collection
import kotlin.collections.List

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Identity
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.Path
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class GptSessionMessage(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, GptSessionMessageRecord>?,
    parentPath: InverseForeignKey<out Record, GptSessionMessageRecord>?,
    aliased: Table<GptSessionMessageRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<GptSessionMessageRecord>(
    alias,
    Public.PUBLIC,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>public.gpt_session_message</code>
         */
        val GPT_SESSION_MESSAGE: GptSessionMessage = GptSessionMessage()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<GptSessionMessageRecord> = GptSessionMessageRecord::class.java

    /**
     * The column <code>public.gpt_session_message.id</code>.
     */
    val ID: TableField<GptSessionMessageRecord, Long?> = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "")

    /**
     * The column <code>public.gpt_session_message.session_id</code>.
     */
    val SESSION_ID: TableField<GptSessionMessageRecord, Long?> = createField(DSL.name("session_id"), SQLDataType.BIGINT.nullable(false), this, "")

    /**
     * The column <code>public.gpt_session_message.role</code>.
     */
    val ROLE: TableField<GptSessionMessageRecord, String?> = createField(DSL.name("role"), SQLDataType.VARCHAR(20).nullable(false), this, "")

    /**
     * The column <code>public.gpt_session_message.content</code>.
     */
    val CONTENT: TableField<GptSessionMessageRecord, String?> = createField(DSL.name("content"), SQLDataType.CLOB.nullable(false), this, "")

    /**
     * The column <code>public.gpt_session_message.created</code>.
     */
    val CREATED: TableField<GptSessionMessageRecord, LocalDateTime?> = createField(DSL.name("created"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "")

    private constructor(alias: Name, aliased: Table<GptSessionMessageRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<GptSessionMessageRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<GptSessionMessageRecord>?, where: Condition?): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>public.gpt_session_message</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>public.gpt_session_message</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>public.gpt_session_message</code> table reference
     */
    constructor(): this(DSL.name("gpt_session_message"), null)

    constructor(path: Table<out Record>, childPath: ForeignKey<out Record, GptSessionMessageRecord>?, parentPath: InverseForeignKey<out Record, GptSessionMessageRecord>?): this(Internal.createPathAlias(path, childPath, parentPath), path, childPath, parentPath, GPT_SESSION_MESSAGE, null, null)

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    open class GptSessionMessagePath : GptSessionMessage, Path<GptSessionMessageRecord> {
        constructor(path: Table<out Record>, childPath: ForeignKey<out Record, GptSessionMessageRecord>?, parentPath: InverseForeignKey<out Record, GptSessionMessageRecord>?): super(path, childPath, parentPath)
        private constructor(alias: Name, aliased: Table<GptSessionMessageRecord>): super(alias, aliased)
        override fun `as`(alias: String): GptSessionMessagePath = GptSessionMessagePath(DSL.name(alias), this)
        override fun `as`(alias: Name): GptSessionMessagePath = GptSessionMessagePath(alias, this)
        override fun `as`(alias: Table<*>): GptSessionMessagePath = GptSessionMessagePath(alias.qualifiedName, this)
    }
    override fun getSchema(): Schema? = if (aliased()) null else Public.PUBLIC
    override fun getIdentity(): Identity<GptSessionMessageRecord, Long?> = super.getIdentity() as Identity<GptSessionMessageRecord, Long?>
    override fun getPrimaryKey(): UniqueKey<GptSessionMessageRecord> = GPT_SESSION_MESSAGE_PKEY
    override fun getReferences(): List<ForeignKey<GptSessionMessageRecord, *>> = listOf(GPT_SESSION_MESSAGE__GPT_SESSION_MESSAGE_SESSION_ID_FKEY)

    /**
     * Get the implicit join path to the <code>public.gpt_session</code> table.
     */
    fun gptSession(): GptSessionPath = gptSession
    val gptSession: GptSessionPath by lazy { GptSessionPath(this, GPT_SESSION_MESSAGE__GPT_SESSION_MESSAGE_SESSION_ID_FKEY, null) }
    override fun `as`(alias: String): GptSessionMessage = GptSessionMessage(DSL.name(alias), this)
    override fun `as`(alias: Name): GptSessionMessage = GptSessionMessage(alias, this)
    override fun `as`(alias: Table<*>): GptSessionMessage = GptSessionMessage(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): GptSessionMessage = GptSessionMessage(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): GptSessionMessage = GptSessionMessage(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): GptSessionMessage = GptSessionMessage(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): GptSessionMessage = GptSessionMessage(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): GptSessionMessage = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): GptSessionMessage = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): GptSessionMessage = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): GptSessionMessage = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): GptSessionMessage = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): GptSessionMessage = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): GptSessionMessage = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): GptSessionMessage = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): GptSessionMessage = where(DSL.notExists(select))
}
