/*
 * This file is generated by jOOQ.
 */
package io.heapy.kotbot.database.tables


import io.heapy.kotbot.database.Public
import io.heapy.kotbot.database.indexes.GPT_SESSION_PREVIEW_UINDEX
import io.heapy.kotbot.database.keys.GPT_SESSION_MESSAGE__GPT_SESSION_MESSAGE_SESSION_ID_FKEY
import io.heapy.kotbot.database.keys.GPT_SESSION_PKEY
import io.heapy.kotbot.database.tables.GptSessionMessage.GptSessionMessagePath
import io.heapy.kotbot.database.tables.records.GptSessionRecord

import java.time.LocalDateTime

import kotlin.collections.Collection
import kotlin.collections.List

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Identity
import org.jooq.Index
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.Path
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class GptSession(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, GptSessionRecord>?,
    parentPath: InverseForeignKey<out Record, GptSessionRecord>?,
    aliased: Table<GptSessionRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<GptSessionRecord>(
    alias,
    Public.PUBLIC,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>public.gpt_session</code>
         */
        val GPT_SESSION: GptSession = GptSession()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<GptSessionRecord> = GptSessionRecord::class.java

    /**
     * The column <code>public.gpt_session.id</code>.
     */
    val ID: TableField<GptSessionRecord, Long?> = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "")

    /**
     * The column <code>public.gpt_session.user_id</code>.
     */
    val USER_ID: TableField<GptSessionRecord, Long?> = createField(DSL.name("user_id"), SQLDataType.BIGINT.nullable(false), this, "")

    /**
     * The column <code>public.gpt_session.group_chat_id</code>.
     */
    val GROUP_CHAT_ID: TableField<GptSessionRecord, Long?> = createField(DSL.name("group_chat_id"), SQLDataType.BIGINT.nullable(false), this, "")

    /**
     * The column <code>public.gpt_session.wait_message_id</code>.
     */
    val WAIT_MESSAGE_ID: TableField<GptSessionRecord, Int?> = createField(DSL.name("wait_message_id"), SQLDataType.INTEGER.nullable(false), this, "")

    /**
     * The column <code>public.gpt_session.preview_chat_id</code>.
     */
    val PREVIEW_CHAT_ID: TableField<GptSessionRecord, Long?> = createField(DSL.name("preview_chat_id"), SQLDataType.BIGINT, this, "")

    /**
     * The column <code>public.gpt_session.preview_message_id</code>.
     */
    val PREVIEW_MESSAGE_ID: TableField<GptSessionRecord, Int?> = createField(DSL.name("preview_message_id"), SQLDataType.INTEGER, this, "")

    /**
     * The column <code>public.gpt_session.status</code>.
     */
    val STATUS: TableField<GptSessionRecord, String?> = createField(DSL.name("status"), SQLDataType.VARCHAR(20).nullable(false).defaultValue(DSL.field(DSL.raw("'ACTIVE'::character varying"), SQLDataType.VARCHAR)), this, "")

    /**
     * The column <code>public.gpt_session.created</code>.
     */
    val CREATED: TableField<GptSessionRecord, LocalDateTime?> = createField(DSL.name("created"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "")

    private constructor(alias: Name, aliased: Table<GptSessionRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<GptSessionRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<GptSessionRecord>?, where: Condition?): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>public.gpt_session</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>public.gpt_session</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>public.gpt_session</code> table reference
     */
    constructor(): this(DSL.name("gpt_session"), null)

    constructor(path: Table<out Record>, childPath: ForeignKey<out Record, GptSessionRecord>?, parentPath: InverseForeignKey<out Record, GptSessionRecord>?): this(Internal.createPathAlias(path, childPath, parentPath), path, childPath, parentPath, GPT_SESSION, null, null)

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    open class GptSessionPath : GptSession, Path<GptSessionRecord> {
        constructor(path: Table<out Record>, childPath: ForeignKey<out Record, GptSessionRecord>?, parentPath: InverseForeignKey<out Record, GptSessionRecord>?): super(path, childPath, parentPath)
        private constructor(alias: Name, aliased: Table<GptSessionRecord>): super(alias, aliased)
        override fun `as`(alias: String): GptSessionPath = GptSessionPath(DSL.name(alias), this)
        override fun `as`(alias: Name): GptSessionPath = GptSessionPath(alias, this)
        override fun `as`(alias: Table<*>): GptSessionPath = GptSessionPath(alias.qualifiedName, this)
    }
    override fun getSchema(): Schema? = if (aliased()) null else Public.PUBLIC
    override fun getIndexes(): List<Index> = listOf(GPT_SESSION_PREVIEW_UINDEX)
    override fun getIdentity(): Identity<GptSessionRecord, Long?> = super.getIdentity() as Identity<GptSessionRecord, Long?>
    override fun getPrimaryKey(): UniqueKey<GptSessionRecord> = GPT_SESSION_PKEY

    private lateinit var _gptSessionMessage: GptSessionMessagePath

    /**
     * Get the implicit to-many join path to the
     * <code>public.gpt_session_message</code> table
     */
    fun gptSessionMessage(): GptSessionMessagePath {
        if (!this::_gptSessionMessage.isInitialized)
            _gptSessionMessage = GptSessionMessagePath(this, null, GPT_SESSION_MESSAGE__GPT_SESSION_MESSAGE_SESSION_ID_FKEY.inverseKey)

        return _gptSessionMessage;
    }

    val gptSessionMessage: GptSessionMessagePath
        get(): GptSessionMessagePath = gptSessionMessage()
    override fun `as`(alias: String): GptSession = GptSession(DSL.name(alias), this)
    override fun `as`(alias: Name): GptSession = GptSession(alias, this)
    override fun `as`(alias: Table<*>): GptSession = GptSession(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): GptSession = GptSession(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): GptSession = GptSession(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): GptSession = GptSession(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): GptSession = GptSession(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): GptSession = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): GptSession = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): GptSession = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): GptSession = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): GptSession = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): GptSession = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): GptSession = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): GptSession = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): GptSession = where(DSL.notExists(select))
}
