/*
 * This file is generated by jOOQ.
 */
package io.heapy.kotbot.database.tables


import io.heapy.kotbot.database.Public
import io.heapy.kotbot.database.enums.JobExecutionStatus
import io.heapy.kotbot.database.indexes.JOB_EXECUTION_NAME_IDX
import io.heapy.kotbot.database.keys.JOB_EXECUTION_PKEY
import io.heapy.kotbot.database.tables.records.JobExecutionRecord

import java.time.LocalDateTime

import kotlin.collections.Collection
import kotlin.collections.List

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Identity
import org.jooq.Index
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class JobExecution(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, JobExecutionRecord>?,
    parentPath: InverseForeignKey<out Record, JobExecutionRecord>?,
    aliased: Table<JobExecutionRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<JobExecutionRecord>(
    alias,
    Public.PUBLIC,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>public.job_execution</code>
         */
        val JOB_EXECUTION: JobExecution = JobExecution()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<JobExecutionRecord> = JobExecutionRecord::class.java

    /**
     * The column <code>public.job_execution.id</code>.
     */
    val ID: TableField<JobExecutionRecord, Long?> = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "")

    /**
     * The column <code>public.job_execution.job_name</code>.
     */
    val JOB_NAME: TableField<JobExecutionRecord, String?> = createField(DSL.name("job_name"), SQLDataType.VARCHAR(100).nullable(false), this, "")

    /**
     * The column <code>public.job_execution.started</code>.
     */
    val STARTED: TableField<JobExecutionRecord, LocalDateTime?> = createField(DSL.name("started"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "")

    /**
     * The column <code>public.job_execution.finished</code>.
     */
    val FINISHED: TableField<JobExecutionRecord, LocalDateTime?> = createField(DSL.name("finished"), SQLDataType.LOCALDATETIME(6), this, "")

    /**
     * The column <code>public.job_execution.status</code>.
     */
    val STATUS: TableField<JobExecutionRecord, JobExecutionStatus?> = createField(DSL.name("status"), SQLDataType.VARCHAR.nullable(false).defaultValue(DSL.field(DSL.raw("'RUNNING'::job_execution_status"), SQLDataType.VARCHAR)).asEnumDataType(JobExecutionStatus::class.java), this, "")

    private constructor(alias: Name, aliased: Table<JobExecutionRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<JobExecutionRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<JobExecutionRecord>?, where: Condition?): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>public.job_execution</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>public.job_execution</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>public.job_execution</code> table reference
     */
    constructor(): this(DSL.name("job_execution"), null)
    override fun getSchema(): Schema? = if (aliased()) null else Public.PUBLIC
    override fun getIndexes(): List<Index> = listOf(JOB_EXECUTION_NAME_IDX)
    override fun getIdentity(): Identity<JobExecutionRecord, Long?> = super.getIdentity() as Identity<JobExecutionRecord, Long?>
    override fun getPrimaryKey(): UniqueKey<JobExecutionRecord> = JOB_EXECUTION_PKEY
    override fun `as`(alias: String): JobExecution = JobExecution(DSL.name(alias), this)
    override fun `as`(alias: Name): JobExecution = JobExecution(alias, this)
    override fun `as`(alias: Table<*>): JobExecution = JobExecution(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): JobExecution = JobExecution(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): JobExecution = JobExecution(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): JobExecution = JobExecution(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): JobExecution = JobExecution(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): JobExecution = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): JobExecution = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): JobExecution = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): JobExecution = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): JobExecution = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): JobExecution = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): JobExecution = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): JobExecution = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): JobExecution = where(DSL.notExists(select))
}
