/*
 * This file is generated by jOOQ.
 */
package io.heapy.kotbot.database.tables


import io.heapy.kotbot.database.Public
import io.heapy.kotbot.database.enums.JoinSessionStatus
import io.heapy.kotbot.database.indexes.JOIN_SESSION_ACTIVE_IDX
import io.heapy.kotbot.database.indexes.JOIN_SESSION_ACTIVE_USER_CHAT_UINDEX
import io.heapy.kotbot.database.keys.CHALLENGE_ATTEMPT__CHALLENGE_ATTEMPT_SESSION_ID_FKEY
import io.heapy.kotbot.database.keys.JOIN_SESSION_PKEY
import io.heapy.kotbot.database.tables.ChallengeAttempt.ChallengeAttemptPath
import io.heapy.kotbot.database.tables.records.JoinSessionRecord

import java.time.LocalDateTime
import java.util.UUID

import kotlin.collections.Collection
import kotlin.collections.List

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Identity
import org.jooq.Index
import org.jooq.InverseForeignKey
import org.jooq.JSONB
import org.jooq.Name
import org.jooq.Path
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class JoinSession(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, JoinSessionRecord>?,
    parentPath: InverseForeignKey<out Record, JoinSessionRecord>?,
    aliased: Table<JoinSessionRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<JoinSessionRecord>(
    alias,
    Public.PUBLIC,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>public.join_session</code>
         */
        val JOIN_SESSION: JoinSession = JoinSession()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<JoinSessionRecord> = JoinSessionRecord::class.java

    /**
     * The column <code>public.join_session.id</code>.
     */
    val ID: TableField<JoinSessionRecord, Long?> = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "")

    /**
     * The column <code>public.join_session.telegram_id</code>.
     */
    val TELEGRAM_ID: TableField<JoinSessionRecord, Long?> = createField(DSL.name("telegram_id"), SQLDataType.BIGINT.nullable(false), this, "")

    /**
     * The column <code>public.join_session.chat_id</code>.
     */
    val CHAT_ID: TableField<JoinSessionRecord, Long?> = createField(DSL.name("chat_id"), SQLDataType.BIGINT.nullable(false), this, "")

    /**
     * The column <code>public.join_session.user_chat_id</code>.
     */
    val USER_CHAT_ID: TableField<JoinSessionRecord, Long?> = createField(DSL.name("user_chat_id"), SQLDataType.BIGINT.nullable(false), this, "")

    /**
     * The column <code>public.join_session.status</code>.
     */
    val STATUS: TableField<JoinSessionRecord, JoinSessionStatus?> = createField(DSL.name("status"), SQLDataType.VARCHAR.nullable(false).defaultValue(DSL.field(DSL.raw("'ACTIVE'::join_session_status"), SQLDataType.VARCHAR)).asEnumDataType(JoinSessionStatus::class.java), this, "")

    /**
     * The column <code>public.join_session.max_attempts</code>.
     */
    val MAX_ATTEMPTS: TableField<JoinSessionRecord, Int?> = createField(DSL.name("max_attempts"), SQLDataType.INTEGER.nullable(false), this, "")

    /**
     * The column <code>public.join_session.attempts_used</code>.
     */
    val ATTEMPTS_USED: TableField<JoinSessionRecord, Int?> = createField(DSL.name("attempts_used"), SQLDataType.INTEGER.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.INTEGER)), this, "")

    /**
     * The column <code>public.join_session.expires_at</code>.
     */
    val EXPIRES_AT: TableField<JoinSessionRecord, LocalDateTime?> = createField(DSL.name("expires_at"), SQLDataType.LOCALDATETIME(6).nullable(false), this, "")

    /**
     * The column <code>public.join_session.created_at</code>.
     */
    val CREATED_AT: TableField<JoinSessionRecord, LocalDateTime?> = createField(DSL.name("created_at"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "")

    /**
     * The column <code>public.join_session.finished_at</code>.
     */
    val FINISHED_AT: TableField<JoinSessionRecord, LocalDateTime?> = createField(DSL.name("finished_at"), SQLDataType.LOCALDATETIME(6), this, "")

    /**
     * The column <code>public.join_session.challenge_id</code>.
     */
    val CHALLENGE_ID: TableField<JoinSessionRecord, UUID?> = createField(DSL.name("challenge_id"), SQLDataType.UUID, this, "")

    /**
     * The column <code>public.join_session.template_key</code>.
     */
    val TEMPLATE_KEY: TableField<JoinSessionRecord, String?> = createField(DSL.name("template_key"), SQLDataType.VARCHAR(50), this, "")

    /**
     * The column <code>public.join_session.seed</code>.
     */
    val SEED: TableField<JoinSessionRecord, Long?> = createField(DSL.name("seed"), SQLDataType.BIGINT, this, "")

    /**
     * The column <code>public.join_session.snippet</code>.
     */
    val SNIPPET: TableField<JoinSessionRecord, String?> = createField(DSL.name("snippet"), SQLDataType.CLOB, this, "")

    /**
     * The column <code>public.join_session.correct_answer</code>.
     */
    val CORRECT_ANSWER: TableField<JoinSessionRecord, String?> = createField(DSL.name("correct_answer"), SQLDataType.CLOB, this, "")

    /**
     * The column <code>public.join_session.options</code>.
     */
    val OPTIONS: TableField<JoinSessionRecord, JSONB?> = createField(DSL.name("options"), SQLDataType.JSONB, this, "")

    /**
     * The column <code>public.join_session.challenge_sent_at</code>.
     */
    val CHALLENGE_SENT_AT: TableField<JoinSessionRecord, LocalDateTime?> = createField(DSL.name("challenge_sent_at"), SQLDataType.LOCALDATETIME(6), this, "")

    /**
     * The column <code>public.join_session.message_id</code>.
     */
    val MESSAGE_ID: TableField<JoinSessionRecord, Int?> = createField(DSL.name("message_id"), SQLDataType.INTEGER, this, "")

    private constructor(alias: Name, aliased: Table<JoinSessionRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<JoinSessionRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<JoinSessionRecord>?, where: Condition?): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>public.join_session</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>public.join_session</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>public.join_session</code> table reference
     */
    constructor(): this(DSL.name("join_session"), null)

    constructor(path: Table<out Record>, childPath: ForeignKey<out Record, JoinSessionRecord>?, parentPath: InverseForeignKey<out Record, JoinSessionRecord>?): this(Internal.createPathAlias(path, childPath, parentPath), path, childPath, parentPath, JOIN_SESSION, null, null)

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    open class JoinSessionPath : JoinSession, Path<JoinSessionRecord> {
        constructor(path: Table<out Record>, childPath: ForeignKey<out Record, JoinSessionRecord>?, parentPath: InverseForeignKey<out Record, JoinSessionRecord>?): super(path, childPath, parentPath)
        private constructor(alias: Name, aliased: Table<JoinSessionRecord>): super(alias, aliased)
        override fun `as`(alias: String): JoinSessionPath = JoinSessionPath(DSL.name(alias), this)
        override fun `as`(alias: Name): JoinSessionPath = JoinSessionPath(alias, this)
        override fun `as`(alias: Table<*>): JoinSessionPath = JoinSessionPath(alias.qualifiedName, this)
    }
    override fun getSchema(): Schema? = if (aliased()) null else Public.PUBLIC
    override fun getIndexes(): List<Index> = listOf(JOIN_SESSION_ACTIVE_IDX, JOIN_SESSION_ACTIVE_USER_CHAT_UINDEX)
    override fun getIdentity(): Identity<JoinSessionRecord, Long?> = super.getIdentity() as Identity<JoinSessionRecord, Long?>
    override fun getPrimaryKey(): UniqueKey<JoinSessionRecord> = JOIN_SESSION_PKEY

    private lateinit var _challengeAttempt: ChallengeAttemptPath

    /**
     * Get the implicit to-many join path to the
     * <code>public.challenge_attempt</code> table
     */
    fun challengeAttempt(): ChallengeAttemptPath {
        if (!this::_challengeAttempt.isInitialized)
            _challengeAttempt = ChallengeAttemptPath(this, null, CHALLENGE_ATTEMPT__CHALLENGE_ATTEMPT_SESSION_ID_FKEY.inverseKey)

        return _challengeAttempt;
    }

    val challengeAttempt: ChallengeAttemptPath
        get(): ChallengeAttemptPath = challengeAttempt()
    override fun `as`(alias: String): JoinSession = JoinSession(DSL.name(alias), this)
    override fun `as`(alias: Name): JoinSession = JoinSession(alias, this)
    override fun `as`(alias: Table<*>): JoinSession = JoinSession(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): JoinSession = JoinSession(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): JoinSession = JoinSession(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): JoinSession = JoinSession(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): JoinSession = JoinSession(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): JoinSession = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): JoinSession = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): JoinSession = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): JoinSession = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): JoinSession = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): JoinSession = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): JoinSession = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): JoinSession = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): JoinSession = where(DSL.notExists(select))
}
