/*
 * This file is generated by jOOQ.
 */
package io.heapy.kotbot.database.tables


import io.heapy.kotbot.database.Public
import io.heapy.kotbot.database.enums.TelegramUserRole
import io.heapy.kotbot.database.enums.TelegramUserStatus
import io.heapy.kotbot.database.keys.TELEGRAM_USER_PK
import io.heapy.kotbot.database.tables.records.TelegramUserRecord

import java.time.LocalDateTime

import kotlin.collections.Collection

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Identity
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class TelegramUser(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, TelegramUserRecord>?,
    parentPath: InverseForeignKey<out Record, TelegramUserRecord>?,
    aliased: Table<TelegramUserRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<TelegramUserRecord>(
    alias,
    Public.PUBLIC,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>public.telegram_user</code>
         */
        val TELEGRAM_USER: TelegramUser = TelegramUser()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<TelegramUserRecord> = TelegramUserRecord::class.java

    /**
     * The column <code>public.telegram_user.internal_id</code>.
     */
    val INTERNAL_ID: TableField<TelegramUserRecord, Long?> = createField(DSL.name("internal_id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "")

    /**
     * The column <code>public.telegram_user.telegram_id</code>.
     */
    val TELEGRAM_ID: TableField<TelegramUserRecord, Long?> = createField(DSL.name("telegram_id"), SQLDataType.BIGINT.nullable(false), this, "")

    /**
     * The column <code>public.telegram_user.created</code>.
     */
    val CREATED: TableField<TelegramUserRecord, LocalDateTime?> = createField(DSL.name("created"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "")

    /**
     * The column <code>public.telegram_user.last_message</code>.
     */
    val LAST_MESSAGE: TableField<TelegramUserRecord, LocalDateTime?> = createField(DSL.name("last_message"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "")

    /**
     * The column <code>public.telegram_user.message_count</code>.
     */
    val MESSAGE_COUNT: TableField<TelegramUserRecord, Int?> = createField(DSL.name("message_count"), SQLDataType.INTEGER.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.INTEGER)), this, "")

    /**
     * The column <code>public.telegram_user.status</code>.
     */
    val STATUS: TableField<TelegramUserRecord, TelegramUserStatus?> = createField(DSL.name("status"), SQLDataType.VARCHAR.nullable(false).defaultValue(DSL.field(DSL.raw("'UNAPPROVED'::telegram_user_status"), SQLDataType.VARCHAR)).asEnumDataType(TelegramUserStatus::class.java), this, "")

    /**
     * The column <code>public.telegram_user.role</code>.
     */
    val ROLE: TableField<TelegramUserRecord, TelegramUserRole?> = createField(DSL.name("role"), SQLDataType.VARCHAR.nullable(false).defaultValue(DSL.field(DSL.raw("'USER'::telegram_user_role"), SQLDataType.VARCHAR)).asEnumDataType(TelegramUserRole::class.java), this, "")

    /**
     * The column <code>public.telegram_user.badge</code>.
     */
    val BADGE: TableField<TelegramUserRecord, String?> = createField(DSL.name("badge"), SQLDataType.VARCHAR(255), this, "")

    /**
     * The column <code>public.telegram_user.version</code>.
     */
    val VERSION: TableField<TelegramUserRecord, Int?> = createField(DSL.name("version"), SQLDataType.INTEGER.nullable(false).defaultValue(DSL.field(DSL.raw("0"), SQLDataType.INTEGER)), this, "")

    private constructor(alias: Name, aliased: Table<TelegramUserRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<TelegramUserRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<TelegramUserRecord>?, where: Condition?): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>public.telegram_user</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>public.telegram_user</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>public.telegram_user</code> table reference
     */
    constructor(): this(DSL.name("telegram_user"), null)
    override fun getSchema(): Schema? = if (aliased()) null else Public.PUBLIC
    override fun getIdentity(): Identity<TelegramUserRecord, Long?> = super.getIdentity() as Identity<TelegramUserRecord, Long?>
    override fun getPrimaryKey(): UniqueKey<TelegramUserRecord> = TELEGRAM_USER_PK
    override fun `as`(alias: String): TelegramUser = TelegramUser(DSL.name(alias), this)
    override fun `as`(alias: Name): TelegramUser = TelegramUser(alias, this)
    override fun `as`(alias: Table<*>): TelegramUser = TelegramUser(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): TelegramUser = TelegramUser(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): TelegramUser = TelegramUser(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): TelegramUser = TelegramUser(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): TelegramUser = TelegramUser(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): TelegramUser = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): TelegramUser = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): TelegramUser = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): TelegramUser = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): TelegramUser = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): TelegramUser = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): TelegramUser = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): TelegramUser = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): TelegramUser = where(DSL.notExists(select))
}
