/*
 * This file is generated by jOOQ.
 */
package io.heapy.kotbot.database.tables


import io.heapy.kotbot.database.Public
import io.heapy.kotbot.database.enums.VerificationSource
import io.heapy.kotbot.database.indexes.VERIFIED_USER_TELEGRAM_ID_UINDEX
import io.heapy.kotbot.database.keys.VERIFIED_USER_PKEY
import io.heapy.kotbot.database.tables.records.VerifiedUserRecord

import java.time.LocalDateTime

import kotlin.collections.Collection
import kotlin.collections.List

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Identity
import org.jooq.Index
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class VerifiedUser(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, VerifiedUserRecord>?,
    parentPath: InverseForeignKey<out Record, VerifiedUserRecord>?,
    aliased: Table<VerifiedUserRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<VerifiedUserRecord>(
    alias,
    Public.PUBLIC,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>public.verified_user</code>
         */
        val VERIFIED_USER: VerifiedUser = VerifiedUser()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<VerifiedUserRecord> = VerifiedUserRecord::class.java

    /**
     * The column <code>public.verified_user.id</code>.
     */
    val ID: TableField<VerifiedUserRecord, Long?> = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "")

    /**
     * The column <code>public.verified_user.telegram_id</code>.
     */
    val TELEGRAM_ID: TableField<VerifiedUserRecord, Long?> = createField(DSL.name("telegram_id"), SQLDataType.BIGINT.nullable(false), this, "")

    /**
     * The column <code>public.verified_user.source</code>.
     */
    val SOURCE: TableField<VerifiedUserRecord, VerificationSource?> = createField(DSL.name("source"), SQLDataType.VARCHAR.nullable(false).asEnumDataType(VerificationSource::class.java), this, "")

    /**
     * The column <code>public.verified_user.verified_at</code>.
     */
    val VERIFIED_AT: TableField<VerifiedUserRecord, LocalDateTime?> = createField(DSL.name("verified_at"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.LOCALDATETIME)), this, "")

    /**
     * The column <code>public.verified_user.session_id</code>.
     */
    val SESSION_ID: TableField<VerifiedUserRecord, Long?> = createField(DSL.name("session_id"), SQLDataType.BIGINT, this, "")

    private constructor(alias: Name, aliased: Table<VerifiedUserRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<VerifiedUserRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<VerifiedUserRecord>?, where: Condition?): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>public.verified_user</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>public.verified_user</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>public.verified_user</code> table reference
     */
    constructor(): this(DSL.name("verified_user"), null)
    override fun getSchema(): Schema? = if (aliased()) null else Public.PUBLIC
    override fun getIndexes(): List<Index> = listOf(VERIFIED_USER_TELEGRAM_ID_UINDEX)
    override fun getIdentity(): Identity<VerifiedUserRecord, Long?> = super.getIdentity() as Identity<VerifiedUserRecord, Long?>
    override fun getPrimaryKey(): UniqueKey<VerifiedUserRecord> = VERIFIED_USER_PKEY
    override fun `as`(alias: String): VerifiedUser = VerifiedUser(DSL.name(alias), this)
    override fun `as`(alias: Name): VerifiedUser = VerifiedUser(alias, this)
    override fun `as`(alias: Table<*>): VerifiedUser = VerifiedUser(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): VerifiedUser = VerifiedUser(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): VerifiedUser = VerifiedUser(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): VerifiedUser = VerifiedUser(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): VerifiedUser = VerifiedUser(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): VerifiedUser = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): VerifiedUser = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): VerifiedUser = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): VerifiedUser = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): VerifiedUser = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): VerifiedUser = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): VerifiedUser = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): VerifiedUser = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): VerifiedUser = where(DSL.notExists(select))
}
