/*
 * This file is generated by jOOQ.
 */
package io.heapy.kotbot.database.tables.records


import io.heapy.kotbot.database.tables.CallbackData
import io.heapy.kotbot.database.tables.interfaces.ICallbackData

import java.time.LocalDateTime
import java.util.UUID

import org.jooq.JSONB
import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
open class CallbackDataRecord private constructor() : UpdatableRecordImpl<CallbackDataRecord>(CallbackData.CALLBACK_DATA), ICallbackData {

    open override var id: UUID?
        set(value): Unit = set(0, value)
        get(): UUID? = get(0) as UUID?

    open override var `data`: JSONB
        set(value): Unit = set(1, value)
        get(): JSONB = get(1) as JSONB

    open override var type: String
        set(value): Unit = set(2, value)
        get(): String = get(2) as String

    open override var created: LocalDateTime
        set(value): Unit = set(3, value)
        get(): LocalDateTime = get(3) as LocalDateTime

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<UUID?> = super.key() as Record1<UUID?>

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    fun from(from: ICallbackData) {
        this.id = from.id
        this.`data` = from.`data`
        this.type = from.type
        this.created = from.created
        resetChangedOnNotNull()
    }

    /**
     * Create a detached, initialised CallbackDataRecord
     */
    constructor(id: UUID? = null, `data`: JSONB, type: String, created: LocalDateTime): this() {
        this.id = id
        this.`data` = `data`
        this.type = type
        this.created = created
        resetChangedOnNotNull()
    }

    /**
     * Create a detached, initialised CallbackDataRecord
     */
    constructor(value: io.heapy.kotbot.database.tables.pojos.CallbackData?): this() {
        if (value != null) {
            this.id = value.id
            this.`data` = value.`data`
            this.type = value.type
            this.created = value.created
            resetChangedOnNotNull()
        }
    }
}
