/*
 * This file is generated by jOOQ.
 */
package io.heapy.kotbot.database.tables.records


import io.heapy.kotbot.database.tables.CallbackData
import io.heapy.kotbot.database.tables.interfaces.ICallbackData

import java.time.LocalDateTime
import java.util.UUID

import org.jooq.JSONB
import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class CallbackDataRecord private constructor() : UpdatableRecordImpl<CallbackDataRecord>(CallbackData.CALLBACK_DATA), ICallbackData {

    open override var id: UUID?
        set(value): Unit = set(0, value)
        get(): UUID? = get(0) as UUID?

    open override var `data`: JSONB
        set(value): Unit = set(1, value)
        get(): JSONB = get(1) as JSONB

    open override var created: LocalDateTime
        set(value): Unit = set(2, value)
        get(): LocalDateTime = get(2) as LocalDateTime

    open override var consumed: Boolean?
        set(value): Unit = set(3, value)
        get(): Boolean? = get(3) as Boolean?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<UUID?> = super.key() as Record1<UUID?>

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    fun from(from: ICallbackData) {
        this.id = from.id
        this.`data` = from.`data`
        this.created = from.created
        this.consumed = from.consumed
        resetTouchedOnNotNull()
    }

    /**
     * Create a detached, initialised CallbackDataRecord
     */
    constructor(id: UUID? = null, `data`: JSONB, created: LocalDateTime, consumed: Boolean? = null): this() {
        this.id = id
        this.`data` = `data`
        this.created = created
        this.consumed = consumed
        resetTouchedOnNotNull()
    }

    /**
     * Create a detached, initialised CallbackDataRecord
     */
    constructor(value: ICallbackData?): this() {
        if (value != null) {
            this.id = value.id
            this.`data` = value.`data`
            this.created = value.created
            this.consumed = value.consumed
            resetTouchedOnNotNull()
        }
    }
}
