/*
 * This file is generated by jOOQ.
 */
package io.heapy.kotbot.database.tables.records


import io.heapy.kotbot.database.tables.ChallengeAttempt
import io.heapy.kotbot.database.tables.interfaces.IChallengeAttempt

import java.time.LocalDateTime
import java.util.UUID

import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class ChallengeAttemptRecord private constructor() : UpdatableRecordImpl<ChallengeAttemptRecord>(ChallengeAttempt.CHALLENGE_ATTEMPT), IChallengeAttempt {

    open override var id: Long?
        set(value): Unit = set(0, value)
        get(): Long? = get(0) as Long?

    open override var sessionId: Long
        set(value): Unit = set(1, value)
        get(): Long = get(1) as Long

    open override var telegramId: Long
        set(value): Unit = set(2, value)
        get(): Long = get(2) as Long

    open override var challengeId: UUID
        set(value): Unit = set(3, value)
        get(): UUID = get(3) as UUID

    open override var templateKey: String
        set(value): Unit = set(4, value)
        get(): String = get(4) as String

    open override var selectedAnswer: String
        set(value): Unit = set(5, value)
        get(): String = get(5) as String

    open override var correctAnswer: String
        set(value): Unit = set(6, value)
        get(): String = get(6) as String

    @Suppress("INAPPLICABLE_JVM_NAME")
    @set:JvmName("setIsCorrect")
    open override var isCorrect: Boolean
        set(value): Unit = set(7, value)
        get(): Boolean = get(7) as Boolean

    open override var challengeSentAt: LocalDateTime
        set(value): Unit = set(8, value)
        get(): LocalDateTime = get(8) as LocalDateTime

    open override var answeredAt: LocalDateTime?
        set(value): Unit = set(9, value)
        get(): LocalDateTime? = get(9) as LocalDateTime?

    open override var latencyMs: Long
        set(value): Unit = set(10, value)
        get(): Long = get(10) as Long

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<Long?> = super.key() as Record1<Long?>

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    fun from(from: IChallengeAttempt) {
        this.id = from.id
        this.sessionId = from.sessionId
        this.telegramId = from.telegramId
        this.challengeId = from.challengeId
        this.templateKey = from.templateKey
        this.selectedAnswer = from.selectedAnswer
        this.correctAnswer = from.correctAnswer
        this.isCorrect = from.isCorrect
        this.challengeSentAt = from.challengeSentAt
        this.answeredAt = from.answeredAt
        this.latencyMs = from.latencyMs
        resetTouchedOnNotNull()
    }

    /**
     * Create a detached, initialised ChallengeAttemptRecord
     */
    constructor(id: Long? = null, sessionId: Long, telegramId: Long, challengeId: UUID, templateKey: String, selectedAnswer: String, correctAnswer: String, isCorrect: Boolean, challengeSentAt: LocalDateTime, answeredAt: LocalDateTime? = null, latencyMs: Long): this() {
        this.id = id
        this.sessionId = sessionId
        this.telegramId = telegramId
        this.challengeId = challengeId
        this.templateKey = templateKey
        this.selectedAnswer = selectedAnswer
        this.correctAnswer = correctAnswer
        this.isCorrect = isCorrect
        this.challengeSentAt = challengeSentAt
        this.answeredAt = answeredAt
        this.latencyMs = latencyMs
        resetTouchedOnNotNull()
    }

    /**
     * Create a detached, initialised ChallengeAttemptRecord
     */
    constructor(value: IChallengeAttempt?): this() {
        if (value != null) {
            this.id = value.id
            this.sessionId = value.sessionId
            this.telegramId = value.telegramId
            this.challengeId = value.challengeId
            this.templateKey = value.templateKey
            this.selectedAnswer = value.selectedAnswer
            this.correctAnswer = value.correctAnswer
            this.isCorrect = value.isCorrect
            this.challengeSentAt = value.challengeSentAt
            this.answeredAt = value.answeredAt
            this.latencyMs = value.latencyMs
            resetTouchedOnNotNull()
        }
    }
}
