/*
 * This file is generated by jOOQ.
 */
package io.heapy.kotbot.database.tables.records


import io.heapy.kotbot.database.enums.FeedSource
import io.heapy.kotbot.database.tables.FeedItem
import io.heapy.kotbot.database.tables.interfaces.IFeedItem

import java.time.LocalDateTime

import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class FeedItemRecord private constructor() : UpdatableRecordImpl<FeedItemRecord>(FeedItem.FEED_ITEM), IFeedItem {

    open override var id: Long?
        set(value): Unit = set(0, value)
        get(): Long? = get(0) as Long?

    open override var source: FeedSource
        set(value): Unit = set(1, value)
        get(): FeedSource = get(1) as FeedSource

    open override var itemKey: String
        set(value): Unit = set(2, value)
        get(): String = get(2) as String

    open override var title: String
        set(value): Unit = set(3, value)
        get(): String = get(3) as String

    open override var url: String
        set(value): Unit = set(4, value)
        get(): String = get(4) as String

    open override var chatId: Long
        set(value): Unit = set(5, value)
        get(): Long = get(5) as Long

    open override var messageId: Int
        set(value): Unit = set(6, value)
        get(): Int = get(6) as Int

    open override var postedAt: LocalDateTime?
        set(value): Unit = set(7, value)
        get(): LocalDateTime? = get(7) as LocalDateTime?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<Long?> = super.key() as Record1<Long?>

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    fun from(from: IFeedItem) {
        this.id = from.id
        this.source = from.source
        this.itemKey = from.itemKey
        this.title = from.title
        this.url = from.url
        this.chatId = from.chatId
        this.messageId = from.messageId
        this.postedAt = from.postedAt
        resetTouchedOnNotNull()
    }

    /**
     * Create a detached, initialised FeedItemRecord
     */
    constructor(id: Long? = null, source: FeedSource, itemKey: String, title: String, url: String, chatId: Long, messageId: Int, postedAt: LocalDateTime? = null): this() {
        this.id = id
        this.source = source
        this.itemKey = itemKey
        this.title = title
        this.url = url
        this.chatId = chatId
        this.messageId = messageId
        this.postedAt = postedAt
        resetTouchedOnNotNull()
    }

    /**
     * Create a detached, initialised FeedItemRecord
     */
    constructor(value: IFeedItem?): this() {
        if (value != null) {
            this.id = value.id
            this.source = value.source
            this.itemKey = value.itemKey
            this.title = value.title
            this.url = value.url
            this.chatId = value.chatId
            this.messageId = value.messageId
            this.postedAt = value.postedAt
            resetTouchedOnNotNull()
        }
    }
}
