/*
 * This file is generated by jOOQ.
 */
package io.heapy.kotbot.database.tables.records


import io.heapy.kotbot.database.tables.GptSessionMessage
import io.heapy.kotbot.database.tables.interfaces.IGptSessionMessage

import java.time.LocalDateTime

import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class GptSessionMessageRecord private constructor() : UpdatableRecordImpl<GptSessionMessageRecord>(GptSessionMessage.GPT_SESSION_MESSAGE), IGptSessionMessage {

    open override var id: Long?
        set(value): Unit = set(0, value)
        get(): Long? = get(0) as Long?

    open override var sessionId: Long
        set(value): Unit = set(1, value)
        get(): Long = get(1) as Long

    open override var role: String
        set(value): Unit = set(2, value)
        get(): String = get(2) as String

    open override var content: String
        set(value): Unit = set(3, value)
        get(): String = get(3) as String

    open override var created: LocalDateTime?
        set(value): Unit = set(4, value)
        get(): LocalDateTime? = get(4) as LocalDateTime?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<Long?> = super.key() as Record1<Long?>

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    fun from(from: IGptSessionMessage) {
        this.id = from.id
        this.sessionId = from.sessionId
        this.role = from.role
        this.content = from.content
        this.created = from.created
        resetTouchedOnNotNull()
    }

    /**
     * Create a detached, initialised GptSessionMessageRecord
     */
    constructor(id: Long? = null, sessionId: Long, role: String, content: String, created: LocalDateTime? = null): this() {
        this.id = id
        this.sessionId = sessionId
        this.role = role
        this.content = content
        this.created = created
        resetTouchedOnNotNull()
    }

    /**
     * Create a detached, initialised GptSessionMessageRecord
     */
    constructor(value: IGptSessionMessage?): this() {
        if (value != null) {
            this.id = value.id
            this.sessionId = value.sessionId
            this.role = value.role
            this.content = value.content
            this.created = value.created
            resetTouchedOnNotNull()
        }
    }
}
