/*
 * This file is generated by jOOQ.
 */
package io.heapy.kotbot.database.tables.records


import io.heapy.kotbot.database.tables.GptSession
import io.heapy.kotbot.database.tables.interfaces.IGptSession

import java.time.LocalDateTime

import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class GptSessionRecord private constructor() : UpdatableRecordImpl<GptSessionRecord>(GptSession.GPT_SESSION), IGptSession {

    open override var id: Long?
        set(value): Unit = set(0, value)
        get(): Long? = get(0) as Long?

    open override var userId: Long
        set(value): Unit = set(1, value)
        get(): Long = get(1) as Long

    open override var groupChatId: Long
        set(value): Unit = set(2, value)
        get(): Long = get(2) as Long

    open override var waitMessageId: Int
        set(value): Unit = set(3, value)
        get(): Int = get(3) as Int

    open override var previewChatId: Long?
        set(value): Unit = set(4, value)
        get(): Long? = get(4) as Long?

    open override var previewMessageId: Int?
        set(value): Unit = set(5, value)
        get(): Int? = get(5) as Int?

    open override var status: String?
        set(value): Unit = set(6, value)
        get(): String? = get(6) as String?

    open override var created: LocalDateTime?
        set(value): Unit = set(7, value)
        get(): LocalDateTime? = get(7) as LocalDateTime?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<Long?> = super.key() as Record1<Long?>

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    fun from(from: IGptSession) {
        this.id = from.id
        this.userId = from.userId
        this.groupChatId = from.groupChatId
        this.waitMessageId = from.waitMessageId
        this.previewChatId = from.previewChatId
        this.previewMessageId = from.previewMessageId
        this.status = from.status
        this.created = from.created
        resetTouchedOnNotNull()
    }

    /**
     * Create a detached, initialised GptSessionRecord
     */
    constructor(id: Long? = null, userId: Long, groupChatId: Long, waitMessageId: Int, previewChatId: Long? = null, previewMessageId: Int? = null, status: String? = null, created: LocalDateTime? = null): this() {
        this.id = id
        this.userId = userId
        this.groupChatId = groupChatId
        this.waitMessageId = waitMessageId
        this.previewChatId = previewChatId
        this.previewMessageId = previewMessageId
        this.status = status
        this.created = created
        resetTouchedOnNotNull()
    }

    /**
     * Create a detached, initialised GptSessionRecord
     */
    constructor(value: IGptSession?): this() {
        if (value != null) {
            this.id = value.id
            this.userId = value.userId
            this.groupChatId = value.groupChatId
            this.waitMessageId = value.waitMessageId
            this.previewChatId = value.previewChatId
            this.previewMessageId = value.previewMessageId
            this.status = value.status
            this.created = value.created
            resetTouchedOnNotNull()
        }
    }
}
