/*
 * This file is generated by jOOQ.
 */
package io.heapy.kotbot.database.tables.records


import io.heapy.kotbot.database.enums.JobExecutionStatus
import io.heapy.kotbot.database.tables.JobExecution
import io.heapy.kotbot.database.tables.interfaces.IJobExecution

import java.time.LocalDateTime

import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class JobExecutionRecord private constructor() : UpdatableRecordImpl<JobExecutionRecord>(JobExecution.JOB_EXECUTION), IJobExecution {

    open override var id: Long?
        set(value): Unit = set(0, value)
        get(): Long? = get(0) as Long?

    open override var jobName: String
        set(value): Unit = set(1, value)
        get(): String = get(1) as String

    open override var started: LocalDateTime?
        set(value): Unit = set(2, value)
        get(): LocalDateTime? = get(2) as LocalDateTime?

    open override var finished: LocalDateTime?
        set(value): Unit = set(3, value)
        get(): LocalDateTime? = get(3) as LocalDateTime?

    open override var status: JobExecutionStatus?
        set(value): Unit = set(4, value)
        get(): JobExecutionStatus? = get(4) as JobExecutionStatus?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<Long?> = super.key() as Record1<Long?>

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    fun from(from: IJobExecution) {
        this.id = from.id
        this.jobName = from.jobName
        this.started = from.started
        this.finished = from.finished
        this.status = from.status
        resetTouchedOnNotNull()
    }

    /**
     * Create a detached, initialised JobExecutionRecord
     */
    constructor(id: Long? = null, jobName: String, started: LocalDateTime? = null, finished: LocalDateTime? = null, status: JobExecutionStatus? = null): this() {
        this.id = id
        this.jobName = jobName
        this.started = started
        this.finished = finished
        this.status = status
        resetTouchedOnNotNull()
    }

    /**
     * Create a detached, initialised JobExecutionRecord
     */
    constructor(value: IJobExecution?): this() {
        if (value != null) {
            this.id = value.id
            this.jobName = value.jobName
            this.started = value.started
            this.finished = value.finished
            this.status = value.status
            resetTouchedOnNotNull()
        }
    }
}
