/*
 * This file is generated by jOOQ.
 */
package io.heapy.kotbot.database.tables.records


import io.heapy.kotbot.database.enums.JoinSessionStatus
import io.heapy.kotbot.database.tables.JoinSession
import io.heapy.kotbot.database.tables.interfaces.IJoinSession

import java.time.LocalDateTime
import java.util.UUID

import org.jooq.JSONB
import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class JoinSessionRecord private constructor() : UpdatableRecordImpl<JoinSessionRecord>(JoinSession.JOIN_SESSION), IJoinSession {

    open override var id: Long?
        set(value): Unit = set(0, value)
        get(): Long? = get(0) as Long?

    open override var telegramId: Long
        set(value): Unit = set(1, value)
        get(): Long = get(1) as Long

    open override var chatId: Long
        set(value): Unit = set(2, value)
        get(): Long = get(2) as Long

    open override var userChatId: Long
        set(value): Unit = set(3, value)
        get(): Long = get(3) as Long

    open override var status: JoinSessionStatus?
        set(value): Unit = set(4, value)
        get(): JoinSessionStatus? = get(4) as JoinSessionStatus?

    open override var maxAttempts: Int
        set(value): Unit = set(5, value)
        get(): Int = get(5) as Int

    open override var attemptsUsed: Int?
        set(value): Unit = set(6, value)
        get(): Int? = get(6) as Int?

    open override var expiresAt: LocalDateTime
        set(value): Unit = set(7, value)
        get(): LocalDateTime = get(7) as LocalDateTime

    open override var createdAt: LocalDateTime?
        set(value): Unit = set(8, value)
        get(): LocalDateTime? = get(8) as LocalDateTime?

    open override var finishedAt: LocalDateTime?
        set(value): Unit = set(9, value)
        get(): LocalDateTime? = get(9) as LocalDateTime?

    open override var challengeId: UUID?
        set(value): Unit = set(10, value)
        get(): UUID? = get(10) as UUID?

    open override var templateKey: String?
        set(value): Unit = set(11, value)
        get(): String? = get(11) as String?

    open override var seed: Long?
        set(value): Unit = set(12, value)
        get(): Long? = get(12) as Long?

    open override var snippet: String?
        set(value): Unit = set(13, value)
        get(): String? = get(13) as String?

    open override var correctAnswer: String?
        set(value): Unit = set(14, value)
        get(): String? = get(14) as String?

    open override var options: JSONB?
        set(value): Unit = set(15, value)
        get(): JSONB? = get(15) as JSONB?

    open override var challengeSentAt: LocalDateTime?
        set(value): Unit = set(16, value)
        get(): LocalDateTime? = get(16) as LocalDateTime?

    open override var messageId: Int?
        set(value): Unit = set(17, value)
        get(): Int? = get(17) as Int?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<Long?> = super.key() as Record1<Long?>

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    fun from(from: IJoinSession) {
        this.id = from.id
        this.telegramId = from.telegramId
        this.chatId = from.chatId
        this.userChatId = from.userChatId
        this.status = from.status
        this.maxAttempts = from.maxAttempts
        this.attemptsUsed = from.attemptsUsed
        this.expiresAt = from.expiresAt
        this.createdAt = from.createdAt
        this.finishedAt = from.finishedAt
        this.challengeId = from.challengeId
        this.templateKey = from.templateKey
        this.seed = from.seed
        this.snippet = from.snippet
        this.correctAnswer = from.correctAnswer
        this.options = from.options
        this.challengeSentAt = from.challengeSentAt
        this.messageId = from.messageId
        resetTouchedOnNotNull()
    }

    /**
     * Create a detached, initialised JoinSessionRecord
     */
    constructor(id: Long? = null, telegramId: Long, chatId: Long, userChatId: Long, status: JoinSessionStatus? = null, maxAttempts: Int, attemptsUsed: Int? = null, expiresAt: LocalDateTime, createdAt: LocalDateTime? = null, finishedAt: LocalDateTime? = null, challengeId: UUID? = null, templateKey: String? = null, seed: Long? = null, snippet: String? = null, correctAnswer: String? = null, options: JSONB? = null, challengeSentAt: LocalDateTime? = null, messageId: Int? = null): this() {
        this.id = id
        this.telegramId = telegramId
        this.chatId = chatId
        this.userChatId = userChatId
        this.status = status
        this.maxAttempts = maxAttempts
        this.attemptsUsed = attemptsUsed
        this.expiresAt = expiresAt
        this.createdAt = createdAt
        this.finishedAt = finishedAt
        this.challengeId = challengeId
        this.templateKey = templateKey
        this.seed = seed
        this.snippet = snippet
        this.correctAnswer = correctAnswer
        this.options = options
        this.challengeSentAt = challengeSentAt
        this.messageId = messageId
        resetTouchedOnNotNull()
    }

    /**
     * Create a detached, initialised JoinSessionRecord
     */
    constructor(value: IJoinSession?): this() {
        if (value != null) {
            this.id = value.id
            this.telegramId = value.telegramId
            this.chatId = value.chatId
            this.userChatId = value.userChatId
            this.status = value.status
            this.maxAttempts = value.maxAttempts
            this.attemptsUsed = value.attemptsUsed
            this.expiresAt = value.expiresAt
            this.createdAt = value.createdAt
            this.finishedAt = value.finishedAt
            this.challengeId = value.challengeId
            this.templateKey = value.templateKey
            this.seed = value.seed
            this.snippet = value.snippet
            this.correctAnswer = value.correctAnswer
            this.options = value.options
            this.challengeSentAt = value.challengeSentAt
            this.messageId = value.messageId
            resetTouchedOnNotNull()
        }
    }
}
