/*
 * This file is generated by jOOQ.
 */
package io.heapy.kotbot.database.tables.records


import io.heapy.kotbot.database.enums.VerificationSource
import io.heapy.kotbot.database.tables.VerifiedUser
import io.heapy.kotbot.database.tables.interfaces.IVerifiedUser

import java.time.LocalDateTime

import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class VerifiedUserRecord private constructor() : UpdatableRecordImpl<VerifiedUserRecord>(VerifiedUser.VERIFIED_USER), IVerifiedUser {

    open override var id: Long?
        set(value): Unit = set(0, value)
        get(): Long? = get(0) as Long?

    open override var telegramId: Long
        set(value): Unit = set(1, value)
        get(): Long = get(1) as Long

    open override var source: VerificationSource
        set(value): Unit = set(2, value)
        get(): VerificationSource = get(2) as VerificationSource

    open override var verifiedAt: LocalDateTime?
        set(value): Unit = set(3, value)
        get(): LocalDateTime? = get(3) as LocalDateTime?

    open override var sessionId: Long?
        set(value): Unit = set(4, value)
        get(): Long? = get(4) as Long?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<Long?> = super.key() as Record1<Long?>

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    fun from(from: IVerifiedUser) {
        this.id = from.id
        this.telegramId = from.telegramId
        this.source = from.source
        this.verifiedAt = from.verifiedAt
        this.sessionId = from.sessionId
        resetTouchedOnNotNull()
    }

    /**
     * Create a detached, initialised VerifiedUserRecord
     */
    constructor(id: Long? = null, telegramId: Long, source: VerificationSource, verifiedAt: LocalDateTime? = null, sessionId: Long? = null): this() {
        this.id = id
        this.telegramId = telegramId
        this.source = source
        this.verifiedAt = verifiedAt
        this.sessionId = sessionId
        resetTouchedOnNotNull()
    }

    /**
     * Create a detached, initialised VerifiedUserRecord
     */
    constructor(value: IVerifiedUser?): this() {
        if (value != null) {
            this.id = value.id
            this.telegramId = value.telegramId
            this.source = value.source
            this.verifiedAt = value.verifiedAt
            this.sessionId = value.sessionId
            resetTouchedOnNotNull()
        }
    }
}
