/*
 * This file is generated by jOOQ.
 */
package io.heapy.tgpt.database.tables.interfaces


import java.io.Serializable
import java.time.LocalDateTime


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
interface IAllowedUser : Serializable {
    val id: Long?
    val telegramId: Long
    val username: String?
    val displayName: String?
    val isActive: Boolean?
    val created: LocalDateTime?
}
