/*
 * This file is generated by jOOQ.
 */
package io.heapy.tgpt.database.tables.interfaces


import java.io.Serializable
import java.math.BigDecimal
import java.time.LocalDateTime


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
interface IApiCall : Serializable {
    val id: Long?
    val threadId: Long
    val telegramUserId: Long
    val model: String
    val promptTokens: Int
    val completionTokens: Int
    val totalTokens: Int
    val estimatedCostUsd: BigDecimal
    val created: LocalDateTime?
}
