/*
 * This file is generated by jOOQ.
 */
package io.heapy.tgpt.database.tables.interfaces


import java.io.Serializable
import java.time.LocalDateTime


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
interface IThread : Serializable {
    val id: Long?
    val chatId: Long
    val createdBy: Long
    val forkedFromThreadId: Long?
    val forkedAtMessageId: Long?
    val created: LocalDateTime?
}
