/*
 * This file is generated by jOOQ.
 */
package io.heapy.tgpt.database.tables.interfaces


import io.heapy.tgpt.database.enums.ContentType
import io.heapy.tgpt.database.enums.MessageRole

import java.io.Serializable
import java.time.LocalDateTime


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
interface IThreadMessage : Serializable {
    val id: Long?
    val threadId: Long
    val role: MessageRole
    val contentType: ContentType?
    val content: String
    val telegramMessageId: Int?
    val telegramUserId: Long?
    val created: LocalDateTime?
}
