version: "2.4"
services:
  kotbot:
    image: ghcr.io/heapy/kotbot:${KOTBOT_VERSION}
    container_name: kotbot
    restart: always
    environment:
      KOTBOT_OPTS: "-Xmx128m"
      KOTBOT_TOKEN: ${KOTBOT_TOKEN}
      KOTBOT_VERSION: ${KOTBOT_VERSION}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    logging:
      driver: "journald"
    mem_limit: 256m
    mem_swappiness: 0
