@file:Suppress("warnings")
/*
 * This file is generated by jOOQ.
 */
package io.heapy.kotbot.database.indexes


import io.heapy.kotbot.database.tables.GptSession
import io.heapy.kotbot.database.tables.TelegramUser

import org.jooq.Index
import org.jooq.impl.DSL
import org.jooq.impl.Internal



// -------------------------------------------------------------------------
// INDEX definitions
// -------------------------------------------------------------------------

val GPT_SESSION_PREVIEW_UINDEX: Index = Internal.createIndex(DSL.name("gpt_session_preview_uindex"), GptSession.GPT_SESSION, arrayOf(GptSession.GPT_SESSION.PREVIEW_CHAT_ID, GptSession.GPT_SESSION.PREVIEW_MESSAGE_ID), true)
val TELEGRAM_USER_TELEGRAM_ID_UINDEX: Index = Internal.createIndex(DSL.name("telegram_user_telegram_id_uindex"), TelegramUser.TELEGRAM_USER, arrayOf(TelegramUser.TELEGRAM_USER.TELEGRAM_ID), true)
