package io.heapy.kotbot.bot.challenge

import io.heapy.kotbot.bot.join.createJoinChallengeModule
import org.junit.jupiter.api.Test
import java.io.File
import kotlin.random.Random

class ChallengeSnippetVerificationGenerator {

    @Test
    fun `generate verification test class`() {
        val joinChallengeModule = createJoinChallengeModule {}
        val templates = joinChallengeModule.challengeTemplates
        val challengesPerTemplate = 100
        val batchSize = 50

        val sb = StringBuilder()
        sb.appendLine("package io.heapy.kotbot.bot.challenge")
        sb.appendLine()
        sb.appendLine("import org.junit.jupiter.api.Assertions.assertEquals")
        sb.appendLine("import org.junit.jupiter.api.Test")
        sb.appendLine()
        sb.appendLine("/**")
        sb.appendLine(" * Auto-generated test that executes challenge snippets and verifies correctness.")
        sb.appendLine(" * Generated by [ChallengeSnippetVerificationGenerator].")
        sb.appendLine(" * DO NOT EDIT MANUALLY.")
        sb.appendLine(" */")
        sb.appendLine("""class GeneratedChallengeVerificationTest {""")
        sb.appendLine()
        sb.appendLine("""    private fun verify(expected: String, actual: Any?, seed: Long, snippet: String) {""")
        sb.appendLine($$"""        assertEquals(expected, "$actual", "seed=$seed snippet=$snippet")""")
        sb.appendLine("""    }""")

        for (template in templates) {
            val challenges = (0 until challengesPerTemplate).map { i ->
                template.generate(Random(i.toLong()))
            }

            val batches = challenges.chunked(batchSize)

            for ((batchIndex, batch) in batches.withIndex()) {
                sb.appendLine()
                sb.appendLine("    @Test")
                sb.appendLine("    fun `verify ${template.key} batch $batchIndex`() {")

                for (challenge in batch) {
                    val snippetLines = challenge.snippet.split("\n")
                    val escapedSnippet = challenge.snippet
                        .replace("\\", "\\\\")
                        .replace("\"", "\\\"")
                        .replace("\$", "\\\$")
                        .replace("\n", "\\n")

                    if (snippetLines.size == 1) {
                        sb.appendLine("        verify(\"${escapeString(challenge.correctAnswer)}\", run { ${snippetLines[0]} }, ${challenge.seed}L, \"${escapedSnippet}\")")
                    } else {
                        sb.appendLine("        verify(\"${escapeString(challenge.correctAnswer)}\", run {")
                        for (line in snippetLines) {
                            sb.appendLine("            $line")
                        }
                        sb.appendLine("        }, ${challenge.seed}L, \"${escapedSnippet}\")")
                    }
                }

                sb.appendLine("    }")
            }
        }

        sb.appendLine("}")

        val outputFile = File(
            "src/test/kotlin/io/heapy/kotbot/bot/challenge/GeneratedChallengeVerificationTest.kt"
        )
        outputFile.writeText(sb.toString())
        println("Generated ${outputFile.absolutePath}")
        println("Total challenges: ${templates.size * challengesPerTemplate}")
    }

    private fun escapeString(s: String): String {
        return s
            .replace("\\", "\\\\")
            .replace("\"", "\\\"")
            .replace("$", "\\$")
    }
}
