@file:Suppress("warnings")
/*
 * This file is generated by jOOQ.
 */
package io.heapy.tgpt.database.tables.references


import io.heapy.tgpt.database.tables.AllowedUser
import io.heapy.tgpt.database.tables.ApiCall
import io.heapy.tgpt.database.tables.Thread
import io.heapy.tgpt.database.tables.ThreadMessage



/**
 * The table <code>public.allowed_user</code>.
 */
val ALLOWED_USER: AllowedUser = AllowedUser.ALLOWED_USER

/**
 * The table <code>public.api_call</code>.
 */
val API_CALL: ApiCall = ApiCall.API_CALL

/**
 * The table <code>public.thread</code>.
 */
val THREAD: Thread = Thread.THREAD

/**
 * The table <code>public.thread_message</code>.
 */
val THREAD_MESSAGE: ThreadMessage = ThreadMessage.THREAD_MESSAGE
