/*
 * This file is generated by jOOQ.
 */
package io.heapy.tgpt.database.tables.records


import io.heapy.tgpt.database.tables.AllowedUser
import io.heapy.tgpt.database.tables.interfaces.IAllowedUser

import java.time.LocalDateTime

import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class AllowedUserRecord private constructor() : UpdatableRecordImpl<AllowedUserRecord>(AllowedUser.ALLOWED_USER), IAllowedUser {

    open override var id: Long?
        set(value): Unit = set(0, value)
        get(): Long? = get(0) as Long?

    open override var telegramId: Long
        set(value): Unit = set(1, value)
        get(): Long = get(1) as Long

    open override var username: String?
        set(value): Unit = set(2, value)
        get(): String? = get(2) as String?

    open override var displayName: String?
        set(value): Unit = set(3, value)
        get(): String? = get(3) as String?

    @Suppress("INAPPLICABLE_JVM_NAME")
    @set:JvmName("setIsActive")
    open override var isActive: Boolean?
        set(value): Unit = set(4, value)
        get(): Boolean? = get(4) as Boolean?

    open override var created: LocalDateTime?
        set(value): Unit = set(5, value)
        get(): LocalDateTime? = get(5) as LocalDateTime?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<Long?> = super.key() as Record1<Long?>

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    fun from(from: IAllowedUser) {
        this.id = from.id
        this.telegramId = from.telegramId
        this.username = from.username
        this.displayName = from.displayName
        this.isActive = from.isActive
        this.created = from.created
        resetTouchedOnNotNull()
    }

    /**
     * Create a detached, initialised AllowedUserRecord
     */
    constructor(id: Long? = null, telegramId: Long, username: String? = null, displayName: String? = null, isActive: Boolean? = null, created: LocalDateTime? = null): this() {
        this.id = id
        this.telegramId = telegramId
        this.username = username
        this.displayName = displayName
        this.isActive = isActive
        this.created = created
        resetTouchedOnNotNull()
    }

    /**
     * Create a detached, initialised AllowedUserRecord
     */
    constructor(value: IAllowedUser?): this() {
        if (value != null) {
            this.id = value.id
            this.telegramId = value.telegramId
            this.username = value.username
            this.displayName = value.displayName
            this.isActive = value.isActive
            this.created = value.created
            resetTouchedOnNotNull()
        }
    }
}
