/*
 * This file is generated by jOOQ.
 */
package io.heapy.tgpt.database.tables.records


import io.heapy.tgpt.database.tables.ApiCall
import io.heapy.tgpt.database.tables.interfaces.IApiCall

import java.math.BigDecimal
import java.time.LocalDateTime

import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class ApiCallRecord private constructor() : UpdatableRecordImpl<ApiCallRecord>(ApiCall.API_CALL), IApiCall {

    open override var id: Long?
        set(value): Unit = set(0, value)
        get(): Long? = get(0) as Long?

    open override var threadId: Long
        set(value): Unit = set(1, value)
        get(): Long = get(1) as Long

    open override var telegramUserId: Long
        set(value): Unit = set(2, value)
        get(): Long = get(2) as Long

    open override var model: String
        set(value): Unit = set(3, value)
        get(): String = get(3) as String

    open override var promptTokens: Int
        set(value): Unit = set(4, value)
        get(): Int = get(4) as Int

    open override var completionTokens: Int
        set(value): Unit = set(5, value)
        get(): Int = get(5) as Int

    open override var totalTokens: Int
        set(value): Unit = set(6, value)
        get(): Int = get(6) as Int

    open override var estimatedCostUsd: BigDecimal
        set(value): Unit = set(7, value)
        get(): BigDecimal = get(7) as BigDecimal

    open override var created: LocalDateTime?
        set(value): Unit = set(8, value)
        get(): LocalDateTime? = get(8) as LocalDateTime?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<Long?> = super.key() as Record1<Long?>

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    fun from(from: IApiCall) {
        this.id = from.id
        this.threadId = from.threadId
        this.telegramUserId = from.telegramUserId
        this.model = from.model
        this.promptTokens = from.promptTokens
        this.completionTokens = from.completionTokens
        this.totalTokens = from.totalTokens
        this.estimatedCostUsd = from.estimatedCostUsd
        this.created = from.created
        resetTouchedOnNotNull()
    }

    /**
     * Create a detached, initialised ApiCallRecord
     */
    constructor(id: Long? = null, threadId: Long, telegramUserId: Long, model: String, promptTokens: Int, completionTokens: Int, totalTokens: Int, estimatedCostUsd: BigDecimal, created: LocalDateTime? = null): this() {
        this.id = id
        this.threadId = threadId
        this.telegramUserId = telegramUserId
        this.model = model
        this.promptTokens = promptTokens
        this.completionTokens = completionTokens
        this.totalTokens = totalTokens
        this.estimatedCostUsd = estimatedCostUsd
        this.created = created
        resetTouchedOnNotNull()
    }

    /**
     * Create a detached, initialised ApiCallRecord
     */
    constructor(value: IApiCall?): this() {
        if (value != null) {
            this.id = value.id
            this.threadId = value.threadId
            this.telegramUserId = value.telegramUserId
            this.model = value.model
            this.promptTokens = value.promptTokens
            this.completionTokens = value.completionTokens
            this.totalTokens = value.totalTokens
            this.estimatedCostUsd = value.estimatedCostUsd
            this.created = value.created
            resetTouchedOnNotNull()
        }
    }
}
