/*
 * This file is generated by jOOQ.
 */
package io.heapy.tgpt.database.tables.records


import io.heapy.tgpt.database.tables.Thread
import io.heapy.tgpt.database.tables.interfaces.IThread

import java.time.LocalDateTime

import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class ThreadRecord private constructor() : UpdatableRecordImpl<ThreadRecord>(Thread.THREAD), IThread {

    open override var id: Long?
        set(value): Unit = set(0, value)
        get(): Long? = get(0) as Long?

    open override var chatId: Long
        set(value): Unit = set(1, value)
        get(): Long = get(1) as Long

    open override var createdBy: Long
        set(value): Unit = set(2, value)
        get(): Long = get(2) as Long

    open override var forkedFromThreadId: Long?
        set(value): Unit = set(3, value)
        get(): Long? = get(3) as Long?

    open override var forkedAtMessageId: Long?
        set(value): Unit = set(4, value)
        get(): Long? = get(4) as Long?

    open override var created: LocalDateTime?
        set(value): Unit = set(5, value)
        get(): LocalDateTime? = get(5) as LocalDateTime?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<Long?> = super.key() as Record1<Long?>

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    fun from(from: IThread) {
        this.id = from.id
        this.chatId = from.chatId
        this.createdBy = from.createdBy
        this.forkedFromThreadId = from.forkedFromThreadId
        this.forkedAtMessageId = from.forkedAtMessageId
        this.created = from.created
        resetTouchedOnNotNull()
    }

    /**
     * Create a detached, initialised ThreadRecord
     */
    constructor(id: Long? = null, chatId: Long, createdBy: Long, forkedFromThreadId: Long? = null, forkedAtMessageId: Long? = null, created: LocalDateTime? = null): this() {
        this.id = id
        this.chatId = chatId
        this.createdBy = createdBy
        this.forkedFromThreadId = forkedFromThreadId
        this.forkedAtMessageId = forkedAtMessageId
        this.created = created
        resetTouchedOnNotNull()
    }

    /**
     * Create a detached, initialised ThreadRecord
     */
    constructor(value: IThread?): this() {
        if (value != null) {
            this.id = value.id
            this.chatId = value.chatId
            this.createdBy = value.createdBy
            this.forkedFromThreadId = value.forkedFromThreadId
            this.forkedAtMessageId = value.forkedAtMessageId
            this.created = value.created
            resetTouchedOnNotNull()
        }
    }
}
