/*
 * This file is generated by jOOQ.
 */
package io.heapy.tgpt.database.tables.records


import io.heapy.tgpt.database.enums.ContentType
import io.heapy.tgpt.database.enums.MessageRole
import io.heapy.tgpt.database.tables.ThreadMessage
import io.heapy.tgpt.database.tables.interfaces.IThreadMessage

import java.time.LocalDateTime

import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class ThreadMessageRecord private constructor() : UpdatableRecordImpl<ThreadMessageRecord>(ThreadMessage.THREAD_MESSAGE), IThreadMessage {

    open override var id: Long?
        set(value): Unit = set(0, value)
        get(): Long? = get(0) as Long?

    open override var threadId: Long
        set(value): Unit = set(1, value)
        get(): Long = get(1) as Long

    open override var role: MessageRole
        set(value): Unit = set(2, value)
        get(): MessageRole = get(2) as MessageRole

    open override var contentType: ContentType?
        set(value): Unit = set(3, value)
        get(): ContentType? = get(3) as ContentType?

    open override var content: String
        set(value): Unit = set(4, value)
        get(): String = get(4) as String

    open override var telegramMessageId: Int?
        set(value): Unit = set(5, value)
        get(): Int? = get(5) as Int?

    open override var telegramUserId: Long?
        set(value): Unit = set(6, value)
        get(): Long? = get(6) as Long?

    open override var created: LocalDateTime?
        set(value): Unit = set(7, value)
        get(): LocalDateTime? = get(7) as LocalDateTime?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<Long?> = super.key() as Record1<Long?>

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    fun from(from: IThreadMessage) {
        this.id = from.id
        this.threadId = from.threadId
        this.role = from.role
        this.contentType = from.contentType
        this.content = from.content
        this.telegramMessageId = from.telegramMessageId
        this.telegramUserId = from.telegramUserId
        this.created = from.created
        resetTouchedOnNotNull()
    }

    /**
     * Create a detached, initialised ThreadMessageRecord
     */
    constructor(id: Long? = null, threadId: Long, role: MessageRole, contentType: ContentType? = null, content: String, telegramMessageId: Int? = null, telegramUserId: Long? = null, created: LocalDateTime? = null): this() {
        this.id = id
        this.threadId = threadId
        this.role = role
        this.contentType = contentType
        this.content = content
        this.telegramMessageId = telegramMessageId
        this.telegramUserId = telegramUserId
        this.created = created
        resetTouchedOnNotNull()
    }

    /**
     * Create a detached, initialised ThreadMessageRecord
     */
    constructor(value: IThreadMessage?): this() {
        if (value != null) {
            this.id = value.id
            this.threadId = value.threadId
            this.role = value.role
            this.contentType = value.contentType
            this.content = value.content
            this.telegramMessageId = value.telegramMessageId
            this.telegramUserId = value.telegramUserId
            this.created = value.created
            resetTouchedOnNotNull()
        }
    }
}
