/*
 * This file is generated by jOOQ.
 */
package io.heapy.tgpt.database.tables.pojos


import io.heapy.tgpt.database.tables.interfaces.IAllowedUser

import java.time.LocalDateTime


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
data class AllowedUser(
    override val id: Long? = null,
    override val telegramId: Long,
    override val username: String? = null,
    override val displayName: String? = null,
    override val isActive: Boolean? = null,
    override val created: LocalDateTime? = null
): IAllowedUser {

    override fun equals(other: Any?): Boolean {
        if (this === other)
            return true
        if (other == null)
            return false
        if (this::class != other::class)
            return false
        val o: AllowedUser = other as AllowedUser
        if (this.id == null) {
            if (o.id != null)
                return false
        }
        else if (this.id != o.id)
            return false
        if (this.telegramId != o.telegramId)
            return false
        if (this.username == null) {
            if (o.username != null)
                return false
        }
        else if (this.username != o.username)
            return false
        if (this.displayName == null) {
            if (o.displayName != null)
                return false
        }
        else if (this.displayName != o.displayName)
            return false
        if (this.isActive == null) {
            if (o.isActive != null)
                return false
        }
        else if (this.isActive != o.isActive)
            return false
        if (this.created == null) {
            if (o.created != null)
                return false
        }
        else if (this.created != o.created)
            return false
        return true
    }

    override fun hashCode(): Int {
        val prime = 31
        var result = 1
        result = prime * result + (if (this.id == null) 0 else this.id.hashCode())
        result = prime * result + this.telegramId.hashCode()
        result = prime * result + (if (this.username == null) 0 else this.username.hashCode())
        result = prime * result + (if (this.displayName == null) 0 else this.displayName.hashCode())
        result = prime * result + (if (this.isActive == null) 0 else this.isActive.hashCode())
        result = prime * result + (if (this.created == null) 0 else this.created.hashCode())
        return result
    }

    override fun toString(): String {
        val sb = StringBuilder("AllowedUser (")

        sb.append(id)
        sb.append(", ").append(telegramId)
        sb.append(", ").append(username)
        sb.append(", ").append(displayName)
        sb.append(", ").append(isActive)
        sb.append(", ").append(created)

        sb.append(")")
        return sb.toString()
    }
}
