/*
 * This file is generated by jOOQ.
 */
package io.heapy.tgpt.database.tables.pojos


import io.heapy.tgpt.database.tables.interfaces.IApiCall

import java.math.BigDecimal
import java.time.LocalDateTime


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
data class ApiCall(
    override val id: Long? = null,
    override val threadId: Long,
    override val telegramUserId: Long,
    override val model: String,
    override val promptTokens: Int,
    override val completionTokens: Int,
    override val totalTokens: Int,
    override val estimatedCostUsd: BigDecimal,
    override val created: LocalDateTime? = null
): IApiCall {

    override fun equals(other: Any?): Boolean {
        if (this === other)
            return true
        if (other == null)
            return false
        if (this::class != other::class)
            return false
        val o: ApiCall = other as ApiCall
        if (this.id == null) {
            if (o.id != null)
                return false
        }
        else if (this.id != o.id)
            return false
        if (this.threadId != o.threadId)
            return false
        if (this.telegramUserId != o.telegramUserId)
            return false
        if (this.model != o.model)
            return false
        if (this.promptTokens != o.promptTokens)
            return false
        if (this.completionTokens != o.completionTokens)
            return false
        if (this.totalTokens != o.totalTokens)
            return false
        if (this.estimatedCostUsd != o.estimatedCostUsd)
            return false
        if (this.created == null) {
            if (o.created != null)
                return false
        }
        else if (this.created != o.created)
            return false
        return true
    }

    override fun hashCode(): Int {
        val prime = 31
        var result = 1
        result = prime * result + (if (this.id == null) 0 else this.id.hashCode())
        result = prime * result + this.threadId.hashCode()
        result = prime * result + this.telegramUserId.hashCode()
        result = prime * result + this.model.hashCode()
        result = prime * result + this.promptTokens.hashCode()
        result = prime * result + this.completionTokens.hashCode()
        result = prime * result + this.totalTokens.hashCode()
        result = prime * result + this.estimatedCostUsd.hashCode()
        result = prime * result + (if (this.created == null) 0 else this.created.hashCode())
        return result
    }

    override fun toString(): String {
        val sb = StringBuilder("ApiCall (")

        sb.append(id)
        sb.append(", ").append(threadId)
        sb.append(", ").append(telegramUserId)
        sb.append(", ").append(model)
        sb.append(", ").append(promptTokens)
        sb.append(", ").append(completionTokens)
        sb.append(", ").append(totalTokens)
        sb.append(", ").append(estimatedCostUsd)
        sb.append(", ").append(created)

        sb.append(")")
        return sb.toString()
    }
}
