/*
 * This file is generated by jOOQ.
 */
package io.heapy.tgpt.database.tables.pojos


import io.heapy.tgpt.database.tables.interfaces.IThread

import java.time.LocalDateTime


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
data class Thread(
    override val id: Long? = null,
    override val chatId: Long,
    override val createdBy: Long,
    override val forkedFromThreadId: Long? = null,
    override val forkedAtMessageId: Long? = null,
    override val created: LocalDateTime? = null
): IThread {

    override fun equals(other: Any?): Boolean {
        if (this === other)
            return true
        if (other == null)
            return false
        if (this::class != other::class)
            return false
        val o: Thread = other as Thread
        if (this.id == null) {
            if (o.id != null)
                return false
        }
        else if (this.id != o.id)
            return false
        if (this.chatId != o.chatId)
            return false
        if (this.createdBy != o.createdBy)
            return false
        if (this.forkedFromThreadId == null) {
            if (o.forkedFromThreadId != null)
                return false
        }
        else if (this.forkedFromThreadId != o.forkedFromThreadId)
            return false
        if (this.forkedAtMessageId == null) {
            if (o.forkedAtMessageId != null)
                return false
        }
        else if (this.forkedAtMessageId != o.forkedAtMessageId)
            return false
        if (this.created == null) {
            if (o.created != null)
                return false
        }
        else if (this.created != o.created)
            return false
        return true
    }

    override fun hashCode(): Int {
        val prime = 31
        var result = 1
        result = prime * result + (if (this.id == null) 0 else this.id.hashCode())
        result = prime * result + this.chatId.hashCode()
        result = prime * result + this.createdBy.hashCode()
        result = prime * result + (if (this.forkedFromThreadId == null) 0 else this.forkedFromThreadId.hashCode())
        result = prime * result + (if (this.forkedAtMessageId == null) 0 else this.forkedAtMessageId.hashCode())
        result = prime * result + (if (this.created == null) 0 else this.created.hashCode())
        return result
    }

    override fun toString(): String {
        val sb = StringBuilder("Thread (")

        sb.append(id)
        sb.append(", ").append(chatId)
        sb.append(", ").append(createdBy)
        sb.append(", ").append(forkedFromThreadId)
        sb.append(", ").append(forkedAtMessageId)
        sb.append(", ").append(created)

        sb.append(")")
        return sb.toString()
    }
}
