/*
 * This file is generated by jOOQ.
 */
package io.heapy.tgpt.database.tables.pojos


import io.heapy.tgpt.database.enums.ContentType
import io.heapy.tgpt.database.enums.MessageRole
import io.heapy.tgpt.database.tables.interfaces.IThreadMessage

import java.time.LocalDateTime


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
data class ThreadMessage(
    override val id: Long? = null,
    override val threadId: Long,
    override val role: MessageRole,
    override val contentType: ContentType? = null,
    override val content: String,
    override val telegramMessageId: Int? = null,
    override val telegramUserId: Long? = null,
    override val created: LocalDateTime? = null
): IThreadMessage {

    override fun equals(other: Any?): Boolean {
        if (this === other)
            return true
        if (other == null)
            return false
        if (this::class != other::class)
            return false
        val o: ThreadMessage = other as ThreadMessage
        if (this.id == null) {
            if (o.id != null)
                return false
        }
        else if (this.id != o.id)
            return false
        if (this.threadId != o.threadId)
            return false
        if (this.role != o.role)
            return false
        if (this.contentType == null) {
            if (o.contentType != null)
                return false
        }
        else if (this.contentType != o.contentType)
            return false
        if (this.content != o.content)
            return false
        if (this.telegramMessageId == null) {
            if (o.telegramMessageId != null)
                return false
        }
        else if (this.telegramMessageId != o.telegramMessageId)
            return false
        if (this.telegramUserId == null) {
            if (o.telegramUserId != null)
                return false
        }
        else if (this.telegramUserId != o.telegramUserId)
            return false
        if (this.created == null) {
            if (o.created != null)
                return false
        }
        else if (this.created != o.created)
            return false
        return true
    }

    override fun hashCode(): Int {
        val prime = 31
        var result = 1
        result = prime * result + (if (this.id == null) 0 else this.id.hashCode())
        result = prime * result + this.threadId.hashCode()
        result = prime * result + this.role.hashCode()
        result = prime * result + (if (this.contentType == null) 0 else this.contentType.hashCode())
        result = prime * result + this.content.hashCode()
        result = prime * result + (if (this.telegramMessageId == null) 0 else this.telegramMessageId.hashCode())
        result = prime * result + (if (this.telegramUserId == null) 0 else this.telegramUserId.hashCode())
        result = prime * result + (if (this.created == null) 0 else this.created.hashCode())
        return result
    }

    override fun toString(): String {
        val sb = StringBuilder("ThreadMessage (")

        sb.append(id)
        sb.append(", ").append(threadId)
        sb.append(", ").append(role)
        sb.append(", ").append(contentType)
        sb.append(", ").append(content)
        sb.append(", ").append(telegramMessageId)
        sb.append(", ").append(telegramUserId)
        sb.append(", ").append(created)

        sb.append(")")
        return sb.toString()
    }
}
