CREATE TYPE JOB_EXECUTION_STATUS AS ENUM ('RUNNING', 'COMPLETED', 'FAILED');

CREATE TABLE JOB_EXECUTION (
    id BIGSERIAL PRIMARY KEY,
    job_name VARCHAR(100) NOT NULL,
    started TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    finished TIMESTAMP,
    status JOB_EXECUTION_STATUS NOT NULL DEFAULT 'RUNNING'
);

CREATE INDEX JOB_EXECUTION_NAME_IDX ON JOB_EXECUTION (job_name, started);
