ALTER TYPE JOIN_SESSION_STATUS ADD VALUE 'AWAITING_APPEAL';
ALTER TYPE JOIN_SESSION_STATUS ADD VALUE 'APPEAL_PENDING';

ALTER TABLE JOIN_SESSION ADD COLUMN appeal_text    TEXT NULL;
ALTER TABLE JOIN_SESSION ADD COLUMN cas_offenses   INT NULL;
ALTER TABLE JOIN_SESSION ADD COLUMN cas_time_added TEXT NULL;
ALTER TABLE JOIN_SESSION ADD COLUMN cas_messages   JSONB NULL;
