CREATE TYPE FEED_SOURCE AS ENUM ('KOTLIN_RELEASES', 'KOTLIN_NEWS');

CREATE TABLE FEED_ITEM (
    id         BIGSERIAL PRIMARY KEY,
    source     FEED_SOURCE NOT NULL,
    item_key   TEXT NOT NULL,
    title      TEXT NOT NULL,
    url        TEXT NOT NULL,
    chat_id    BIGINT NOT NULL,
    message_id INT NOT NULL,
    posted_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE UNIQUE INDEX FEED_ITEM_SOURCE_KEY_UINDEX ON FEED_ITEM (source, item_key);
