CREATE TABLE GPT_SESSION (
    id BIGSERIAL PRIMARY KEY,
    user_id BIGINT NOT NULL,
    group_chat_id BIGINT NOT NULL,
    wait_message_id INT NOT NULL,
    preview_chat_id BIGINT,
    preview_message_id INT,
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX GPT_SESSION_PREVIEW_UINDEX ON GPT_SESSION (preview_chat_id, preview_message_id);

CREATE TABLE GPT_SESSION_MESSAGE (
    id BIGSERIAL PRIMARY KEY,
    session_id BIGINT NOT NULL REFERENCES GPT_SESSION(id),
    role VARCHAR(20) NOT NULL,
    content TEXT NOT NULL,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);