@file:Suppress("warnings")
/*
 * This file is generated by jOOQ.
 */
package io.heapy.tgpt.database.keys


import io.heapy.tgpt.database.tables.AllowedUser
import io.heapy.tgpt.database.tables.ApiCall
import io.heapy.tgpt.database.tables.Thread
import io.heapy.tgpt.database.tables.ThreadMessage
import io.heapy.tgpt.database.tables.records.AllowedUserRecord
import io.heapy.tgpt.database.tables.records.ApiCallRecord
import io.heapy.tgpt.database.tables.records.ThreadMessageRecord
import io.heapy.tgpt.database.tables.records.ThreadRecord

import org.jooq.ForeignKey
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.QOM.ForeignKeyRule



// -------------------------------------------------------------------------
// UNIQUE and PRIMARY KEY definitions
// -------------------------------------------------------------------------

val ALLOWED_USER_PKEY: UniqueKey<AllowedUserRecord> = Internal.createUniqueKey(AllowedUser.ALLOWED_USER, DSL.name("allowed_user_pkey"), arrayOf(AllowedUser.ALLOWED_USER.ID), true)
val ALLOWED_USER_TELEGRAM_ID_KEY: UniqueKey<AllowedUserRecord> = Internal.createUniqueKey(AllowedUser.ALLOWED_USER, DSL.name("allowed_user_telegram_id_key"), arrayOf(AllowedUser.ALLOWED_USER.TELEGRAM_ID), true)
val API_CALL_PKEY: UniqueKey<ApiCallRecord> = Internal.createUniqueKey(ApiCall.API_CALL, DSL.name("api_call_pkey"), arrayOf(ApiCall.API_CALL.ID), true)
val THREAD_PKEY: UniqueKey<ThreadRecord> = Internal.createUniqueKey(Thread.THREAD, DSL.name("thread_pkey"), arrayOf(Thread.THREAD.ID), true)
val THREAD_MESSAGE_PKEY: UniqueKey<ThreadMessageRecord> = Internal.createUniqueKey(ThreadMessage.THREAD_MESSAGE, DSL.name("thread_message_pkey"), arrayOf(ThreadMessage.THREAD_MESSAGE.ID), true)

// -------------------------------------------------------------------------
// FOREIGN KEY definitions
// -------------------------------------------------------------------------

val API_CALL__API_CALL_THREAD_ID_FKEY: ForeignKey<ApiCallRecord, ThreadRecord> = Internal.createForeignKey(ApiCall.API_CALL, DSL.name("api_call_thread_id_fkey"), arrayOf(ApiCall.API_CALL.THREAD_ID), io.heapy.tgpt.database.keys.THREAD_PKEY, arrayOf(Thread.THREAD.ID), true, ForeignKeyRule.NO_ACTION, ForeignKeyRule.NO_ACTION)
val THREAD__THREAD_FORKED_FROM_THREAD_ID_FKEY: ForeignKey<ThreadRecord, ThreadRecord> = Internal.createForeignKey(Thread.THREAD, DSL.name("thread_forked_from_thread_id_fkey"), arrayOf(Thread.THREAD.FORKED_FROM_THREAD_ID), io.heapy.tgpt.database.keys.THREAD_PKEY, arrayOf(Thread.THREAD.ID), true, ForeignKeyRule.NO_ACTION, ForeignKeyRule.NO_ACTION)
val THREAD_MESSAGE__THREAD_MESSAGE_THREAD_ID_FKEY: ForeignKey<ThreadMessageRecord, ThreadRecord> = Internal.createForeignKey(ThreadMessage.THREAD_MESSAGE, DSL.name("thread_message_thread_id_fkey"), arrayOf(ThreadMessage.THREAD_MESSAGE.THREAD_ID), io.heapy.tgpt.database.keys.THREAD_PKEY, arrayOf(Thread.THREAD.ID), true, ForeignKeyRule.NO_ACTION, ForeignKeyRule.NO_ACTION)
