/*
 * This file is generated by jOOQ.
 */
package io.heapy.kotbot.database.enums


import io.heapy.kotbot.database.Public

import org.jooq.Catalog
import org.jooq.EnumType
import org.jooq.Schema


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
enum class ActionType(@get:JvmName("literal") public val literal: String) : EnumType {
    WARN("WARN"),
    BAN("BAN");
    override fun getCatalog(): Catalog? = schema.catalog
    override fun getSchema(): Schema = Public.PUBLIC
    override fun getName(): String = "action_type"
    override fun getLiteral(): String = literal
}
