/*
 * This file is generated by jOOQ.
 */
package io.heapy.kotbot.database.enums


import io.heapy.kotbot.database.Public

import org.jooq.Catalog
import org.jooq.EnumType
import org.jooq.Schema


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
enum class FeedSource(@get:JvmName("literal") public val literal: String) : EnumType {
    KOTLIN_RELEASES("KOTLIN_RELEASES"),
    KOTLIN_NEWS("KOTLIN_NEWS");
    override fun getCatalog(): Catalog? = schema.catalog
    override fun getSchema(): Schema = Public.PUBLIC
    override fun getName(): String = "feed_source"
    override fun getLiteral(): String = literal
}
