/*
 * This file is generated by jOOQ.
 */
package io.heapy.kotbot.database.enums


import io.heapy.kotbot.database.Public

import org.jooq.Catalog
import org.jooq.EnumType
import org.jooq.Schema


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
enum class JobExecutionStatus(@get:JvmName("literal") public val literal: String) : EnumType {
    RUNNING("RUNNING"),
    COMPLETED("COMPLETED"),
    FAILED("FAILED");
    override fun getCatalog(): Catalog? = schema.catalog
    override fun getSchema(): Schema = Public.PUBLIC
    override fun getName(): String = "job_execution_status"
    override fun getLiteral(): String = literal
}
