/*
 * This file is generated by jOOQ.
 */
package io.heapy.kotbot.database.enums


import io.heapy.kotbot.database.Public

import org.jooq.Catalog
import org.jooq.EnumType
import org.jooq.Schema


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
enum class JoinSessionStatus(@get:JvmName("literal") public val literal: String) : EnumType {
    ACTIVE("ACTIVE"),
    PASSED("PASSED"),
    FAILED("FAILED"),
    EXPIRED("EXPIRED");
    override fun getCatalog(): Catalog? = schema.catalog
    override fun getSchema(): Schema = Public.PUBLIC
    override fun getName(): String = "join_session_status"
    override fun getLiteral(): String = literal
}
