/*
 * This file is generated by jOOQ.
 */
package io.heapy.kotbot.database.enums


import io.heapy.kotbot.database.Public

import org.jooq.Catalog
import org.jooq.EnumType
import org.jooq.Schema


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
enum class MatchType(@get:JvmName("literal") public val literal: String) : EnumType {
    EXACT("EXACT"),
    CONTAINS("CONTAINS"),
    CONTAINS_WORD("CONTAINS_WORD");
    override fun getCatalog(): Catalog? = schema.catalog
    override fun getSchema(): Schema = Public.PUBLIC
    override fun getName(): String = "match_type"
    override fun getLiteral(): String = literal
}
