/*
 * This file is generated by jOOQ.
 */
package io.heapy.kotbot.database.enums


import io.heapy.kotbot.database.Public

import org.jooq.Catalog
import org.jooq.EnumType
import org.jooq.Schema


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
enum class TelegramUserStatus(@get:JvmName("literal") public val literal: String) : EnumType {
    UNAPPROVED("UNAPPROVED"),
    APPROVED("APPROVED"),
    BANNED("BANNED");
    override fun getCatalog(): Catalog? = schema.catalog
    override fun getSchema(): Schema = Public.PUBLIC
    override fun getName(): String = "telegram_user_status"
    override fun getLiteral(): String = literal
}
