/*
 * This file is generated by jOOQ.
 */
package io.heapy.kotbot.database.enums


import io.heapy.kotbot.database.Public

import org.jooq.Catalog
import org.jooq.EnumType
import org.jooq.Schema


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
enum class TelegramUserRole(@get:JvmName("literal") public val literal: String) : EnumType {
    USER("USER"),
    MODERATOR("MODERATOR"),
    ADMIN("ADMIN");
    override fun getCatalog(): Catalog? = schema.catalog
    override fun getSchema(): Schema = Public.PUBLIC
    override fun getName(): String = "telegram_user_role"
    override fun getLiteral(): String = literal
}
