/*
 * This file is generated by jOOQ.
 */
package io.heapy.kotbot.database.tables.pojos


import io.heapy.kotbot.database.tables.interfaces.IChallengeAttempt

import java.time.LocalDateTime
import java.util.UUID


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
data class ChallengeAttempt(
    override val id: Long? = null,
    override val sessionId: Long,
    override val telegramId: Long,
    override val challengeId: UUID,
    override val templateKey: String,
    override val selectedAnswer: String,
    override val correctAnswer: String,
    override val isCorrect: Boolean,
    override val challengeSentAt: LocalDateTime,
    override val answeredAt: LocalDateTime? = null,
    override val latencyMs: Long
): IChallengeAttempt {

    override fun equals(other: Any?): Boolean {
        if (this === other)
            return true
        if (other == null)
            return false
        if (this::class != other::class)
            return false
        val o: ChallengeAttempt = other as ChallengeAttempt
        if (this.id == null) {
            if (o.id != null)
                return false
        }
        else if (this.id != o.id)
            return false
        if (this.sessionId != o.sessionId)
            return false
        if (this.telegramId != o.telegramId)
            return false
        if (this.challengeId != o.challengeId)
            return false
        if (this.templateKey != o.templateKey)
            return false
        if (this.selectedAnswer != o.selectedAnswer)
            return false
        if (this.correctAnswer != o.correctAnswer)
            return false
        if (this.isCorrect != o.isCorrect)
            return false
        if (this.challengeSentAt != o.challengeSentAt)
            return false
        if (this.answeredAt == null) {
            if (o.answeredAt != null)
                return false
        }
        else if (this.answeredAt != o.answeredAt)
            return false
        if (this.latencyMs != o.latencyMs)
            return false
        return true
    }

    override fun hashCode(): Int {
        val prime = 31
        var result = 1
        result = prime * result + (if (this.id == null) 0 else this.id.hashCode())
        result = prime * result + this.sessionId.hashCode()
        result = prime * result + this.telegramId.hashCode()
        result = prime * result + this.challengeId.hashCode()
        result = prime * result + this.templateKey.hashCode()
        result = prime * result + this.selectedAnswer.hashCode()
        result = prime * result + this.correctAnswer.hashCode()
        result = prime * result + this.isCorrect.hashCode()
        result = prime * result + this.challengeSentAt.hashCode()
        result = prime * result + (if (this.answeredAt == null) 0 else this.answeredAt.hashCode())
        result = prime * result + this.latencyMs.hashCode()
        return result
    }

    override fun toString(): String {
        val sb = StringBuilder("ChallengeAttempt (")

        sb.append(id)
        sb.append(", ").append(sessionId)
        sb.append(", ").append(telegramId)
        sb.append(", ").append(challengeId)
        sb.append(", ").append(templateKey)
        sb.append(", ").append(selectedAnswer)
        sb.append(", ").append(correctAnswer)
        sb.append(", ").append(isCorrect)
        sb.append(", ").append(challengeSentAt)
        sb.append(", ").append(answeredAt)
        sb.append(", ").append(latencyMs)

        sb.append(")")
        return sb.toString()
    }
}
