/*
 * This file is generated by jOOQ.
 */
package io.heapy.kotbot.database.tables.pojos


import io.heapy.kotbot.database.enums.FeedSource
import io.heapy.kotbot.database.tables.interfaces.IFeedItem

import java.time.LocalDateTime


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
data class FeedItem(
    override val id: Long? = null,
    override val source: FeedSource,
    override val itemKey: String,
    override val title: String,
    override val url: String,
    override val chatId: Long,
    override val messageId: Int,
    override val postedAt: LocalDateTime? = null
): IFeedItem {

    override fun equals(other: Any?): Boolean {
        if (this === other)
            return true
        if (other == null)
            return false
        if (this::class != other::class)
            return false
        val o: FeedItem = other as FeedItem
        if (this.id == null) {
            if (o.id != null)
                return false
        }
        else if (this.id != o.id)
            return false
        if (this.source != o.source)
            return false
        if (this.itemKey != o.itemKey)
            return false
        if (this.title != o.title)
            return false
        if (this.url != o.url)
            return false
        if (this.chatId != o.chatId)
            return false
        if (this.messageId != o.messageId)
            return false
        if (this.postedAt == null) {
            if (o.postedAt != null)
                return false
        }
        else if (this.postedAt != o.postedAt)
            return false
        return true
    }

    override fun hashCode(): Int {
        val prime = 31
        var result = 1
        result = prime * result + (if (this.id == null) 0 else this.id.hashCode())
        result = prime * result + this.source.hashCode()
        result = prime * result + this.itemKey.hashCode()
        result = prime * result + this.title.hashCode()
        result = prime * result + this.url.hashCode()
        result = prime * result + this.chatId.hashCode()
        result = prime * result + this.messageId.hashCode()
        result = prime * result + (if (this.postedAt == null) 0 else this.postedAt.hashCode())
        return result
    }

    override fun toString(): String {
        val sb = StringBuilder("FeedItem (")

        sb.append(id)
        sb.append(", ").append(source)
        sb.append(", ").append(itemKey)
        sb.append(", ").append(title)
        sb.append(", ").append(url)
        sb.append(", ").append(chatId)
        sb.append(", ").append(messageId)
        sb.append(", ").append(postedAt)

        sb.append(")")
        return sb.toString()
    }
}
