/*
 * This file is generated by jOOQ.
 */
package io.heapy.kotbot.database.tables.pojos


import io.heapy.kotbot.database.tables.interfaces.IGptSessionMessage

import java.time.LocalDateTime


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
data class GptSessionMessage(
    override val id: Long? = null,
    override val sessionId: Long,
    override val role: String,
    override val content: String,
    override val created: LocalDateTime? = null
): IGptSessionMessage {

    override fun equals(other: Any?): Boolean {
        if (this === other)
            return true
        if (other == null)
            return false
        if (this::class != other::class)
            return false
        val o: GptSessionMessage = other as GptSessionMessage
        if (this.id == null) {
            if (o.id != null)
                return false
        }
        else if (this.id != o.id)
            return false
        if (this.sessionId != o.sessionId)
            return false
        if (this.role != o.role)
            return false
        if (this.content != o.content)
            return false
        if (this.created == null) {
            if (o.created != null)
                return false
        }
        else if (this.created != o.created)
            return false
        return true
    }

    override fun hashCode(): Int {
        val prime = 31
        var result = 1
        result = prime * result + (if (this.id == null) 0 else this.id.hashCode())
        result = prime * result + this.sessionId.hashCode()
        result = prime * result + this.role.hashCode()
        result = prime * result + this.content.hashCode()
        result = prime * result + (if (this.created == null) 0 else this.created.hashCode())
        return result
    }

    override fun toString(): String {
        val sb = StringBuilder("GptSessionMessage (")

        sb.append(id)
        sb.append(", ").append(sessionId)
        sb.append(", ").append(role)
        sb.append(", ").append(content)
        sb.append(", ").append(created)

        sb.append(")")
        return sb.toString()
    }
}
