/*
 * This file is generated by jOOQ.
 */
package io.heapy.kotbot.database.tables.pojos


import io.heapy.kotbot.database.tables.interfaces.IGptSession

import java.time.LocalDateTime


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
data class GptSession(
    override val id: Long? = null,
    override val userId: Long,
    override val groupChatId: Long,
    override val waitMessageId: Int,
    override val previewChatId: Long? = null,
    override val previewMessageId: Int? = null,
    override val status: String? = null,
    override val created: LocalDateTime? = null
): IGptSession {

    override fun equals(other: Any?): Boolean {
        if (this === other)
            return true
        if (other == null)
            return false
        if (this::class != other::class)
            return false
        val o: GptSession = other as GptSession
        if (this.id == null) {
            if (o.id != null)
                return false
        }
        else if (this.id != o.id)
            return false
        if (this.userId != o.userId)
            return false
        if (this.groupChatId != o.groupChatId)
            return false
        if (this.waitMessageId != o.waitMessageId)
            return false
        if (this.previewChatId == null) {
            if (o.previewChatId != null)
                return false
        }
        else if (this.previewChatId != o.previewChatId)
            return false
        if (this.previewMessageId == null) {
            if (o.previewMessageId != null)
                return false
        }
        else if (this.previewMessageId != o.previewMessageId)
            return false
        if (this.status == null) {
            if (o.status != null)
                return false
        }
        else if (this.status != o.status)
            return false
        if (this.created == null) {
            if (o.created != null)
                return false
        }
        else if (this.created != o.created)
            return false
        return true
    }

    override fun hashCode(): Int {
        val prime = 31
        var result = 1
        result = prime * result + (if (this.id == null) 0 else this.id.hashCode())
        result = prime * result + this.userId.hashCode()
        result = prime * result + this.groupChatId.hashCode()
        result = prime * result + this.waitMessageId.hashCode()
        result = prime * result + (if (this.previewChatId == null) 0 else this.previewChatId.hashCode())
        result = prime * result + (if (this.previewMessageId == null) 0 else this.previewMessageId.hashCode())
        result = prime * result + (if (this.status == null) 0 else this.status.hashCode())
        result = prime * result + (if (this.created == null) 0 else this.created.hashCode())
        return result
    }

    override fun toString(): String {
        val sb = StringBuilder("GptSession (")

        sb.append(id)
        sb.append(", ").append(userId)
        sb.append(", ").append(groupChatId)
        sb.append(", ").append(waitMessageId)
        sb.append(", ").append(previewChatId)
        sb.append(", ").append(previewMessageId)
        sb.append(", ").append(status)
        sb.append(", ").append(created)

        sb.append(")")
        return sb.toString()
    }
}
