/*
 * This file is generated by jOOQ.
 */
package io.heapy.kotbot.database.tables.pojos


import io.heapy.kotbot.database.enums.JobExecutionStatus
import io.heapy.kotbot.database.tables.interfaces.IJobExecution

import java.time.LocalDateTime


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
data class JobExecution(
    override val id: Long? = null,
    override val jobName: String,
    override val started: LocalDateTime? = null,
    override val finished: LocalDateTime? = null,
    override val status: JobExecutionStatus? = null
): IJobExecution {

    override fun equals(other: Any?): Boolean {
        if (this === other)
            return true
        if (other == null)
            return false
        if (this::class != other::class)
            return false
        val o: JobExecution = other as JobExecution
        if (this.id == null) {
            if (o.id != null)
                return false
        }
        else if (this.id != o.id)
            return false
        if (this.jobName != o.jobName)
            return false
        if (this.started == null) {
            if (o.started != null)
                return false
        }
        else if (this.started != o.started)
            return false
        if (this.finished == null) {
            if (o.finished != null)
                return false
        }
        else if (this.finished != o.finished)
            return false
        if (this.status == null) {
            if (o.status != null)
                return false
        }
        else if (this.status != o.status)
            return false
        return true
    }

    override fun hashCode(): Int {
        val prime = 31
        var result = 1
        result = prime * result + (if (this.id == null) 0 else this.id.hashCode())
        result = prime * result + this.jobName.hashCode()
        result = prime * result + (if (this.started == null) 0 else this.started.hashCode())
        result = prime * result + (if (this.finished == null) 0 else this.finished.hashCode())
        result = prime * result + (if (this.status == null) 0 else this.status.hashCode())
        return result
    }

    override fun toString(): String {
        val sb = StringBuilder("JobExecution (")

        sb.append(id)
        sb.append(", ").append(jobName)
        sb.append(", ").append(started)
        sb.append(", ").append(finished)
        sb.append(", ").append(status)

        sb.append(")")
        return sb.toString()
    }
}
