/*
 * This file is generated by jOOQ.
 */
package io.heapy.kotbot.database.tables.pojos


import io.heapy.kotbot.database.enums.JoinSessionStatus
import io.heapy.kotbot.database.tables.interfaces.IJoinSession

import java.time.LocalDateTime
import java.util.UUID

import org.jooq.JSONB


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
data class JoinSession(
    override val id: Long? = null,
    override val telegramId: Long,
    override val chatId: Long,
    override val userChatId: Long,
    override val status: JoinSessionStatus? = null,
    override val maxAttempts: Int,
    override val attemptsUsed: Int? = null,
    override val expiresAt: LocalDateTime,
    override val createdAt: LocalDateTime? = null,
    override val finishedAt: LocalDateTime? = null,
    override val challengeId: UUID? = null,
    override val templateKey: String? = null,
    override val seed: Long? = null,
    override val snippet: String? = null,
    override val correctAnswer: String? = null,
    override val options: JSONB? = null,
    override val challengeSentAt: LocalDateTime? = null,
    override val messageId: Int? = null
): IJoinSession {

    override fun equals(other: Any?): Boolean {
        if (this === other)
            return true
        if (other == null)
            return false
        if (this::class != other::class)
            return false
        val o: JoinSession = other as JoinSession
        if (this.id == null) {
            if (o.id != null)
                return false
        }
        else if (this.id != o.id)
            return false
        if (this.telegramId != o.telegramId)
            return false
        if (this.chatId != o.chatId)
            return false
        if (this.userChatId != o.userChatId)
            return false
        if (this.status == null) {
            if (o.status != null)
                return false
        }
        else if (this.status != o.status)
            return false
        if (this.maxAttempts != o.maxAttempts)
            return false
        if (this.attemptsUsed == null) {
            if (o.attemptsUsed != null)
                return false
        }
        else if (this.attemptsUsed != o.attemptsUsed)
            return false
        if (this.expiresAt != o.expiresAt)
            return false
        if (this.createdAt == null) {
            if (o.createdAt != null)
                return false
        }
        else if (this.createdAt != o.createdAt)
            return false
        if (this.finishedAt == null) {
            if (o.finishedAt != null)
                return false
        }
        else if (this.finishedAt != o.finishedAt)
            return false
        if (this.challengeId == null) {
            if (o.challengeId != null)
                return false
        }
        else if (this.challengeId != o.challengeId)
            return false
        if (this.templateKey == null) {
            if (o.templateKey != null)
                return false
        }
        else if (this.templateKey != o.templateKey)
            return false
        if (this.seed == null) {
            if (o.seed != null)
                return false
        }
        else if (this.seed != o.seed)
            return false
        if (this.snippet == null) {
            if (o.snippet != null)
                return false
        }
        else if (this.snippet != o.snippet)
            return false
        if (this.correctAnswer == null) {
            if (o.correctAnswer != null)
                return false
        }
        else if (this.correctAnswer != o.correctAnswer)
            return false
        if (this.options == null) {
            if (o.options != null)
                return false
        }
        else if (this.options != o.options)
            return false
        if (this.challengeSentAt == null) {
            if (o.challengeSentAt != null)
                return false
        }
        else if (this.challengeSentAt != o.challengeSentAt)
            return false
        if (this.messageId == null) {
            if (o.messageId != null)
                return false
        }
        else if (this.messageId != o.messageId)
            return false
        return true
    }

    override fun hashCode(): Int {
        val prime = 31
        var result = 1
        result = prime * result + (if (this.id == null) 0 else this.id.hashCode())
        result = prime * result + this.telegramId.hashCode()
        result = prime * result + this.chatId.hashCode()
        result = prime * result + this.userChatId.hashCode()
        result = prime * result + (if (this.status == null) 0 else this.status.hashCode())
        result = prime * result + this.maxAttempts.hashCode()
        result = prime * result + (if (this.attemptsUsed == null) 0 else this.attemptsUsed.hashCode())
        result = prime * result + this.expiresAt.hashCode()
        result = prime * result + (if (this.createdAt == null) 0 else this.createdAt.hashCode())
        result = prime * result + (if (this.finishedAt == null) 0 else this.finishedAt.hashCode())
        result = prime * result + (if (this.challengeId == null) 0 else this.challengeId.hashCode())
        result = prime * result + (if (this.templateKey == null) 0 else this.templateKey.hashCode())
        result = prime * result + (if (this.seed == null) 0 else this.seed.hashCode())
        result = prime * result + (if (this.snippet == null) 0 else this.snippet.hashCode())
        result = prime * result + (if (this.correctAnswer == null) 0 else this.correctAnswer.hashCode())
        result = prime * result + (if (this.options == null) 0 else this.options.hashCode())
        result = prime * result + (if (this.challengeSentAt == null) 0 else this.challengeSentAt.hashCode())
        result = prime * result + (if (this.messageId == null) 0 else this.messageId.hashCode())
        return result
    }

    override fun toString(): String {
        val sb = StringBuilder("JoinSession (")

        sb.append(id)
        sb.append(", ").append(telegramId)
        sb.append(", ").append(chatId)
        sb.append(", ").append(userChatId)
        sb.append(", ").append(status)
        sb.append(", ").append(maxAttempts)
        sb.append(", ").append(attemptsUsed)
        sb.append(", ").append(expiresAt)
        sb.append(", ").append(createdAt)
        sb.append(", ").append(finishedAt)
        sb.append(", ").append(challengeId)
        sb.append(", ").append(templateKey)
        sb.append(", ").append(seed)
        sb.append(", ").append(snippet)
        sb.append(", ").append(correctAnswer)
        sb.append(", ").append(options)
        sb.append(", ").append(challengeSentAt)
        sb.append(", ").append(messageId)

        sb.append(")")
        return sb.toString()
    }
}
