/*
 * This file is generated by jOOQ.
 */
package io.heapy.kotbot.database.tables.pojos


import io.heapy.kotbot.database.tables.interfaces.IUpdateRaw

import java.time.LocalDateTime

import org.jooq.JSONB


/**
 * This class is generated by jOOQ.
 */
@Suppress("UNCHECKED_CAST")
data class UpdateRaw(
    override val id: Long? = null,
    override val created: LocalDateTime,
    override val update: JSONB
): IUpdateRaw {

    override fun equals(other: Any?): Boolean {
        if (this === other)
            return true
        if (other == null)
            return false
        if (this::class != other::class)
            return false
        val o: UpdateRaw = other as UpdateRaw
        if (this.id == null) {
            if (o.id != null)
                return false
        }
        else if (this.id != o.id)
            return false
        if (this.created != o.created)
            return false
        if (this.update != o.update)
            return false
        return true
    }

    override fun hashCode(): Int {
        val prime = 31
        var result = 1
        result = prime * result + (if (this.id == null) 0 else this.id.hashCode())
        result = prime * result + this.created.hashCode()
        result = prime * result + this.update.hashCode()
        return result
    }

    override fun toString(): String {
        val sb = StringBuilder("UpdateRaw (")

        sb.append(id)
        sb.append(", ").append(created)
        sb.append(", ").append(update)

        sb.append(")")
        return sb.toString()
    }
}
