/*
 * This file is generated by jOOQ.
 */
package io.heapy.kotbot.database.tables.pojos


import io.heapy.kotbot.database.enums.VerificationSource
import io.heapy.kotbot.database.tables.interfaces.IVerifiedUser

import java.time.LocalDateTime


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
data class VerifiedUser(
    override val id: Long? = null,
    override val telegramId: Long,
    override val source: VerificationSource,
    override val verifiedAt: LocalDateTime? = null,
    override val sessionId: Long? = null
): IVerifiedUser {

    override fun equals(other: Any?): Boolean {
        if (this === other)
            return true
        if (other == null)
            return false
        if (this::class != other::class)
            return false
        val o: VerifiedUser = other as VerifiedUser
        if (this.id == null) {
            if (o.id != null)
                return false
        }
        else if (this.id != o.id)
            return false
        if (this.telegramId != o.telegramId)
            return false
        if (this.source != o.source)
            return false
        if (this.verifiedAt == null) {
            if (o.verifiedAt != null)
                return false
        }
        else if (this.verifiedAt != o.verifiedAt)
            return false
        if (this.sessionId == null) {
            if (o.sessionId != null)
                return false
        }
        else if (this.sessionId != o.sessionId)
            return false
        return true
    }

    override fun hashCode(): Int {
        val prime = 31
        var result = 1
        result = prime * result + (if (this.id == null) 0 else this.id.hashCode())
        result = prime * result + this.telegramId.hashCode()
        result = prime * result + this.source.hashCode()
        result = prime * result + (if (this.verifiedAt == null) 0 else this.verifiedAt.hashCode())
        result = prime * result + (if (this.sessionId == null) 0 else this.sessionId.hashCode())
        return result
    }

    override fun toString(): String {
        val sb = StringBuilder("VerifiedUser (")

        sb.append(id)
        sb.append(", ").append(telegramId)
        sb.append(", ").append(source)
        sb.append(", ").append(verifiedAt)
        sb.append(", ").append(sessionId)

        sb.append(")")
        return sb.toString()
    }
}
