/*
 * This file is generated by jOOQ.
 */
package io.heapy.tgpt.database


import io.heapy.tgpt.database.tables.AllowedUser
import io.heapy.tgpt.database.tables.ApiCall
import io.heapy.tgpt.database.tables.Thread
import io.heapy.tgpt.database.tables.ThreadMessage

import kotlin.collections.List

import org.jooq.Catalog
import org.jooq.Table
import org.jooq.impl.DSL
import org.jooq.impl.SchemaImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class Public : SchemaImpl(DSL.name("public"), DefaultCatalog.DEFAULT_CATALOG, DSL.comment("")) {
    companion object {

        /**
         * The reference instance of <code>public</code>
         */
        val PUBLIC: Public = Public()
    }

    /**
     * The table <code>public.allowed_user</code>.
     */
    val ALLOWED_USER: AllowedUser get() = AllowedUser.ALLOWED_USER

    /**
     * The table <code>public.api_call</code>.
     */
    val API_CALL: ApiCall get() = ApiCall.API_CALL

    /**
     * The table <code>public.thread</code>.
     */
    val THREAD: Thread get() = Thread.THREAD

    /**
     * The table <code>public.thread_message</code>.
     */
    val THREAD_MESSAGE: ThreadMessage get() = ThreadMessage.THREAD_MESSAGE

    override fun getCatalog(): Catalog = DefaultCatalog.DEFAULT_CATALOG

    override fun getTables(): List<Table<*>> = listOf(
        AllowedUser.ALLOWED_USER,
        ApiCall.API_CALL,
        Thread.THREAD,
        ThreadMessage.THREAD_MESSAGE
    )
}
