/*
 * This file is generated by jOOQ.
 */
package io.heapy.tgpt.database.tables.daos


import io.heapy.tgpt.database.tables.AllowedUser
import io.heapy.tgpt.database.tables.records.AllowedUserRecord

import java.time.LocalDateTime

import kotlin.collections.List

import org.jooq.Configuration
import org.jooq.impl.DAOImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class AllowedUserDao(configuration: Configuration?) : DAOImpl<AllowedUserRecord, io.heapy.tgpt.database.tables.pojos.AllowedUser, Long>(AllowedUser.ALLOWED_USER, io.heapy.tgpt.database.tables.pojos.AllowedUser::class.java, configuration) {

    /**
     * Create a new AllowedUserDao without any configuration
     */
    constructor(): this(null)

    override fun getId(o: io.heapy.tgpt.database.tables.pojos.AllowedUser): Long? = o.id

    /**
     * Fetch records that have <code>id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    fun fetchRangeOfId(lowerInclusive: Long?, upperInclusive: Long?): List<io.heapy.tgpt.database.tables.pojos.AllowedUser> = fetchRange(AllowedUser.ALLOWED_USER.ID, lowerInclusive, upperInclusive)

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    fun fetchById(vararg values: Long): List<io.heapy.tgpt.database.tables.pojos.AllowedUser> = fetch(AllowedUser.ALLOWED_USER.ID, *values.toTypedArray())

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    fun fetchOneById(value: Long): io.heapy.tgpt.database.tables.pojos.AllowedUser? = fetchOne(AllowedUser.ALLOWED_USER.ID, value)

    /**
     * Fetch records that have <code>telegram_id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    fun fetchRangeOfTelegramId(lowerInclusive: Long, upperInclusive: Long): List<io.heapy.tgpt.database.tables.pojos.AllowedUser> = fetchRange(AllowedUser.ALLOWED_USER.TELEGRAM_ID, lowerInclusive, upperInclusive)

    /**
     * Fetch records that have <code>telegram_id IN (values)</code>
     */
    fun fetchByTelegramId(vararg values: Long): List<io.heapy.tgpt.database.tables.pojos.AllowedUser> = fetch(AllowedUser.ALLOWED_USER.TELEGRAM_ID, *values.toTypedArray())

    /**
     * Fetch a unique record that has <code>telegram_id = value</code>
     */
    fun fetchOneByTelegramId(value: Long): io.heapy.tgpt.database.tables.pojos.AllowedUser? = fetchOne(AllowedUser.ALLOWED_USER.TELEGRAM_ID, value)

    /**
     * Fetch records that have <code>username BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    fun fetchRangeOfUsername(lowerInclusive: String?, upperInclusive: String?): List<io.heapy.tgpt.database.tables.pojos.AllowedUser> = fetchRange(AllowedUser.ALLOWED_USER.USERNAME, lowerInclusive, upperInclusive)

    /**
     * Fetch records that have <code>username IN (values)</code>
     */
    fun fetchByUsername(vararg values: String): List<io.heapy.tgpt.database.tables.pojos.AllowedUser> = fetch(AllowedUser.ALLOWED_USER.USERNAME, *values)

    /**
     * Fetch records that have <code>display_name BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    fun fetchRangeOfDisplayName(lowerInclusive: String?, upperInclusive: String?): List<io.heapy.tgpt.database.tables.pojos.AllowedUser> = fetchRange(AllowedUser.ALLOWED_USER.DISPLAY_NAME, lowerInclusive, upperInclusive)

    /**
     * Fetch records that have <code>display_name IN (values)</code>
     */
    fun fetchByDisplayName(vararg values: String): List<io.heapy.tgpt.database.tables.pojos.AllowedUser> = fetch(AllowedUser.ALLOWED_USER.DISPLAY_NAME, *values)

    /**
     * Fetch records that have <code>is_active BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    fun fetchRangeOfIsActive(lowerInclusive: Boolean?, upperInclusive: Boolean?): List<io.heapy.tgpt.database.tables.pojos.AllowedUser> = fetchRange(AllowedUser.ALLOWED_USER.IS_ACTIVE, lowerInclusive, upperInclusive)

    /**
     * Fetch records that have <code>is_active IN (values)</code>
     */
    fun fetchByIsActive(vararg values: Boolean): List<io.heapy.tgpt.database.tables.pojos.AllowedUser> = fetch(AllowedUser.ALLOWED_USER.IS_ACTIVE, *values.toTypedArray())

    /**
     * Fetch records that have <code>created BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    fun fetchRangeOfCreated(lowerInclusive: LocalDateTime?, upperInclusive: LocalDateTime?): List<io.heapy.tgpt.database.tables.pojos.AllowedUser> = fetchRange(AllowedUser.ALLOWED_USER.CREATED, lowerInclusive, upperInclusive)

    /**
     * Fetch records that have <code>created IN (values)</code>
     */
    fun fetchByCreated(vararg values: LocalDateTime): List<io.heapy.tgpt.database.tables.pojos.AllowedUser> = fetch(AllowedUser.ALLOWED_USER.CREATED, *values)
}
