/*
 * This file is generated by jOOQ.
 */
package io.heapy.tgpt.database.tables.daos


import io.heapy.tgpt.database.tables.ApiCall
import io.heapy.tgpt.database.tables.records.ApiCallRecord

import java.math.BigDecimal
import java.time.LocalDateTime

import kotlin.collections.List

import org.jooq.Configuration
import org.jooq.impl.DAOImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class ApiCallDao(configuration: Configuration?) : DAOImpl<ApiCallRecord, io.heapy.tgpt.database.tables.pojos.ApiCall, Long>(ApiCall.API_CALL, io.heapy.tgpt.database.tables.pojos.ApiCall::class.java, configuration) {

    /**
     * Create a new ApiCallDao without any configuration
     */
    constructor(): this(null)

    override fun getId(o: io.heapy.tgpt.database.tables.pojos.ApiCall): Long? = o.id

    /**
     * Fetch records that have <code>id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    fun fetchRangeOfId(lowerInclusive: Long?, upperInclusive: Long?): List<io.heapy.tgpt.database.tables.pojos.ApiCall> = fetchRange(ApiCall.API_CALL.ID, lowerInclusive, upperInclusive)

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    fun fetchById(vararg values: Long): List<io.heapy.tgpt.database.tables.pojos.ApiCall> = fetch(ApiCall.API_CALL.ID, *values.toTypedArray())

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    fun fetchOneById(value: Long): io.heapy.tgpt.database.tables.pojos.ApiCall? = fetchOne(ApiCall.API_CALL.ID, value)

    /**
     * Fetch records that have <code>thread_id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    fun fetchRangeOfThreadId(lowerInclusive: Long, upperInclusive: Long): List<io.heapy.tgpt.database.tables.pojos.ApiCall> = fetchRange(ApiCall.API_CALL.THREAD_ID, lowerInclusive, upperInclusive)

    /**
     * Fetch records that have <code>thread_id IN (values)</code>
     */
    fun fetchByThreadId(vararg values: Long): List<io.heapy.tgpt.database.tables.pojos.ApiCall> = fetch(ApiCall.API_CALL.THREAD_ID, *values.toTypedArray())

    /**
     * Fetch records that have <code>telegram_user_id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    fun fetchRangeOfTelegramUserId(lowerInclusive: Long, upperInclusive: Long): List<io.heapy.tgpt.database.tables.pojos.ApiCall> = fetchRange(ApiCall.API_CALL.TELEGRAM_USER_ID, lowerInclusive, upperInclusive)

    /**
     * Fetch records that have <code>telegram_user_id IN (values)</code>
     */
    fun fetchByTelegramUserId(vararg values: Long): List<io.heapy.tgpt.database.tables.pojos.ApiCall> = fetch(ApiCall.API_CALL.TELEGRAM_USER_ID, *values.toTypedArray())

    /**
     * Fetch records that have <code>model BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    fun fetchRangeOfModel(lowerInclusive: String, upperInclusive: String): List<io.heapy.tgpt.database.tables.pojos.ApiCall> = fetchRange(ApiCall.API_CALL.MODEL, lowerInclusive, upperInclusive)

    /**
     * Fetch records that have <code>model IN (values)</code>
     */
    fun fetchByModel(vararg values: String): List<io.heapy.tgpt.database.tables.pojos.ApiCall> = fetch(ApiCall.API_CALL.MODEL, *values)

    /**
     * Fetch records that have <code>prompt_tokens BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    fun fetchRangeOfPromptTokens(lowerInclusive: Int, upperInclusive: Int): List<io.heapy.tgpt.database.tables.pojos.ApiCall> = fetchRange(ApiCall.API_CALL.PROMPT_TOKENS, lowerInclusive, upperInclusive)

    /**
     * Fetch records that have <code>prompt_tokens IN (values)</code>
     */
    fun fetchByPromptTokens(vararg values: Int): List<io.heapy.tgpt.database.tables.pojos.ApiCall> = fetch(ApiCall.API_CALL.PROMPT_TOKENS, *values.toTypedArray())

    /**
     * Fetch records that have <code>completion_tokens BETWEEN lowerInclusive
     * AND upperInclusive</code>
     */
    fun fetchRangeOfCompletionTokens(lowerInclusive: Int, upperInclusive: Int): List<io.heapy.tgpt.database.tables.pojos.ApiCall> = fetchRange(ApiCall.API_CALL.COMPLETION_TOKENS, lowerInclusive, upperInclusive)

    /**
     * Fetch records that have <code>completion_tokens IN (values)</code>
     */
    fun fetchByCompletionTokens(vararg values: Int): List<io.heapy.tgpt.database.tables.pojos.ApiCall> = fetch(ApiCall.API_CALL.COMPLETION_TOKENS, *values.toTypedArray())

    /**
     * Fetch records that have <code>total_tokens BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    fun fetchRangeOfTotalTokens(lowerInclusive: Int, upperInclusive: Int): List<io.heapy.tgpt.database.tables.pojos.ApiCall> = fetchRange(ApiCall.API_CALL.TOTAL_TOKENS, lowerInclusive, upperInclusive)

    /**
     * Fetch records that have <code>total_tokens IN (values)</code>
     */
    fun fetchByTotalTokens(vararg values: Int): List<io.heapy.tgpt.database.tables.pojos.ApiCall> = fetch(ApiCall.API_CALL.TOTAL_TOKENS, *values.toTypedArray())

    /**
     * Fetch records that have <code>estimated_cost_usd BETWEEN lowerInclusive
     * AND upperInclusive</code>
     */
    fun fetchRangeOfEstimatedCostUsd(lowerInclusive: BigDecimal, upperInclusive: BigDecimal): List<io.heapy.tgpt.database.tables.pojos.ApiCall> = fetchRange(ApiCall.API_CALL.ESTIMATED_COST_USD, lowerInclusive, upperInclusive)

    /**
     * Fetch records that have <code>estimated_cost_usd IN (values)</code>
     */
    fun fetchByEstimatedCostUsd(vararg values: BigDecimal): List<io.heapy.tgpt.database.tables.pojos.ApiCall> = fetch(ApiCall.API_CALL.ESTIMATED_COST_USD, *values)

    /**
     * Fetch records that have <code>created BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    fun fetchRangeOfCreated(lowerInclusive: LocalDateTime?, upperInclusive: LocalDateTime?): List<io.heapy.tgpt.database.tables.pojos.ApiCall> = fetchRange(ApiCall.API_CALL.CREATED, lowerInclusive, upperInclusive)

    /**
     * Fetch records that have <code>created IN (values)</code>
     */
    fun fetchByCreated(vararg values: LocalDateTime): List<io.heapy.tgpt.database.tables.pojos.ApiCall> = fetch(ApiCall.API_CALL.CREATED, *values)
}
