/*
 * This file is generated by jOOQ.
 */
package io.heapy.tgpt.database.tables.daos


import io.heapy.tgpt.database.enums.ContentType
import io.heapy.tgpt.database.enums.MessageRole
import io.heapy.tgpt.database.tables.ThreadMessage
import io.heapy.tgpt.database.tables.records.ThreadMessageRecord

import java.time.LocalDateTime

import kotlin.collections.List

import org.jooq.Configuration
import org.jooq.impl.DAOImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class ThreadMessageDao(configuration: Configuration?) : DAOImpl<ThreadMessageRecord, io.heapy.tgpt.database.tables.pojos.ThreadMessage, Long>(ThreadMessage.THREAD_MESSAGE, io.heapy.tgpt.database.tables.pojos.ThreadMessage::class.java, configuration) {

    /**
     * Create a new ThreadMessageDao without any configuration
     */
    constructor(): this(null)

    override fun getId(o: io.heapy.tgpt.database.tables.pojos.ThreadMessage): Long? = o.id

    /**
     * Fetch records that have <code>id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    fun fetchRangeOfId(lowerInclusive: Long?, upperInclusive: Long?): List<io.heapy.tgpt.database.tables.pojos.ThreadMessage> = fetchRange(ThreadMessage.THREAD_MESSAGE.ID, lowerInclusive, upperInclusive)

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    fun fetchById(vararg values: Long): List<io.heapy.tgpt.database.tables.pojos.ThreadMessage> = fetch(ThreadMessage.THREAD_MESSAGE.ID, *values.toTypedArray())

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    fun fetchOneById(value: Long): io.heapy.tgpt.database.tables.pojos.ThreadMessage? = fetchOne(ThreadMessage.THREAD_MESSAGE.ID, value)

    /**
     * Fetch records that have <code>thread_id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    fun fetchRangeOfThreadId(lowerInclusive: Long, upperInclusive: Long): List<io.heapy.tgpt.database.tables.pojos.ThreadMessage> = fetchRange(ThreadMessage.THREAD_MESSAGE.THREAD_ID, lowerInclusive, upperInclusive)

    /**
     * Fetch records that have <code>thread_id IN (values)</code>
     */
    fun fetchByThreadId(vararg values: Long): List<io.heapy.tgpt.database.tables.pojos.ThreadMessage> = fetch(ThreadMessage.THREAD_MESSAGE.THREAD_ID, *values.toTypedArray())

    /**
     * Fetch records that have <code>role BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    fun fetchRangeOfRole(lowerInclusive: MessageRole, upperInclusive: MessageRole): List<io.heapy.tgpt.database.tables.pojos.ThreadMessage> = fetchRange(ThreadMessage.THREAD_MESSAGE.ROLE, lowerInclusive, upperInclusive)

    /**
     * Fetch records that have <code>role IN (values)</code>
     */
    fun fetchByRole(vararg values: MessageRole): List<io.heapy.tgpt.database.tables.pojos.ThreadMessage> = fetch(ThreadMessage.THREAD_MESSAGE.ROLE, *values)

    /**
     * Fetch records that have <code>content_type BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    fun fetchRangeOfContentType(lowerInclusive: ContentType?, upperInclusive: ContentType?): List<io.heapy.tgpt.database.tables.pojos.ThreadMessage> = fetchRange(ThreadMessage.THREAD_MESSAGE.CONTENT_TYPE, lowerInclusive, upperInclusive)

    /**
     * Fetch records that have <code>content_type IN (values)</code>
     */
    fun fetchByContentType(vararg values: ContentType): List<io.heapy.tgpt.database.tables.pojos.ThreadMessage> = fetch(ThreadMessage.THREAD_MESSAGE.CONTENT_TYPE, *values)

    /**
     * Fetch records that have <code>content BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    fun fetchRangeOfContent(lowerInclusive: String, upperInclusive: String): List<io.heapy.tgpt.database.tables.pojos.ThreadMessage> = fetchRange(ThreadMessage.THREAD_MESSAGE.CONTENT, lowerInclusive, upperInclusive)

    /**
     * Fetch records that have <code>content IN (values)</code>
     */
    fun fetchByContent(vararg values: String): List<io.heapy.tgpt.database.tables.pojos.ThreadMessage> = fetch(ThreadMessage.THREAD_MESSAGE.CONTENT, *values)

    /**
     * Fetch records that have <code>telegram_message_id BETWEEN lowerInclusive
     * AND upperInclusive</code>
     */
    fun fetchRangeOfTelegramMessageId(lowerInclusive: Int?, upperInclusive: Int?): List<io.heapy.tgpt.database.tables.pojos.ThreadMessage> = fetchRange(ThreadMessage.THREAD_MESSAGE.TELEGRAM_MESSAGE_ID, lowerInclusive, upperInclusive)

    /**
     * Fetch records that have <code>telegram_message_id IN (values)</code>
     */
    fun fetchByTelegramMessageId(vararg values: Int): List<io.heapy.tgpt.database.tables.pojos.ThreadMessage> = fetch(ThreadMessage.THREAD_MESSAGE.TELEGRAM_MESSAGE_ID, *values.toTypedArray())

    /**
     * Fetch records that have <code>telegram_user_id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    fun fetchRangeOfTelegramUserId(lowerInclusive: Long?, upperInclusive: Long?): List<io.heapy.tgpt.database.tables.pojos.ThreadMessage> = fetchRange(ThreadMessage.THREAD_MESSAGE.TELEGRAM_USER_ID, lowerInclusive, upperInclusive)

    /**
     * Fetch records that have <code>telegram_user_id IN (values)</code>
     */
    fun fetchByTelegramUserId(vararg values: Long): List<io.heapy.tgpt.database.tables.pojos.ThreadMessage> = fetch(ThreadMessage.THREAD_MESSAGE.TELEGRAM_USER_ID, *values.toTypedArray())

    /**
     * Fetch records that have <code>created BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    fun fetchRangeOfCreated(lowerInclusive: LocalDateTime?, upperInclusive: LocalDateTime?): List<io.heapy.tgpt.database.tables.pojos.ThreadMessage> = fetchRange(ThreadMessage.THREAD_MESSAGE.CREATED, lowerInclusive, upperInclusive)

    /**
     * Fetch records that have <code>created IN (values)</code>
     */
    fun fetchByCreated(vararg values: LocalDateTime): List<io.heapy.tgpt.database.tables.pojos.ThreadMessage> = fetch(ThreadMessage.THREAD_MESSAGE.CREATED, *values)
}
