/*
 * This file is generated by jOOQ.
 */
package io.heapy.tgpt.database.tables.daos


import io.heapy.tgpt.database.tables.Thread
import io.heapy.tgpt.database.tables.records.ThreadRecord

import java.time.LocalDateTime

import kotlin.collections.List

import org.jooq.Configuration
import org.jooq.impl.DAOImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class ThreadDao(configuration: Configuration?) : DAOImpl<ThreadRecord, io.heapy.tgpt.database.tables.pojos.Thread, Long>(Thread.THREAD, io.heapy.tgpt.database.tables.pojos.Thread::class.java, configuration) {

    /**
     * Create a new ThreadDao without any configuration
     */
    constructor(): this(null)

    override fun getId(o: io.heapy.tgpt.database.tables.pojos.Thread): Long? = o.id

    /**
     * Fetch records that have <code>id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    fun fetchRangeOfId(lowerInclusive: Long?, upperInclusive: Long?): List<io.heapy.tgpt.database.tables.pojos.Thread> = fetchRange(Thread.THREAD.ID, lowerInclusive, upperInclusive)

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    fun fetchById(vararg values: Long): List<io.heapy.tgpt.database.tables.pojos.Thread> = fetch(Thread.THREAD.ID, *values.toTypedArray())

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    fun fetchOneById(value: Long): io.heapy.tgpt.database.tables.pojos.Thread? = fetchOne(Thread.THREAD.ID, value)

    /**
     * Fetch records that have <code>chat_id BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    fun fetchRangeOfChatId(lowerInclusive: Long, upperInclusive: Long): List<io.heapy.tgpt.database.tables.pojos.Thread> = fetchRange(Thread.THREAD.CHAT_ID, lowerInclusive, upperInclusive)

    /**
     * Fetch records that have <code>chat_id IN (values)</code>
     */
    fun fetchByChatId(vararg values: Long): List<io.heapy.tgpt.database.tables.pojos.Thread> = fetch(Thread.THREAD.CHAT_ID, *values.toTypedArray())

    /**
     * Fetch records that have <code>created_by BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    fun fetchRangeOfCreatedBy(lowerInclusive: Long, upperInclusive: Long): List<io.heapy.tgpt.database.tables.pojos.Thread> = fetchRange(Thread.THREAD.CREATED_BY, lowerInclusive, upperInclusive)

    /**
     * Fetch records that have <code>created_by IN (values)</code>
     */
    fun fetchByCreatedBy(vararg values: Long): List<io.heapy.tgpt.database.tables.pojos.Thread> = fetch(Thread.THREAD.CREATED_BY, *values.toTypedArray())

    /**
     * Fetch records that have <code>forked_from_thread_id BETWEEN
     * lowerInclusive AND upperInclusive</code>
     */
    fun fetchRangeOfForkedFromThreadId(lowerInclusive: Long?, upperInclusive: Long?): List<io.heapy.tgpt.database.tables.pojos.Thread> = fetchRange(Thread.THREAD.FORKED_FROM_THREAD_ID, lowerInclusive, upperInclusive)

    /**
     * Fetch records that have <code>forked_from_thread_id IN (values)</code>
     */
    fun fetchByForkedFromThreadId(vararg values: Long): List<io.heapy.tgpt.database.tables.pojos.Thread> = fetch(Thread.THREAD.FORKED_FROM_THREAD_ID, *values.toTypedArray())

    /**
     * Fetch records that have <code>forked_at_message_id BETWEEN lowerInclusive
     * AND upperInclusive</code>
     */
    fun fetchRangeOfForkedAtMessageId(lowerInclusive: Long?, upperInclusive: Long?): List<io.heapy.tgpt.database.tables.pojos.Thread> = fetchRange(Thread.THREAD.FORKED_AT_MESSAGE_ID, lowerInclusive, upperInclusive)

    /**
     * Fetch records that have <code>forked_at_message_id IN (values)</code>
     */
    fun fetchByForkedAtMessageId(vararg values: Long): List<io.heapy.tgpt.database.tables.pojos.Thread> = fetch(Thread.THREAD.FORKED_AT_MESSAGE_ID, *values.toTypedArray())

    /**
     * Fetch records that have <code>created BETWEEN lowerInclusive AND
     * upperInclusive</code>
     */
    fun fetchRangeOfCreated(lowerInclusive: LocalDateTime?, upperInclusive: LocalDateTime?): List<io.heapy.tgpt.database.tables.pojos.Thread> = fetchRange(Thread.THREAD.CREATED, lowerInclusive, upperInclusive)

    /**
     * Fetch records that have <code>created IN (values)</code>
     */
    fun fetchByCreated(vararg values: LocalDateTime): List<io.heapy.tgpt.database.tables.pojos.Thread> = fetch(Thread.THREAD.CREATED, *values)
}
