name: "Test Telegram API"

on:
  workflow_dispatch

jobs:
  build:
    name: "Test Telegram API"
    runs-on: ubuntu-latest
    concurrency: telegram-api-tests-single
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "liberica"
      - uses: gradle/gradle-build-action@v3
      - run: ./gradlew check
        env:
          KOTBOT_TOKEN: ${{ secrets.KOTBOT_TOKEN }}
          KOTBOT_QA_USER_ID: ${{ secrets.KOTBOT_QA_USER_ID }}
          KOTBOT_QA_GROUP_ID: ${{ secrets.KOTBOT_QA_GROUP_ID }}
          KOTBOT_QA_CHANNEL_ID: ${{ secrets.KOTBOT_QA_CHANNEL_ID }}
          KOTBOT_QA_PUBLIC_CHANNEL_ID: ${{ secrets.KOTBOT_QA_PUBLIC_CHANNEL_ID }}
